### ISSUE TITLE
Calling locationWhenInUse and then locationAlways results in immediate permanentlyDenied response

### ISSUE THREAD

**Issue by armandsLa** [Baseflow/flutter-permission-handler#601] opened 2021-06-18 14:06 UTC
## 🐛 Bug Report

Calling `Permission.locationWhenInUse.request()` and then `await Permission.locationAlways.request()` results in `locationAlways` to respond immediately with permission permanently denied. However, user was prompted with "Always allow" permission request.

Code example:
```
final locationUseStatus = await Permission.locationWhenInUse.request();
if (locationUseStatus.isGranted) {
    await Permission.locationAlways.request();
}
```

### Expected behavior

`locationAlways` to wait for user action and return result accordingly 

### Reproduction steps

1. Call `Permission.locationWhenInUse.request()`
2. Wait for `locationWhenInUse` to complete
3. Call `Permission.locationAlways.request()`
4. Receive incorrect response

### Configuration

**Version:** 8.1.1

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by jasonkaruza** [comment] 2021-06-23 03:27
I too am experiencing the `.request()` returning before the permission dialog actually appears.

```
// Elsewhere in the code
await checkStoragePermissions();
// ...

Future<void> checkStoragePermissions() async {
    PermissionStatus status = await Permission.storage.request();
    if (!status.isGranted || await Permission.storage.isPermanentlyDenied) {
      if (await Permission.storage.isPermanentlyDenied) {
        // Gets to this point without popping up the permission request dialog
```

This is with `8.1.1`

**Comment by leoneparise** [comment] 2021-06-23 16:11
I'm also having the same issue for media library and camera permission. It always return `PermanentlyDenied`

**Comment by vinceve** [comment] 2021-06-26 11:33
Can confirm, ios gives immediately an permanentlyDenied

**Comment by raphaaugustosilva** [comment] 2021-06-26 16:38
This is happening with me too. Any ideas on how to workaround it?

**Comment by arasu33** [comment] 2021-06-28 13:46
Same issue occurring to me. Any solution?

**Comment by F-anleo** [comment] 2021-06-29 08:19
Did you add  'PERMISSION_LOCATION=1' to the PodFile?

https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/example/ios/Podfile

**Comment by fldvlpr** [comment] 2021-06-29 11:29
Same issue occuring to me too.

**Comment by kylqin** [comment] 2021-07-01 08:50
I face the same issue on my iOS.

**Comment by mvanbeusekom** [comment] 2021-07-01 12:12
@armandsLa and others, please make sure you enable the permissions you would like to use in your `ios/Podfile` file. Instructions are documented in the iOS section of the [README.md](https://pub.dev/packages/permission_handler). You can also have a look at the [Podfile](https://github.com/Baseflow/flutter-permission-handler/blob/30939b0a4759d8120ecce155e781964443ea258f/permission_handler/example/ios/Podfile) from our example app for a working implementation (here we enabled all available permissions).

Note: since version 8.0.0 we flipped the default behaviour. Before all permissions were enabled by default and you had to disable permissions you didn't want to use. Since version 8.0.0 we flipped this behaviour so all permissions are now disabled by default and you have to enable the permissions you would like to use in your App. More details can be found in our [CHANGELOG.md](https://pub.dev/packages/permission_handler/changelog#800)

I will close this issue now, if there are additional questions don't hesitate to leave another comment.

**Comment by jasonkaruza** [comment] 2021-07-03 03:39
I am using Android and this is the behavior that I am experiencing, still.

**Comment by mvanbeusekom** [comment] 2021-07-05 08:28
@jasonkaruza we currently confirmed an issue that has similar symptoms you describe. The problem is only shows up on Android API 30 and higher and including the `android.location.ACCESS_BACKGROUND_LOCATION` in the AndroidManifest.xml file. See also issue #771. If this is also what you are experiencing please follow this issue to track progress.

In case you are experiencing other behaviour I would like ask you to create a new issue and please include as much as information as possible. Information that would be helpful includes:

- The version of the plugin you are using;
- The output of the `flutter doctor -v` command;
- Information on the Android device / emulator you are testing with;
- Code snippet of reproducible example.

**Comment by jasonkaruza** [comment] 2021-07-10 20:26
Thanks @mvanbeusekom . I am using API 30, so I'll follow issue 771 and keep my 🤞

**Comment by MilesAdamson** [comment] 2021-07-13 17:11
This issue should not be closed. I'm experiencing it on both iOS and Android https://github.com/Baseflow/flutter-permission-handler/issues/620

**Comment by maerlynflagg** [comment] 2021-07-14 08:23
`permission_handler: ^8.1.2`

this line is not working iOS:
`final PermissionStatus _status = await Permission.calendar.request();`

the user doesn't get any UI. the line of code always return `PermissionStatus.permanentlyDenied`. both iPads with iOS 14.6 not working. no calendar entry is generated in the device app settings, where you can found all permissions.


all my Android devices working fine:

Samsung Galaxy Tab S3 (Android 9), Huawai P30 Pro (Android 10), Google Pixel 3 (Android 11). there come up UI for users and all is fine.

**Comment by mvanbeusekom** [comment] 2021-07-14 09:31
@maerlynflagg this looks like you have not configured your `ios/Podfile` correctly to enable support for the calendar permissions. Please follow the instructions in this [comment](https://github.com/Baseflow/flutter-permission-handler/issues/601#issuecomment-872194098) carefully. 

If after configuring the `ios/Podfile` correctly you are still experiencing issues, please let me know.

**Comment by JDDV** [comment] 2021-07-16 15:45
Hi @armandsLa , I worked on this issue today and made a fix where the user now can ask for the locationAlways permission. We found out today that asking for the locationAlways permission will not work, most likely because of some bug using the Apple's CLLocationManager's requestAlwaysAuthorization() method. The permission can be requested as how it will be stated in the updated documentation saying the following:
```
The `locationAlways` permission can not be requested directly, the user has to request the `locationWhenInUse` permission first.
Accepting this permission by clicking on the 'Allow While Using App' gives the user the possibility to request the `locationAlways` permission.
This will then bring up another permission popup asking you to `Keep Only While Using` or to `Change To Always Allow`.
```
The PR will be reviewed and merged most likely in the next few days. Let me know if this solved your problem so I can close the issue.

**Closed** 2021-07-22 12:47 UTC
