### ISSUE TITLE
Android storage permission status is PermissionStatus.undetermined incorrectly.

### ISSUE THREAD

**Issue by m-j-g** [Baseflow/flutter-permission-handler#327] opened 2020-06-09 16:22 UTC
## 🐛 Bug Report

Storage permission on Android will have a Status of .undetermined when it should be .isDenied and .isPermanentlyDenied.  It correctly identifies Status.isGranted when accepted.

### Reproduction steps
Deny Storage permission on Android. (or perma deny)
Check Status
Says PermissionStatus.undetermined.

**Comment by chloe722** [comment] 2020-07-09 14:19
same thing happen on me. 
Is there any workaround?

**Comment by m-j-g** [comment] 2020-07-25 12:41
> same thing happen on me.
> Is there any workaround?

I don't think so.  Don't know if anyone is maintaining this anymore.

**Comment by mikeesouth** [comment] 2020-12-03 16:02
Same as #336 ?

**Comment by Sempakonka** [comment] 2021-01-04 14:06
Hi,
To keep the issues on this repo more organized I am going to close this ticket, as I think it is a duplicate of #336. 
Don't hestitate to re-open if you think otherwise!

**Closed by Sempakonka** 2021-01-04 14:06 UTC
Labels: platform: android, status: triage
