### ISSUE TITLE
Add permission for Manifest.permission.NEARBY_WIFI_DEVICES

### ISSUE THREAD

**Issue by SherwinDeveloper** [Baseflow/flutter-permission-handler#903] opened 2022-09-02 16:23 UTC
## 🏗 Enhancement Proposal

Need permission for NEARBY_WIFI_DEVICES on Android 13.

### Pitch

Needed functionality.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment] 2022-09-28 06:43
Duplicate of #859. Work on this is in progress as part of #923.

**Closed by mvanbeusekom** 2022-09-28 06:43 UTC
