### ISSUE TITLE
On Android, notification permission status stays to `granted` despite the user denying it in the app settings.

### ISSUE THREAD

**Issue by silverhairs** [Baseflow/flutter-permission-handler#960] opened 2022-12-01 16:15 UTC
## 🐛 Bug Report

On Android, after the notification permission is granted, when the user revokes the permission in the app settings page; once they come back to the app, when `permission.status` is called again the permission status will stay to granted despite the user manually disabling it.

### Expected behavior
The permission should stay denied when the user denies it in the app settings page and comes back to the app as it does on iOS.

### Reproduction steps
```dart
import 'package:flutter/material.dart';
import 'package:permission_handler/permission_handler.dart';

void main() => runApp(const App());

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: HomePage());
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  late final NotificationPermissionListener _notificationListner;
  @override
  void initState() {
    _notificationListner = NotificationPermissionListener()..request();
    super.initState();
  }

  @override
  void dispose() {
    _notificationListner.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Title')),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Center(
          child: ValueListenableBuilder<bool>(
            valueListenable: _notificationListner,
            builder: (context, isGranted, _) => ListTile(
              title: const Text('Notification Permission'),
              trailing: Switch(
                value: isGranted,
                onChanged: (_) => _notificationListner.openSettings(),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class NotificationPermissionListener extends ValueNotifier<bool>
    with WidgetsBindingObserver {
  NotificationPermissionListener() : super(false) {
    WidgetsBinding.instance.addObserver(this);
  }
  final permission = Permission.notification;

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      permission.status.then((status) async {
       
      // Updating the value to get the latest status. If the user disables the permission, 
      // `status.isGranted` should be false.
        value = status.isGranted;
      });
    }
    super.didChangeAppLifecycleState(state);
  }

  Future<void> request() async {
    final status = await permission.request();
    value = status.isGranted;
  }

  Future<void> openSettings() async {
    await openAppSettings();
    value = await permission.isGranted;
  }

  bool get iGranted => value;
}

```

### Configuration

**Version:** ^10.2.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
---
### Update:
The bug seems to come from Android 13 and there is an [issue](https://issuetracker.google.com/issues/244387259) for it in the android issue tracker.

**Comment by peter-nilsson-scotts** [comment] 2022-12-16 20:49
I have this same issue on Android 12.

**Comment by TimHoogstrate** [comment] 2023-08-23 09:27
It looks like the issue has been resolved, at least I cannot reproduce it on Android 13. Therefore I close this issue for now. Feel free to reopen the issue when new information pops up.

**Closed by TimHoogstrate** 2023-08-23 09:27 UTC
