### ISSUE TITLE
Permission.storage.request() returns permanentlyDenied when it's allowed on android 13

### ISSUE THREAD

**Issue by salaryazdjerdi** [Baseflow/flutter-permission-handler#907] opened 2022-09-05 01:40 UTC
## 🐛 Bug Report
This used to work until recently but I think it stopped exactly as I upgraded to android 13.

### Expected behavior
return allowed

### Reproduction steps
run Permission.storage.request();

### Configuration
I have the below 2 lines in AndroidManifest:
    
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

**Version:** 
Flutter: 3.0.5
permission_handler: 10.0.0
android 13

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by armandojimenez** [comment] 2022-09-05 22:42
With Android 13 you need to ask for granular permissions. This packages does not handle the new permissions currently

**Comment by xieenming** [comment] 2022-09-09 01:50
I am facing the same error.
I see that this GitHub repo is not very active now..

Does permission_handler have plan to support Granular Media permissions (https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions) for Android 13 ? @mvanbeusekom 
Thanks.

**Comment by holy-dev** [comment] 2022-09-12 07:02
Same error for me.

When the compile sdk & target sdk both set to 33 it's not working but I'm using firebase messaging which needs it.

**Comment by Theunodb** [comment] 2022-09-14 03:24
I see there is already a PR for this. https://github.com/Baseflow/flutter-permission-handler/pull/870

**Comment by Theunodb** [comment] 2022-09-14 05:00
A temp workaround is to downgrade your targetSdkVersion to 32, while keeping compileSdkVersion on 33 to cater for firebase requirements.

**Comment by bac-huuk** [comment] 2022-09-22 04:13
Same error for me

**Comment by armandojimenez** [comment] 2022-09-22 17:06
> I see there is already a PR for this. #870

This PR was closed, so there is no support for the new granular permissions with this package.

**Comment by aytunch** [comment] 2022-09-22 22:11
I think this problem is a more broad issue. Our app crashes on Android 13 devices for every single permission requested. Do any of you know any umbrella issue where we can track android api 33 related problems?

**Comment by JGeek00** [comment] 2022-10-29 17:02
I'm facing the same issue. With target SDK 33 it doesn't work.

**Comment by xieenming** [comment] 2022-11-18 09:20
Now with the version 10.2.0 released, I think this issue is resolved.
https://pub.dev/packages/permission_handler/changelog

**Comment by piotruela** [comment] 2022-11-21 08:21
I bumped package version to 10.2.0, added permissions to manifest file and for target SDK 33 `Permission.storage.request()` is still returning `permanentlyDenied`. (Also tried `flutter clean` & clearing cache).
I created a fresh project and there everything works as expected.

**Comment by mvanbeusekom** [comment] 2022-11-21 08:25
Hi @piotruela,

Did you also update the `compileSdkVersion` in the `build.gradle` file? The path should be  `android/app/build.gradle`

**Comment by piotruela** [comment] 2022-11-21 08:27
Yep, it's also set to 33.

**Comment by xieenming** [comment] 2022-11-24 08:08
With Android 13 and above (SDK 33 and +), should use Granular media permissions:

No longer use Permission.storage.request(), but use 

- Permission.photos.request() for Read image files from external storage
- Permission.videos.request() for Read video files from external storage
- Permission.audio.request() for Read audio files from external storage

![photos](https://user-images.githubusercontent.com/68989498/203727563-a09f36ed-755b-42ca-b8ac-491a3b4eda45.png)


![videos and audio](https://user-images.githubusercontent.com/68989498/203727534-d6ad7221-8347-44df-9deb-2026ad011278.png)

**Comment by VatsalShah03** [comment] 2022-12-15 05:49
I want to request permission to download PDFs from firebase, how do I do that?

**Comment by aytunch** [comment] 2023-01-10 15:37
@daveshirman Thanks for sharing the code. I haven't tested it yet but if it works, should the Android version checking be somehow seamlessly baked in to the plugin instead of living in our code? Or at least it should be mentioned in the documentation.

**Comment by daveshirman** [comment] 2023-01-10 17:12
> @daveshirman Thanks for sharing the code. I haven't tested it yet but if it works, should the Android version checking be somehow seamlessly baked in to the plugin instead of living in our code? Or at least it should be mentioned in the documentation.

I wrapped the code in a platform check, e.g.

```
// Check for relevant permissions.
if (Platform.isIOS) {
  bool storage = await Permission.storage.status.isGranted;
  if (storage) {
    // Awesome
  } else {
    // Crap
  }
} else {
  bool storage = true;
  bool videos = true;
  bool photos = true;

  // Only check for storage < Android 13
  DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
  AndroidDeviceInfo androidInfo = await deviceInfo.androidInfo;
  if (androidInfo.version.sdkInt >= 33) {
    videos = await Permission.videos.status.isGranted;
    photos = await Permission.photos.status.isGranted;
  } else {
    storage = await Permission.storage.status.isGranted;
  }

  if (storage && videos && photos) {
    // Awesome
  } else {
    // Crap
  }
}
```

**Comment by brunovsiqueira** [comment] 2023-02-14 16:42
Any updates on this? Affecting several production users.

**Comment by WatchDogsDev** [comment] 2023-03-04 13:02
Any updates ?

**Comment by jkydevelopment** [comment] 2023-03-10 19:59
Please we need some update about this issue. Thanks in advance.

**Comment by jkydevelopment** [comment] 2023-03-10 19:59
Please we need some update about this issue. Thanks in advance.

**Comment by jkydevelopment** [comment] 2023-03-10 19:59
Please we need some update about this issue. Thanks in advance.

**Comment by Tapankumardang** [comment] 2023-04-05 14:58
hi i got the solution which is working for me ,also using permission_handler: ^10.2.0.

change   **targetSdkVersion 31** in build.gradle 

As SdkVersion 33 is for android 13 , changing it to 31 (android 12) .

so, may be it changing to 31 works as backward compatibility.

`
    defaultConfig {
      
        applicationId "com.example.example"
        minSdkVersion 28
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }`


for permission 
` var status = await Permission.storage.status;
    debugPrint("storage permission " + status.toString());
    if (await Permission.storage.isDenied) {
    
      debugPrint("sorage permission ===" + status.toString());
     
      await Permission.storage.request();
    } else {
      debugPrint("permission storage " + status.toString());
     // do something with storage like file picker
    }`

**Comment by dubocr** [comment] 2023-06-14 09:03
Some package limits READ_EXTERNAL_STORAGE permission until sdk 29 only, to make sure permission are set in manifest for sdk 30,31 and 32, you could try :

`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:replace="android:maxSdkVersion" android:maxSdkVersion="32"/>`

**Comment by JeroenWeener** [comment] 2023-07-03 11:33
This is a duplicate of #955. As mentioned there, there are changes to Android in 13, where requesting storage should be done using the granular media permissions. For more information, you can have a look here: https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions.

**Closed by JeroenWeener** 2023-07-03 11:33 UTC
Labels: platform: android, type: bug

**Comment by ashrith122** [comment] 2024-02-10 05:43
hi iam facing this error still can anyone help me out    
 Future<void> _downloadPdf() async {
    try {
      bool storagePermissionGranted = false;

      if (Platform.isAndroid) {
        if (_getAndroidSdkVersion() >= 33) {
          // For Android 13 and above, use granular media permissions
          PermissionStatus photosStatus = await Permission.photos.request();
          PermissionStatus storageStatus = await Permission.storage.request();

          if (photosStatus.isGranted && storageStatus.isGranted) {
            storagePermissionGranted = true;
          } else if (photosStatus.isDenied || storageStatus.isDenied) {
            // The user denied permission, show a request dialog
            storagePermissionGranted = false;
            await openAppSettings();
          } else {
            // Handle permission denied
            storagePermissionGranted = false;
          }
        } else {
          // For Android 12 and below, use the old storage permission
          storagePermissionGranted = await Permission.storage.request().isGranted;
        }
      }

      if (storagePermissionGranted) {
        final response = await http.get(Uri.parse(url));

        if (response.statusCode == 200) {
          final directory = await getApplicationDocumentsDirectory();
          final filename = 'quotation.pdf';
          final filePath = '${directory.path}/$filename';

          final file = File(filePath);
          await file.writeAsBytes(response.bodyBytes);

          // Open the downloaded PDF file
          OpenFile.open(file.path);
        } else {
          // Handle HTTP error
          print('HTTP Error: ${response.statusCode}');
        }
      } else {
        // Handle storage permission denied
        print('Storage Permission Denied');
        // You can show a dialog or toast to inform the user about the permission denial
      }
    } catch (e, stackTrace) {
      // Handle general exceptions
      print('Error during download: $e');
      print('StackTrace: $stackTrace');
    }
  }



defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.safestorage_supervisour"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion 21
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }




<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />

**Comment by subrahmanyashedge** [comment] 2024-07-02 13:44
void downLoadNetworkFile(String url) async {
    final fileName = getFileNameFromUrl(url);
    final status = await Permission.storage.request();

    if (await Permission.manageExternalStorage.request().isGranted) {

      final id = await FlutterDownloader.enqueue(
        fileName: fileName,
        url: url,
        savedDir: '/storage/emulated/0/Download',
        showNotification: true,
        openFileFromNotification: true,
      );
    } else {
      print('Permission Denied');
    }
  }
  
  someone help me here , for some devices its working , getting denied for some devices

**Comment by honeybansal2968** [comment] 2024-07-21 06:43
@ashrith122 I am facing same problem as you do for pdf download and fetching. 
Have you any solution to this?

**Comment by subrahmanyashedge** [comment] 2024-07-25 08:41
@honeybansal2968  from the above code you can download files .
