### ISSUE TITLE
App Tracking Transparency prompt not showing on iOS 15

### ISSUE THREAD

**Issue by thegrxp** [Baseflow/flutter-permission-handler#676] opened 2021-09-25 14:42 UTC
## 🐛 Bug Report

I noticed the ATT prompt is not showing up on iOS 15. Not on the iOS Simulator and also not on my physical iPhone.
See: https://www.reddit.com/r/iOSProgramming/comments/pt41jz/att_prompt_not_showing_on_ios_15/

**Version:** 8.1.6

**Platform:** 
- [x] :iphone: iOS 15

**Comment by Kurogoma4D** [comment] 2021-10-04 03:38
Same here, and my job app has rejected review due to this.

**Comment by RafaelBarbosatec** [comment] 2021-10-05 12:38
I'm in the same situation. My app was rejected and I can't upload because of this issue.

**Comment by speedlightwp** [comment] 2021-10-10 03:00
version 8.2.2

I called my permission request in initstate. It was working perviously on IOS 14.x, now not working in IOS 15 anymore.

**Comment by ernesto** [comment] 2021-11-02 15:03
Same problem, v8.2.5

**Comment by usaikoo** [comment] 2021-12-13 11:52
Same here as well. requestTrackingAuthorization is not working in ios 15

**Comment by noneed52** [comment] 2022-02-20 13:03
This still issue with v8.3.0... 
When will it be fixed?

**Comment by jay2jp** [comment] 2022-06-11 18:06
i found it, in the settings go to privacy and then tracking and allow for tracking and it stops being permanently denied

**Comment by hassanbasri** [comment] 2022-07-06 09:36
it happened with me as well. the issue is it does not work the first time one opens the app. so  install the app. login and then close the app completely and then start it again it will show the prompt. I have used this as a solution the app reviewers and they accepted my app

**Comment by omatt** [comment] 2022-09-29 02:31
I encountered the same issue, the prompt isn't being displayed on iOS 15.5 even with `Allow Apps to Request to Track` enabled under `Settings > Privacy`. I ended up using [app_tracking_transparency](https://pub.dev/packages/app_tracking_transparency) plugin instead.

**Comment by michaelsof47** [comment] 2022-10-10 02:39
so, how about conclusion about this case?

**Comment by moesaid** [comment] 2023-03-27 20:02
same issue , 
any update here ?

**Comment by techouse** [comment] 2023-05-18 17:26
I just tested it on iOS 15.5 and it works just fine.

**Comment by TimHoogstrate** [comment] 2023-08-04 07:58
It seems to us that this issue is no longer valid or solved in the meantime. Therefore, we will close this issue. Feel free to reopen the issue when it reappears or if it has not been resolved. Also please inform us about the steps to reproduce and possibly the output of `flutter doctor -v`.

**Closed by TimHoogstrate** 2023-08-04 07:58 UTC
Labels: platform: ios, type: bug, P2
