### ISSUE TITLE
[iOS] permissions.request() not working correctly

### ISSUE THREAD

**Issue by galunecandrey** [Baseflow/flutter-permission-handler#588] opened 2021-06-09 21:35 UTC
Hi, 
I'm using : permission_handler: ^8.0.1 ,
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)

Device: **iPhone 8**

When i check `Permission.notification` results is:
- isGranted: false,
- isDenied: true 
- **isPermanentlyDenied: false**

but when i tried to call `permissions.request()` the result always is `PermissionStatus.permanentlyDenied` without any alerts

When i check `Permission.locationWhenInUse` results is:
- isGranted: false,
- isDenied: true 
- **isPermanentlyDenied: false**

but when i tried to call `permissions.request()` the result always is `PermissionStatus.permanentlyDenied` without any alerts too...

**Comment by tannercrook** [comment] 2021-06-10 00:14
I am seeing the same issue. It appears that the request is never registered in the app settings either.

**Comment by jlubeck** [comment] 2021-06-10 02:25
Probably the same as what I'm experiencing here: https://github.com/Baseflow/flutter-permission-handler/issues/585

**Comment by mvanbeusekom** [comment] 2021-06-10 06:54
Closing this issue as duplicate of #585. I will track progress there.

**Comment by galunecandrey** [comment] 2021-06-10 13:11
@mvanbeusekom I do not understand how this is related to that problem? You yourself wrote that bluetooth has a different behavior with permissions. I indicate a problem for notifications and locations.

**Comment by mvanbeusekom** [comment] 2021-06-10 13:25
@galunecandrey you are right I maybe acted prematurely, at first glance the issue looked similar. I re-opened the issue. However this problem looks very close to wrongly configured `ios/Podfile` file. Please make sure you enabled the permissions in your `ios/Podfile` file and added the necessary configuration to the `ios/Runner/Info.plist` file as documented in the "iOS" section of our [README.md](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/README.md) file. 

>Note: take special attention to the fact that we flipped the configuration in your `ios/Podfile` since version 8.0.0 of the plugin. Pre version 8.0.0 all permissions were enabled by default and you had to configure the permissions you didn't want to use. Since version 8.0.0 you will have to explicitly "enable" permissions you want to use.

If you continue to have problems please provide the following information:

1. Contents of your `ios/Podfile` and `ios/Runner/Info.plist` files;
2. Code snippet on how you use the plugin (preferably a complete reproduction example).

**Comment by galunecandrey** [comment] 2021-06-10 13:54
@mvanbeusekom Thank you! You are right. The problem was breaking changes from version 8.0.0

**Closed** 2021-06-10 13:54 UTC
Labels: platform: ios

**Comment by imiskolee** [comment] 2021-06-28 07:20
#607  same issue here.
