### ISSUE TITLE
Unexpected content of Location permission popup under iOS

### ISSUE THREAD

**Issue by bambinoua** [Baseflow/flutter-permission-handler#197] opened 2020-01-29 15:22 UTC
### Expected behavior

When permission _locationAlways_ is asked it is expected popup screen with option _Allow Always_ but there is no such option. Only those ones are visible _Allow when using app_, _Allow once_, _Never_.

### Reproduction steps

Just call:
`PermissionHandler().requestPermissions([PermissionGroup.locationAlways]);`

### Configuration

**Version:** 4.2.0-hotfix.2

**Platform:** 
- [x] :iphone: iOS

**Comment by mvanbeusekom** [comment] 2020-01-29 15:48
Hello @bambinoua, just to start and help us debug this issue, which keys did you register in your `Info.plist` (should be inside the iOS folder of your Flutter App)?  

For always permissions the `Info.plist` should have the `NSLocationAlwaysAndWhenInUseUsageDescription` key listed. Can you verify that it is there?

**Comment by bambinoua** [comment] 2020-01-30 08:36
I checked `Info.plist` and these keys are present:
`NSLocationAlwaysAndWhenInUseUsageDescription`
`NSLocationWhenInUseUsageDescription`
`NSLocationAlwaysUsageDescription`

**Comment by arok** [comment] 2020-02-12 11:54
Same for me

**Comment by arok** [comment] 2020-02-12 12:04
Looks like it is expected behaviour https://medium.com/better-programming/understanding-new-location-permission-changes-in-ios-13-6c34dc5f54da

**Comment by mvanbeusekom** [comment] 2020-04-03 14:54
Closing this issue, as it seems it is indeed expected behaviour. Thanks @arok for helping out.

**Closed by mvanbeusekom** 2020-04-03 14:54 UTC
Labels: platform: ios, status: needs more info
