### ISSUE TITLE
contacts permission is inconsistent in iOS emulator

### ISSUE THREAD

**Issue by aaronscherbing** [Baseflow/flutter-permission-handler#763] opened 2021-12-30 15:16 UTC
## 🐛 Bug Report

When I request contacts permission, I get `permanentlyDenied`:
`PermissionStatus status = await Permission.contacts.request();`

When I later fetch the contacts status, I get `denied`:
`PermissionStatus contacts = await Permission.contacts.status;`

### Expected behavior

If the request returns permanentlyDenied, the subsequently fetched status should also be permanentlyDenied.

### Reproduction steps

See above.

### Configuration

Flutter - 2.8.1
permission_handler - 8.3.0
iOS Simulator - iPhone 13 iOS 15.2
Xcode - 13.2
Mac M1

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by wizardoma** [comment] 2022-08-17 20:07
I am having the same issue. Have anyone found a solution to this?

**Comment by TimHoogstrate** [comment] 2023-08-24 07:25
I personally cannot reproduce this issue. Therefore, I close this issue. Feel free to reopen when new information pops-up. If so, please try to add the output of `flutter doctor -v` to this issue. 

Kind regards,

**Closed** 2023-08-24 07:25 UTC
Labels: platform: ios

**Comment by EliaTolin** [comment] 2024-06-03 13:23
**Solution:** 
in ios/Podfile check if permission_contacts is equal to:

```
        # dart: PermissionGroup.contacts
        'PERMISSION_CONTACTS=1',
```
