### ISSUE TITLE
OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by RoyalCoder88** [Baseflow/flutter-permission-handler#818] opened 2022-03-23 14:26 UTC
## 🐛 Bug Report

**Version:** **permission_handler 9.2.0**

**Platform:** 
- [ √] :robot: Android
- **OS Version: 11**
- 
**Flutter doctor:**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.22000.556], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.10)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.65.2)
[√] Connected device (5 available)
[√] HTTP Host Availability

Hi friends I'm trying to get files from my phone in a simple flutter project I get these errors:

`[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Directory listing failed, path = '/storage/emulated/0/Android/data' (OS Error: Permission denied, errno = 13)`

I tried a lot of fixes in Android Manifest change code etc. nothing :( can you please help me with it? Thanks in advance!

**Comment by mvanbeusekom** [comment] 2022-03-25 10:18
Duplicate of #313

**Closed by mvanbeusekom** 2022-03-25 10:18 UTC
