### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by michaeljajou** [Baseflow/flutter-permission-handler#1178] opened 2023-10-03 13:25 UTC
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

1. Fresh Install App that requests Calendar Permissions on a device running iOS 17.0
2. Request Calendar Permissions using `Permission.calendar.request()`
3. The permission will come back as permanently denied

### Expected results

An alert pops up that should request the user to enable calendar permissions

### Actual results

The alert does not pop up and instead just returns a permission status as permanently denied

### Code sample

N/A

### Screenshots or video

N/A

### Version

11

### Flutter Doctor output

N/A

**Comment by MilosKarakas** [comment] 2023-10-03 17:51
@michaeljajou Please check https://github.com/Baseflow/flutter-permission-handler/pull/1151

**Comment by JeroenWeener** [comment] 2023-10-04 08:11
I am closing this issue as it is a duplicate of #1151.

**Closed** 2023-10-04 08:53 UTC
