### ISSUE TITLE
[Bug] Storage permission not requested on Android 13

### ISSUE THREAD

**Issue by laminr** [Baseflow/flutter-permission-handler#955] opened 2022-11-16 16:28 UTC
## 🔙 Regression

Try to get the Storage permission doing
`if (await Permission.storage.request().isGranted) ...`

The request() do nothing on Android 13, No dialog box shown. But works on Android 12 en previous

### Old (and correct) behavior
Permission.storage.request() show permission request dialog
It is working on Android 12 and below

### Current behavior
Permission.storage.request() does nothing, nothing is happening.

### Configuration
Storage permission is not shown in the App Permissions page (Allowed or Not)
and yet I have :
```
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <!-- From Android 11    -->
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
```

in Android Manifest.
**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by Alfaizkhan** [comment] 2022-11-17 06:38
Same issue 👍🏼

**Comment by joknjokn** [comment] 2022-11-23 09:30
This is pretty critical, I think. Any updates or ETA?

I'm not aware of any workaround - not even downgrading the version. So basically all functionality regarding this, like image-upload, is broken for all Flutter apps for Android 13 - right?

**Comment by abhinavsinghring** [comment] 2022-11-25 06:26
> This is pretty critical, I think. Any updates or ETA?
> 
> I'm not aware of any workaround - not even downgrading the version. So basically all functionality regarding this, like image-upload, is broken for all Flutter apps for Android 13 - right?

If your app download files like pdf in storage then in 13 no permission is required for your application directory ask for getApplicationDocumentDirectory using path_provider and save your file in app directory then create download page in your app and using builder list all files available in given storage and give button to open file (you can use open_file).

**Comment by EArminjon** [comment] 2022-12-06 09:25
> > This is pretty critical, I think. Any updates or ETA?
> > I'm not aware of any workaround - not even downgrading the version. So basically all functionality regarding this, like image-upload, is broken for all Flutter apps for Android 13 - right?
> 
> If your app download files like pdf in storage then in 13 no permission is required for your application directory ask for getApplicationDocumentDirectory using path_provider and save your file in app directory then create download page in your app and using builder list all files available in given storage and give button to open file (you can use open_file).

So this permission should be GRANTED by default no ?

**Comment by abhinavsinghring** [comment] 2022-12-06 09:58
I don't know about reading files from storage but in my app users can download pdf files from network so using path provider plugin i have asked for appDocumentDirectory then save files in them and then created download page to show all downloaded files and then created a button with function to save files to download folder of storage/emulated/0/Download using lecle download path plugin which gets this path and copy file from appDir to DownloadDir or u can directly use this plugin to download in storage/emulated/0/Download.

**Comment by abhinavsinghring** [comment] 2022-12-06 10:02
> > > This is pretty critical, I think. Any updates or ETA?
> > > I'm not aware of any workaround - not even downgrading the version. So basically all functionality regarding this, like image-upload, is broken for all Flutter apps for Android 13 - right?
> > 
> > If your app download files like pdf in storage then in 13 no permission is required for your application directory ask for getApplicationDocumentDirectory using path_provider and save your file in app directory then create download page in your app and using builder list all files available in given storage and give button to open file (you can use open_file).
> 
> So this permission should be GRANTED by default no ? Because of that, we must add extra logique inside our apps to check if android is api 33 when using that :/

Remove permission handler for storage and it work fine because in API 33 no such permission exist so it will always return empty.

**Comment by EArminjon** [comment] 2022-12-06 10:04
Yep so external logic required. Maybe this must be write inside the package documentation ?

**Comment by abhinavsinghring** [comment] 2022-12-06 10:09
Not available anything in documentation.

**Comment by EArminjon** [comment] 2022-12-06 10:15
> Not available anything in documentation.

So it must be added...

**Comment by EArminjon** [comment] 2022-12-06 10:23
On my app i've something like that now : 
```dart
Future<bool> checkStoragePermission(BuildContext context) async {
  // No need to ask this permission and Android 13 (API 33)
 if (Platform.isAndroid) {
    final DeviceInfoPlugin deviceInfoPlugin = DeviceInfoPlugin();
    final AndroidDeviceInfo info = await deviceInfoPlugin.androidInfo;
    if ((info.version.sdkInt ?? 0) >= 33) return true;
  }
  if (!await requestPermission(<Permission>[Permission.storage])) {
    // pop up to redirect user to phone settings
    return false;
  }
  return true;
}
```

**Comment by okbye123** [comment] 2023-03-17 12:27
This might help https://www.youtube.com/watch?v=uMvGpBOT0ZY

**Comment by mbfakourii** [comment] 2023-04-28 12:54
```dart
 _checkStoragePermission() async {
    PermissionStatus status;
    if (Platform.isAndroid) {
      final DeviceInfoPlugin deviceInfoPlugin = DeviceInfoPlugin();
      final AndroidDeviceInfo info = await deviceInfoPlugin.androidInfo;
      if ((info.version.sdkInt) >= 33) {
        status = await Permission.manageExternalStorage.request();
      } else {
        status = await Permission.storage.request();
      }
    } else {
      status = await Permission.storage.request();
    }

    switch (status) {
      case PermissionStatus.denied:
        return false;
      case PermissionStatus.granted:
        return true;
      case PermissionStatus.restricted:
        return false;
      case PermissionStatus.limited:
        return true;
      case PermissionStatus.permanentlyDenied:
        return false;
    }
  }
```

**Comment by osamamohammed98** [comment] 2023-05-23 08:54
> ```dart
> _checkStoragePermission() async {
>   PermissionStatus status;
>   if (Platform.isAndroid) {
>     final DeviceInfoPlugin deviceInfoPlugin = DeviceInfoPlugin();
>     final AndroidDeviceInfo info = await deviceInfoPlugin.androidInfo;
>     if ((info.version.sdkInt) >= 33) {
>       status = await Permission.manageExternalStorage.request();
>     } else {
>       status = await Permission.storage.request();
>     }
>   } else {
>     status = await Permission.storage.request();
>   }
> 
>   switch (status) {
>     case PermissionStatus.denied:
>       return false;
>     case PermissionStatus.granted:
>       return true;
>     case PermissionStatus.restricted:
>       return false;
>     case PermissionStatus.limited:
>       return true;
>     case PermissionStatus.permanentlyDenied:
>       return false;
>   }
> }
> ```

in api 33 and more you not need Permission 
i try it in my case and it work

**Comment by rodolfocop** [comment] 2023-06-29 16:08
+1

**Comment by JeroenWeener** [comment] 2023-06-30 10:22
I found the likely culprit. Both `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` permissions have been deprecated in Android 13.

```
READ_EXTERNAL_STORAGE is deprecated (and is not granted) when targeting Android 13+. If you need to query or interact with MediaStore or media files on the shared storage, you should instead use one or more new storage permissions: READ_MEDIA_IMAGES, READ_MEDIA_VIDEO or READ_MEDIA_AUDIO.
```

```
WRITE_EXTERNAL_STORAGE is deprecated (and is not granted) when targeting Android 13+. If you need to write to shared storage, use the MediaStore.createWriteRequest intent.
```

**Comment by mvanbeusekom** [comment] 2023-06-30 10:47
Adding to @JeroenWeener's comment, to request the new media storage permissions use the following:

- "READ_MEDIA_IMAGE" maps to `Permission.photos`.
- "READ_MEDIA_VIDEO" maps to `Permission.video`.
- "READ_MEDIA_AUDIO" maps to `Permission.audio`.

When file system access is really necessary it is possible to call `Permission.manageExternalStorage`, this however requires additional argumentation when uploading the final application to the Google's Play Store. More information can be found here: https://support.google.com/googleplay/android-developer/answer/10467955?hl=en.

I will go ahead and close this issue as the permission handler is working as intended.

**Closed by mvanbeusekom** 2023-06-30 10:47 UTC
Labels: good first issue, platform: android, type: bug

**Comment by mbfakourii** [comment] 2024-04-29 09:16
> Adding to @JeroenWeener's comment, to request the new media storage permissions use the following:
> 
> * "READ_MEDIA_IMAGE" maps to `Permission.photos`.
> * "READ_MEDIA_VIDEO" maps to `Permission.video`.
> * "READ_MEDIA_AUDIO" maps to `Permission.audio`.
> 
> When file system access is really necessary it is possible to call `Permission.manageExternalStorage`, this however requires additional argumentation when uploading the final application to the Google's Play Store. More information can be found here: https://support.google.com/googleplay/android-developer/answer/10467955?hl=en.
> 
> I will go ahead and close this issue as the permission handler is working as intended.

What should be done to save pdf and zip files, etc.?
