### ISSUE TITLE
[Bug]: locationAlwaysPermission.request() instantly resolves with permanently denied, even though the dialog to ask a user is being displayed

### ISSUE THREAD

**Issue by niksen75** [Baseflow/flutter-permission-handler#1155] opened 2023-09-16 11:43 UTC
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

Re-introduction of closed issue: https://github.com/Baseflow/flutter-permission-handler/issues/620

### Expected results

// expected this future to not complete, until the dialog is closed by the user
final alwaysStatus = await locationAlwaysPermission.request(); 

### Actual results

// this future completes instantly, even though the dialog is still visible to the user
final alwaysStatus = await locationAlwaysPermission.request(); 

### Code sample

<details><summary>Code sample</summary>

```dart
void processAskForLocationPermission() async {
final whenInUseStatus = await locationWhenInUsePermission.request();
print("whenInUseStatus: $whenInUseStatus");

if (whenInUseStatus == PermissionStatus.permanentlyDenied || whenInUseStatus == PermissionStatus.denied) {
  return;
}

// this future completes instantly, even though the dialog is still visible to the user
final alwaysStatus = await locationAlwaysPermission.request(); 
// this prints "always: PermissionStatus.permanentlyDenied" immediately after the above line finishes
print("always: $alwaysStatus");
}
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

permission_handler: ^10.4.5

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Flutter doctor:
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-x64, locale en-GB)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] VS Code (version 1.82.0)
[✓] Connected device (2 available)
[✓] Network resources

Dart info:

Dart 3.0.6 (stable) (Tue Jul 11 18:49:07 2023 +0000) on "macos_x64"
on macos / Version 13.4.1 (c) (Build 22F770820d)
locale is en-GB
```

</details>

**Comment by niksen75** [comment] 2023-09-16 11:45
Configuration as mentioned in this comment https://github.com/Baseflow/flutter-permission-handler/issues/620#issuecomment-1721318980

**Comment by JeroenWeener** [comment] 2023-09-18 08:16
Duplicate of #1152

**Closed by JeroenWeener** 2023-09-18 08:16 UTC
Labels: platform: ios, type: bug, P2
