### ISSUE TITLE
final permission = Permission.manageExternalStorage.request();

### ISSUE THREAD

**Issue by tluanga** [Baseflow/flutter-permission-handler#636] opened 2021-07-25 07:11 UTC
While using Pemission handler inside main function it throws an exception.
`void main() async {
final permission = Permission.manageExternalStorage.request();
if (await permission.isGranted){
}`
Error: Exception has occurred. _CastError (Null check operator used on a null value)

**Comment by mvanbeusekom** [comment] 2021-07-25 20:17
Hi @tluanga,

This is probably caused by the the Flutter activity not being registered with Android yet. 

Please make sure to call `WidgetsFlutterBinding.ensureInitialized()` method before you make any calls to the `permission_handler` (this would be true for any plugin b.t.w.)

**Comment by CellCS** [comment] 2021-09-17 19:01
**Permission.manageExternalStorage.request() Issue.**

env: version 8.1.6, version  6.1.1, Android 10

Permission.manageExternalStorage.request() return **"restricted"** in version 8.1.6, but return "denied" (this is supposed) in version 6.1.1. 


**Issue 1:** : permission status:
test code 1: **var status = await Permission.manageExternalStorage.status;** 

returns: PermissionStatus.restricted in version 8.1.6, but  PermissionStatus.denied in version 6.1.1, both has following exception log:
`_D/permissions_handler( 8074): No permissions found in manifest for: []22`

**Issue 2:** : no permission request happens.
test code 2: **status = await Permission.manageExternalStorage.request()**  do nothing and does not pops up permission request dialog, and has log:
`_D/permissions_handler( 8074): No permissions found in manifest for: []22`

For test code 2: double-check the AndroidManifest.xml file for main, debug, profile. all have: 
```
    <!-- %%INSERT_PERMISSIONS -->
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```
**Potential solution tries:**

1 Flutter clean and WidgetsFlutterBinding.ensureInitialized() does not help.

**Comment by JDDV** [comment] 2021-09-30 10:21
Hi @CellCS, for the `manageExternalStorage` permission you need another line in your `AndroidManifest` than you mentioned.
The line you need to add is as follows:

```
<!-- Permissions options for the `manage external storage` group -->
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
```

Then you can try the `flutter clean` followed by the `flutter pub get`, let me know if it worked, thanks in advance!

**Comment by CellCS** [comment] 2021-10-11 16:52
@JDDV thanks, no lucky. tried with add in `AndroidManifest`, tried `flutter clean` followed by `flutter pub get`

**Comment by laxkarparas1** [comment] 2021-11-12 12:25
> > @JDDV I am having the same issue, I tried flutter clean but I am still facing an issue, there is no popup for confirming and the status comes as restricted for `Permission.manageExternalStorage`.
> > Manifest debug:
> > ```
> > <manifest xmlns:android="http://schemas.android.com/apk/res/android"
> >     package="com.example.yt_player">
> >     
> >     <uses-permission android:name="android.permission.INTERNET"/>
> >     <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
> >     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
> >     <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
> >     
> > </manifest>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Manifest profile:
> > ```
> > <manifest xmlns:android="http://schemas.android.com/apk/res/android"
> >     package="com.example.yt_player">
> >     
> >     <uses-permission android:name="android.permission.INTERNET"/>
> >     <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
> >     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
> >     <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
> > </manifest>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Manifest main:
> > ```
> > <manifest xmlns:android="http://schemas.android.com/apk/res/android"
> >     package="com.example.yt_player">
> >     <uses-permission android:name="android.permission.INTERNET"/>
> >     <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
> >     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
> >     <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
> >    <application
> >         android:label="yt_player"
> >         android:icon="@mipmap/ic_launcher">
> >         <activity
> >             android:name=".MainActivity"
> >             android:launchMode="singleTop"
> >             android:theme="@style/LaunchTheme"
> >             android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
> >             android:hardwareAccelerated="true"
> >             android:requestLegacyExternalStorage="true"
> >             android:windowSoftInputMode="adjustResize">
> >             
> >             <meta-data
> >               android:name="io.flutter.embedding.android.NormalTheme"
> >               android:resource="@style/NormalTheme"
> >               />
> >             
> >             <meta-data
> >               android:name="io.flutter.embedding.android.SplashScreenDrawable"
> >               android:resource="@drawable/launch_background"
> >               />
> >             <intent-filter>
> >                 <action android:name="android.intent.action.MAIN"/>
> >                 <category android:name="android.intent.category.LAUNCHER"/>
> >             </intent-filter>
> >         </activity>
> >         
> >         <meta-data
> >             android:name="flutterEmbedding"
> >             android:value="2" />
> >     </application>
> > </manifest>
> > ```
> 
> Issue fixed I moved the android:requestLegacyExternalStorage="true" to the application tag

still giving error 
any solution???

**Comment by neoacevedo** [comment] 2022-03-20 00:04
This happens to me in a weird mode. An app raises the following error:

> Unhandled Exception: Null check operator used on a null value

But another app, same code to request for permissions works perfectly.

**Comment by TimHoogstrate** [comment] 2023-08-24 09:04
It seems to work fine on Android 13 Example app. Do you have some additional information regarding Android version that you are testing on?

Kind regards,

**Comment by Rizwan201** [comment] 2023-09-04 11:35
@TimHoogstrate facing the same issue the device is Android 10

**Comment by mvanbeusekom** [comment] 2023-09-12 13:12
Hi @Rizwan201,

The `MANAGE_EXTERNAL_STORAGE` permission is introduced in Android API 30 (which relates to Android 11) as a replacement for the `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` permissions. 

As a developer it is currently your responsibility to validate which Android version your app is running on and request the appropriate permission. 

I am going to go ahead and close this issue as the original problem was solved by making sure the `ensureInitialized` method was called before accessing the permission_handler.

**Closed by mvanbeusekom** 2023-09-12 13:12 UTC
Labels: platform: android
