### ISSUE TITLE
App crashes when switching on/off bluetooth permissions in iOS settings

### ISSUE THREAD

**Issue by Annelein** [Baseflow/flutter-permission-handler#509] opened 2021-03-30 08:20 UTC
I am building an app using Flutterblue and for that I need bluetooth to be switched on and bluetooth permissions. I am using permission handler to check it like this:

`bluetoothPermission = await Permission.bluetooth.isGranted;`

I've created a button which is green when bluetooth permission is granted and blue when not, I've created my own stream to listen to `bluetoothPermission = await Permission.bluetooth.isGranted;
`
But when I open my app settings on iOS and either switch on or off the bluetooth permission, my app crashes and I receive this SIGKILL:

`* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGKILL
    frame #0: 0x00000001dd2fb644 libsystem_kernel.dylib`mach_msg_trap + 8
libsystem_kernel.dylib`mach_msg_trap:
->  0x1dd2fb644 <+8>: ret    
libsystem_kernel.dylib`mach_msg_overwrite_trap:
    0x1dd2fb648 <+0>: mov    x16, #-0x20
    0x1dd2fb64c <+4>: svc    #0x80
    0x1dd2fb650 <+8>: ret    
Target 0: (Runner) stopped.
Lost connection to device.`

I do the same exact same with location switched on and location permission but that goes fine.

Can anyone help me out with this problem? I have no clue where to look or what might cause this.

**Comment by brosnic** [comment] 2021-04-01 13:07
I can see the exact same error with the camera permission.
And I can confirm that it works with locations (and for notifications)

**Comment by petro-i** [comment] 2021-05-24 06:35
@Annelein it is normal behavior on iOS, nothing to do with the plugin.

**Comment by Lawati97** [comment] 2021-08-17 07:31
@petro-i even in android

**Comment by Lawati97** [comment] 2021-08-17 07:34
even if I restart the application the moment I go to the page where it checks for that permission in crashes

**Comment by tas246** [comment] 2022-04-23 23:51
This issue is happening to me as well in iOS - App detects the user has permanently denied bluetooth access, prompts them to go to the settings page.  On the settings page, if they switch Bluetooth to the ON position the app instantly crashes:

* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGKILL
    frame #0: 0x00000002100d74e0 libsystem_kernel.dylib`mach_msg_trap + 8
libsystem_kernel.dylib`mach_msg_trap:
->  0x2100d74e0 <+8>: ret
libsystem_kernel.dylib`mach_msg_overwrite_trap:
    0x2100d74e4 <+0>: mov    x16, #-0x20
    0x2100d74e8 <+4>: svc    #0x80
    0x2100d74ec <+8>: ret
Target 0: (Runner) stopped.
Lost connection to device.

Anyone have a solution for this?

**Comment by luggy-wuggy** [comment] 2022-04-29 19:07
This isn't an issue pertaining to the package, as explained in this [comment](https://github.com/Baseflow/flutter-permission-handler/issues/293#issuecomment-1079923473) from similar issue #293 

> This is not a problem of this lib.
If you try to run you app without doing anything and open iOS settings and try to change app permission the app exit automatically.

You can test this behavior on any existing apps.

ie. Instagram.
1. If you go deep into a navigation flow
2. have some state in a page (scroll, content)
3. close the app (not kill)
4. go to OS settings
5. toggle Instagram permissions
6. go back to Instagram app
7. you'll notice that Instagram is rebooted again from scratch (not saving any of your previous states)

Since the app is essentially "rebooted", Flutter assumes you `Lost connection to device`and throws this error and In order to get around this to test your app. You would need to launch in release mode

in the terminal
`flutter run --release`

**Comment by konradjurkowski** [comment] 2022-12-01 10:45
@luggy-wuggy thanks, works exactly as you said

**Comment by bakboem** [comment] 2023-02-01 02:09
@luggy-wuggy  Thank you～～～～, I thought there was something wrong with my program

**Comment by JeroenWeener** [comment] 2023-07-03 14:20
Closing this issue, as the problem has been identified: the behavior is driven by the OS, not the plugin. See the https://github.com/Baseflow/flutter-permission-handler/issues/509#issuecomment-1113636977 for an explanation. Thanks @luggy-wuggy!

**Closed by JeroenWeener** 2023-07-03 14:20 UTC
