### ISSUE TITLE
folder not creating in android version 12

### ISSUE THREAD

**Issue by codermonk1** [Baseflow/flutter-permission-handler#820] opened 2022-03-25 08:54 UTC
E/flutter (32093): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Creation failed, path = '/storage/emulated/0/abcd' (OS Error: Operation not permitted, errno = 1)

**Comment by mvanbeusekom** [comment] 2022-03-25 10:17
Duplicate of #313

**Closed by mvanbeusekom** 2022-03-25 10:17 UTC

**Comment by RehanAhmedKhan** [comment] 2022-09-13 07:44
use external_path package
https://pub.dev/packages/external_path
