### ISSUE TITLE
Permission.camera always returns the same value

### ISSUE THREAD

**Issue by YourLibHasBugs** [Baseflow/flutter-permission-handler#943] opened 2022-10-20 09:31 UTC
## 🐛 Bug Report

When opens the app for the first time, I need to get current status of camera permissions, for that I use `Permission.camera.status`. It returns `PermissionStatus.denied`, that is fine, it means not determined. After I request permission via `Permission.camera.request()` and it always returns `PermissionStatus.permanentlyDenied`.
If I request permission via another lib, dialog appears, I give consent, but after `Permission.camera.status` still returns `PermissionStatus.denied`. If go to device setting and revoke camera permission, it will still return `PermissionStatus.denied` instead of PermissionStatus.permanentlyDenied`
```
final status = await Permission.camera.status;
        switch (status) {
          case PermissionStatus.granted:
            _cameraScanState = _cameraScanState.copyWith(cameraScanWidgetState: CameraScanWidgetState.unfolded);
            break;
          case PermissionStatus.limited:
            _cameraScanState = _cameraScanState.copyWith(cameraScanWidgetState: CameraScanWidgetState.unfolded);
            break;
          case PermissionStatus.denied:
            final result = await Permission.camera.request();
            // _cameraScanState = _cameraScanState.copyWith(cameraScanWidgetState: CameraScanWidgetState.unfolded);
            break;
          case PermissionStatus.permanentlyDenied:
            _cameraScanState = _cameraScanState.copyWith(needsGoToSettings: true);
            break;
          case PermissionStatus.restricted:
            break;
        }
```

### Expected behavior
`Permission.camera.status` returns `PermissionStatus.denied` if permission is not determined yet.
`Permission.camera.status` returns `PermissionStatus.permanentlyDenied` if user didn't give consent or revoked it in device settings.
`Permission.camera.request()` requests permissions instead of do nothing (if call it for the first time) & return permanentlyDenied

### Configuration

**Version:** 10.1.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment] 2022-10-20 09:43
Hi @YourLibHasBugs, 

Have you enabled the camera permissions in your `Podfile` configuration as mentioned in the iOS section of the README?

**Comment by YourLibHasBugs** [comment] 2022-10-20 11:44
> Hi @YourLibHasBugs,
> 
> Have you enabled the camera permissions in your `Podfile` configuration as mentioned in the iOS section of the README?

Hi, yes

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      if target.name == 'shared_preferences_ios'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited',
          ## dart: PermissionGroup.camera
          'PERMISSION_CAMERA=1'
        ]
      end
    end
    flutter_additional_ios_build_settings(target)
  end
end
```

**Comment by ninoko1995** [comment] 2023-01-11 16:47
same problem.

**Comment by balaji101010** [comment] 2023-08-08 07:08
Same problem here Too

**Comment by mvanbeusekom** [comment] 2023-08-08 07:19
@YourLibHasBugs, apologies for the late reply. I never was able to reproduce the bug. However looking back and more closely to the `Podfile` configuration you supplied I think I notice what is going wrong. The configuration is only set for the target `shared_preferences_ios` as per the if statement in your sample:

```ruby
      if target.name == 'shared_preferences_ios'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          ## dart: PermissionGroup.camera
          'PERMISSION_CAMERA=1'
        ]
      end
```

This would mean that the macros are not applied for the `permission_handler_apple` target and thus the `PERMISSION_CAMERA` permission is still disabled. Best would be to remove the mentioned if statement.

@balaji101010, if you have an issue on Android it is a different issue as this one is specifically targeting iOS which is a different code base and package. Please file an new issue describing your issue in detail.

I am going to close this issue as this seems to be a user configuration mistake and not related to the plugin.

**Closed as completed by mvanbeusekom** 2023-08-08 07:19 UTC
Labels: platform: ios
