### ISSUE TITLE
Permission NEARBY_WIFI_DEVICES

### ISSUE THREAD

**Issue by kostadin24** [Baseflow/flutter-permission-handler#926] opened 2022-09-28 06:20 UTC
Android introduced permission NEARBY_WIFI_DEVICES.
It is less scary than PRECISE_LOCATION and useful for many WiFi related calls.

**Comment by mvanbeusekom** [comment] 2022-09-28 06:43
Duplicate of #859. Work on this is in progress as part of #923.

**Closed by mvanbeusekom** 2022-09-28 06:43 UTC
