### ISSUE TITLE
iOS notification permission incorrectly returned as isPermanetlyDenied

### ISSUE THREAD

**Issue by rgb1380** [Baseflow/flutter-permission-handler#753] opened 2021-12-10 01:04 UTC
## 🐛 Bug Report

Using the latest plug-in (8.3.0), requesting Permission.notification returns status as isPermanentlyDenied whereas the permission is actually granted.

Downgraded to plug-in version 7.2.0 and Permission.isGranted is correctly returned.

Tested on iOS 15.1, physical device

**Comment by mvanbeusekom** [comment] 2021-12-10 08:13
Hi @rgb1380,

That is most likely caused by upgrading to version 8.0.0 without updating the configuration in the `ios/Podfile`. Since version 8.0.0 the permission_handler treats all permissions as disabled by default, instead of having permissions enabled by default as with the prior versions. 

The reason for this change is that each time we introduced new permissions this would result into breaking changes when releasing Apps to the App Store. In these cases Apple would reject the App submission because of missing descriptions in the `Info.plist` file. So by disabling permissions by default this problem doesn't occur and we can more easily introduce new permissions.

This means however that when upgrading to version 8.0.0 or higher it is necessary to change the configuration in the `ios/Podfile` file. Information on how to do this can be found in the [README.md](https://github.com/Baseflow/flutter-permission-handler/blob/634b29bf03faf4431fd4bf535eb03eb0d10a6c53/permission_handler/README.md). 

I will close this issue now, if you keep having issues feel free to leave a comment and I would be happy to re-open the issue.

**Closed by mvanbeusekom** 2021-12-10 08:13 UTC

**Comment by rgb1380** [comment] 2021-12-10 11:25
That was certainly the case. Thanks for the quick response.
