### ISSUE TITLE
Can this resolve

### ISSUE THREAD

**Issue by xiaschina** [Baseflow/flutter-permission-handler#314] opened 2020-06-05 06:13 UTC
![Lark20200605-140915](https://user-images.githubusercontent.com/29702169/83842898-7c145000-a736-11ea-887a-3c2223471f3a.png)

**Comment by Sempakonka** [comment] 2020-12-17 10:55
Hi @xiaschina 
I'm afraid with such little information it is rather difficult to tackle this problem.
Could you provide a minimal reproducible example.
And the output of your `flutter doctor -v` command.

**Comment by Sempakonka** [comment] 2021-01-06 12:00
Closing this ticket due to lack of follow up.
Feel free to re-open when you provide extra information and/or you have any other follow-up related to this issue!

**Closed by Sempakonka** 2021-01-06 12:00 UTC
Labels: status: needs more info
