### ISSUE TITLE
Android location serviceStatus 

### ISSUE THREAD

**Issue by BaroneX** [Baseflow/flutter-permission-handler#624] opened 2021-07-16 09:59 UTC
## 🐛 Bug Report

```
    PermissionWithService locationPermission = Permission.locationWhenInUse;
    var permissionStatus = await locationPermission.status;
    if (permissionStatus == PermissionStatus.denied) {
      permissionStatus = await locationPermission.request();

      if (permissionStatus == PermissionStatus.denied) {
        permissionStatus = await locationPermission.request();
        return false;
      }
    }
    bool isLocationServiceOn = await locationPermission.serviceStatus.isEnabled;
    print(isLocationServiceOn);
```
when i disable and enable the gps , the locationPermission.serviceStatus.isEnabled is always return true

![Lark20210716-175712](https://user-images.githubusercontent.com/6743367/125930031-d66e90b0-4994-444f-8fc7-7c2b85ab4a55.jpg)

<img width="591" alt="WX20210716-175759@2x" src="https://user-images.githubusercontent.com/6743367/125930148-4e3506cb-861e-47b0-beba-d3ee2c32de0d.png">

### Expected behavior
when disable return false
### Configuration

**Version:** 8.1.2

**Platform:** 
- :robot: Android

**Comment by JDDV** [comment] 2021-07-22 14:40
Hi @BaroneX, I tested this issue on different Samsung phones and emulators on different kind of API levels (also API level 28, which is Android 9.0, the same version you tried it on). I tested it by just turning off the GPS as you also show in the image. The results I got are expected behavior; when the GPS is turned off it returns `false`, and when the GPS is turned on it returns `true`.

So I can think of 2 things why your code shows its behavior, maybe you can test those:

1. It could be that GPS only disables GPS, but not location itself, since it can have multiple sources (see image below here).
<img width="354" alt="Schermafbeelding 2021-07-22 om 16 28 07" src="https://user-images.githubusercontent.com/47666699/126656812-4efd1fe9-0e30-4895-a717-4d48f2173030.png">
Can you try to see if you can change the source of location to only GPS and see what it returns then?

2. It can be a problem with Xiaomi phones, we've noticed more issues on Xiaomi phones.

Let me know if you know more!

**Comment by BaroneX** [comment] 2021-08-05 11:10
when i disable the GPS in top setting
<img src="https://user-images.githubusercontent.com/6743367/128339462-9a632020-57cc-471d-9479-e8291c73bff0.png" width="50%">
the location mode has become Battery saving mode
<img src="https://user-images.githubusercontent.com/6743367/128339390-51b8c0a2-ad88-4194-9969-49c98c924c65.jpg" width="50%">
and the ` bool isLocationServiceOn = await locationPermission.serviceStatus.isEnabled;` is always true
finaly i disable the location access the ` bool isLocationServiceOn = await locationPermission.serviceStatus.isEnabled;` it return false;
<img src="https://user-images.githubusercontent.com/6743367/128339398-1e7a260a-b318-4428-84a9-5e47bc6546b4.jpg" width="50%">

**Comment by JDDV** [comment] 2021-08-05 11:42
So the problem was when you disabled GPS in the phones 'quick-menu' the location service is still true, cause it will then use the location hardware like bluetooth, mobile network etc. so the behavior is correct.

Once you have eliminated every location retrieving option (so the location access slider is in the off position) then the service status indeed should be false as how you mention it. This is exactly the expected behavior!

So long story short, `location.serviceStatus` only returns `false` when every option to retrieve location (Bluetooth, WiFi, mobile network, GPS) is turned off by turning off the Location Access slider on your phone. If you only disable GPS (so Bluetooth, WiFi, mobile network is still on) then the `serviceStatus` should return `true` as it did in your case.

Hope it helped you! I will close this issue, feel free to comment if anything isn't still clear!

**Closed by JDDV** 2021-08-05 11:42 UTC
Labels: platform: android, status: waiting for customer response, type: bug
