### ISSUE TITLE
Android SEND_SMS permission only

### ISSUE THREAD

**Issue by pahoel** [Baseflow/flutter-permission-handler#271] opened 2020-04-23 21:00 UTC
## 🚀 Feature Requests

I need a possibility to request only the SEND_SMS permission.
The plugin has only one sms permission handler which request all three permissions: SEND_SMS,
RECEIVE_SMS and READ_SMS.

### Describe the feature
My app's core functionality is to make  Physical safety / emergency alerts. This only requires the SEND_SMS permission. - So when my app ask the user for all three sms permission, it is not accepted by Google Play.

### Platforms affected (mark all that apply)
- [ ] :robot: Android

**Comment by JDDV** [comment] 2021-03-29 11:04
Hi @pahoel I was not able to reproduce the problem, can you provide more information about the issue? do you have an example code, flutter doctor -v, and on what version of Android and which device you used to test it? Thanks in advance!

**Comment by JDDV** [comment] 2022-01-13 14:01
From what I tested the permission SEND_SMS will only be asked (and not all three) if you only have the SEND_SMS in the manifest as shown below.

```
<!-- Permissions options for the `sms` group -->
    <uses-permission android:name="android.permission.SEND_SMS"/>  // YOU ONLY NEED THIS ONE
    <uses-permission android:name="android.permission.RECEIVE_SMS"/>
    <uses-permission android:name="android.permission.READ_SMS"/>
    <uses-permission android:name="android.permission.RECEIVE_WAP_PUSH"/>
    <uses-permission android:name="android.permission.RECEIVE_MMS"/>
```
I hope this answer will help you out so Google Play can accept your app!
I'll close this issue for now, feel free to start a new issue if you still need help with this issue or have any questions.

**Closed by JDDV** 2022-01-13 14:01 UTC
Labels: platform: android, type: enhancement
