### ISSUE TITLE
Notification Permission Denied in Flutter iOS Framework

### ISSUE THREAD

**Issue by danielrsousa** [Baseflow/flutter-permission-handler#1044] opened 2023-05-11 13:52 UTC
**Problem**

Hello everyone,

I'm working on a Flutter project that uses the Permission Handler library. I've built a framework of the project using the command 'flutter build ios-framework --cocoapods --no-profile' and added it to my native iOS app. In the podfile of the app, I've added the following code in the `post_install` section:

```swift
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # You can remove unused permissions here.
      # For more information, please refer to:
      # https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # For example, if you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        ## dart: PermissionGroup.notification
        'PERMISSION_NOTIFICATIONS=1',
      ]
    end
  end
end
```

However, I'm facing an issue where the notification permission request always gets denied. Can someone please suggest a solution to this problem?

**Reproduction Steps**

To reproduce this issue, please follow these steps:

1. Create a Flutter project and add the Permission Handler library.
2. Generate a framework of the project using the command 'flutter build ios-framework --cocoapods --no-profile'.
3. Add the generated framework to your native iOS app.
4. Change the podfile of the app by adding the code mentioned above in the `post_install` section.

Example:
Native iOS App -> MyCustomFramework (Flutter) -> PermissionHandler

**Comment by sezer** [comment] 2023-05-15 11:24
I'm facing the same problem with my old app also including location permission. Do you have any progress on this?

**Comment by mvanbeusekom** [comment] 2023-07-25 07:41
Hi @danielrsousa,

Unfortunately I am not really familiar with embedding the Flutter modules in native iOS applications. However I feel the problem is related to the `GCC_PREPROCESSOR_DEFINITIONS` section. 

The permission_handler relies on the compile-time instructions (`GCC_PREPROCESSOR_DEFINITIONS`) to either include or exclude SDKs that require permission. By default all SDKs are excluded, since you are creating an iOS framework I suspect the Flutter module is already pre-compiled before it is included in the native application.

In this case the issue is probably solved by adding the `post_install` section to the `Podfile` that is part of the Flutter project so that is takes the correct pre-processor definitions into account when running the `flutter build ios-framework --cocoapods --no-profile` command.

Since this is an older issue I will close it for now, however feel free to leave a comment if the suggestion above doesn't help and willing to assist me in further debugging this issue.

**Closed by mvanbeusekom** 2023-07-25 07:41 UTC
