### ISSUE TITLE
returned `permanentlyDenied` when permission is `Ask Every Time` on Android R

### ISSUE THREAD

**Issue by Ralph-Li** [Baseflow/flutter-permission-handler#411] opened 2020-11-05 03:25 UTC
### Expected behavior
for `camera`,  returned `permanentlyDenied` when permission is `Ask Every Time` on Android R
![image](https://user-images.githubusercontent.com/68741321/98194227-d3bf1d80-1f59-11eb-8c00-41824090e938.png)

**Version:** 5.0.1+1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by Ralph-Li** [comment] 2020-11-05 07:06
one problem is "Ask Every Time" is not handled,
another problem is `shouldShowRequestPermissionRationale` return false in this situation.
https://issuetracker.google.com/issues/151427074

**Comment by Ralph-Li** [comment] 2020-11-05 08:07
the example project is failed as expected 
![image](https://user-images.githubusercontent.com/68741321/98214054-f4e73480-1f80-11eb-93d3-4dcea7539242.png)

**Comment by magillus** [comment] 2020-11-25 07:31
This also happened on location permission.

**Comment by Sempakonka** [comment] 2020-12-15 09:44
Hi @Ralph-Li 
Was able to reproduce.
If you would like I think baseflow would love to see a PR coming!

**Comment by AdamJonsson** [comment] 2020-12-27 21:20
The issue only occurs when I go to the settings page and choose "Ask every time". However, when I choose "Only this time" in an in-app permission request, it works as normal. I have only tested this on an Android emulator using Android version 11.

**Comment by tobilarscheid** [comment] 2021-01-22 13:17
Hi everyone, I am seeing the same issue when clicking "Ask everytime" for `Permission.locationInUse`.

**Comment by BasitCh** [comment] 2021-03-17 07:38
Hi! @Ralph-Li did it fix now or not ? i am also facing the same issue. On selection of 'Only this time' it becomes 'Permission.whileInUse' and it does not ask for permission next time ?

**Comment by JDDV** [comment] 2021-03-18 12:53
There has been a never version released as of today (6.1.1) of the permission handler which could possibly fix the issue.
If I understand it correctly, I can reproduce the issue as followed:

On Emulator Android API 30:
Settings > Privacy > Permission Manager > Camera permission set to 'Ask everytime'

In example app:
Click on Permission.camera > should see PermissionStatus.permanentlyDenied

I've tried reproducing the issue with the newest version, but I did not see the same result as mentioned here.
Can you please let us know if the problem still occurs with using the newest version?

**Comment by KSLiquid** [comment] 2021-04-04 13:52
I had the issue as well and for me it disappeared with 6.1.1

**Comment by JDDV** [comment] 2021-05-06 14:07
Closing issue as seems to be solved in the newer version of the permission_handler plugin (^6.1.1)

**Closed by JDDV** 2021-05-06 14:07 UTC
Labels: platform: android, type: bug

**Comment by guilhermeagostinelli** [comment] 2022-08-12 14:01
The issue still persists on 10.0.0.

**Comment by alfie-trbc** [comment] 2025-05-19 07:55
This issue still persists on **12.0.0+1**

There is an open issue regarding this: 
https://github.com/Baseflow/flutter-permission-handler/issues/1206 

**Issue:**  Ask Every time returns permanentlyDenied status. 
**Expectation:** It should return something that distinguish if it is set "Ask every time" not permanentlyDenied.
