### ISSUE TITLE
[Bug]: Permission.requestInstallPackages.request() didn't work at Android11

### ISSUE THREAD

**Issue by Lonely-shang** [Baseflow/flutter-permission-handler#1201] opened 2023-10-23 10:01 UTC
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

1、Install apps
2、Access Page
3、call ```Permission.requestInstallPackages.request()``` to enter the page and open the permissions. The application crashes.

### Expected results

The application don't crashes.

### Actual results

The application crashes.

### Code sample

<details><summary>Code sample</summary>

```dart
The official case I use
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

https://github.com/Baseflow/flutter-permission-handler/assets/34124930/a867caad-8ba6-48e0-be7e-1e5c93089309

</details>

### Version

11.0.1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[✓] Flutter (Channel stable, 3.13.2, on Microsoft Windows [版本 10.0.22621.2428], locale zh-CN)
    • Flutter version 3.13.2 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (9 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at D:\Android\android-sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • ANDROID_HOME = D:\Android\android-sdk
    • Java binary at: D:\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.2)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA 2022.1.4
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9392.3

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA 2023.2
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.10072.19

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (4 available)
    • 21091116AC (mobile) • 4XCMYL5HRSZLF6NR • android-arm64  • Android 11 (API 30)
    • Windows (desktop)   • windows          • windows-x64    • Microsoft Windows [版本 10.0.22621.2428]
    • Chrome (web)        • chrome           • web-javascript • Google Chrome 118.0.5993.89
    • Edge (web)          • edge             • web-javascript • Microsoft Edge 117.0.2045.60

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by mvanbeusekom** [comment] 2023-10-31 07:56
Hi @Lonely-shang,

I have done some testing and debugging and was able to reproduce the error on Android 11 using the emulator. What seems to happen is that Android it selfs closes the application as soon as the user toggles the "Allow from this source" switch  in the Android settings page. 

I have tried running with debuggers attached and verbose logging but it doesn't show any activity the app is simply killed immediately when the "Allow from this source" switch is toggled, without any message or log. Note that at the moment the "Install unknown apps" page is displayed our app it in the background and is not active, so at that point in time we are not running any code. 

It really seems this is a bug in the Android OS and fixed in later versions as the problem doesn't occur in Android 12 or later. The same behaviour is also discussed in this article: https://www.androidpolice.com/2020/08/24/android-11-install-unknown-apps-more-cumbersome/

I am going ahead and close this issue as this seems intended behaviour on Android 11 (or at least it is outside of our control). Feel free to leave a comment with additional information if you think this is incorrect.

**Closed by mvanbeusekom** 2023-10-31 07:56 UTC
Labels: platform: android, P2

**Comment by Lonely-shang** [comment] 2023-11-01 00:02
> Hi @Lonely-shang,
> 
> I have done some testing and debugging and was able to reproduce the error on Android 11 using the emulator. What seems to happen is that Android it selfs closes the application as soon as the user toggles the "Allow from this source" switch  in the Android settings page. 
> 
> I have tried running with debuggers attached and verbose logging but it doesn't show any activity the app is simply killed immediately when the "Allow from this source" switch is toggled, without any message or log. Note that at the moment the "Install unknown apps" page is displayed our app it in the background and is not active, so at that point in time we are not running any code. 
> 
> It really seems this is a bug in the Android OS and fixed in later versions as the problem doesn't occur in Android 12 or later. The same behaviour is also discussed in this article: https://www.androidpolice.com/2020/08/24/android-11-install-unknown-apps-more-cumbersome/
> 
> I am going ahead and close this issue as this seems intended behaviour on Android 11 (or at least it is outside of our control). Feel free to leave a comment with additional information if you think this is incorrect.

Ok, thank you for your reply. I will also keep an eye on it later.
