### ISSUE TITLE
[Question]:  expect work finewith flutter_blue plugin in Xcode 15 as in Xcode 14

### ISSUE THREAD

**Issue by Yongle-Fu** [Baseflow/flutter-permission-handler#1171] opened 2023-09-27 11:18 UTC
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Windows

### Your question

https://github.com/boskokg/flutter_blue_plus/issues/581

### Version

11.0.0

```yaml
flutter_blue: ^0.8.0
```
cannot work fine with Xcode 15

**Comment by chipweinberger** [comment] 2023-09-27 17:36
You are using `flutter_blue`? i.e. `flutter_blue: ^0.8.0`

I thought you were using `flutter_blue_plus`? i.e. `flutter_blue_plus: ^1.15.8`

**Comment by Yongle-Fu** [comment] 2023-09-28 01:29
> You are using `flutter_blue`? i.e. `flutter_blue: ^0.8.0`
> 
> I thought you were using `flutter_blue_plus`? i.e. `flutter_blue_plus: ^1.15.8`

yes, we fork flutter_blue repo and make some customed changes such as windows support, a2dp info before flutter_blue_plus publish, so i try fix this or plan mirgate to flutter_blue_plus

**Comment by JeroenWeener** [comment] 2023-09-28 07:53
Hi @Yongle-Fu, thank you for reaching out.

Could you elaborate on your issue? Are you saying combining `flutter_blue` and `permission_handler` is causing issues for you on Xcode 15, but not on Xcode 14? What exact issue are you experiencing? You could provide us with a minimal reproducible code sample, and an error stack trace?

**Comment by Yongle-Fu** [comment] 2023-09-28 08:31
> ### Please check the following before submitting a new issue.
> * [x]  I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
>         
>       
>   
>       Create an issue with the title I have searched the existing issues.. Press Enter to convert to an issue instantly. Press Option-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [x]  I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).
>         
>       
>   
>       Create an issue with the title I have carefully read the documentation.. Press Enter to convert to an issue instantly. Press Option-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> 
> ### Please select for which platform(s) you need help
> * [ ]  Android
>         
>       
>   
>       Create an issue with the title Android. Press Enter to convert to an issue instantly. Press Option-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [x]  iOS
>         
>       
>   
>       Create an issue with the title iOS. Press Enter to convert to an issue instantly. Press Option-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [ ]  Windows
>         
>       
>   
>       Create an issue with the title Windows. Press Enter to convert to an issue instantly. Press Option-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> 
> ### Your question
> [boskokg/flutter_blue_plus#581](https://github.com/boskokg/flutter_blue_plus/issues/581)
> 
> ### Version
> 11.0.0
> 
> ```yaml
> flutter_blue: ^0.8.0
> ```
> 
> cannot work fine with Xcode 15

yes, reproducible code sample just only add ```flutter_blue: ^0.8.0``` to permission_handler_example/pubspec.yaml

**Comment by Yongle-Fu** [comment] 2023-09-28 08:31
> Hi @Yongle-Fu, thank you for reaching out.
> 
> Could you elaborate on your issue? Are you saying combining `flutter_blue` and `permission_handler` is causing issues for you on Xcode 15, but not on Xcode 14? What exact issue are you experiencing? You could provide us with a minimal reproducible code sample, and an error stack trace?

yes, reproducible code sample just only add flutter_blue: ^0.8.0 to permission_handler_example/pubspec.yaml

**Comment by TimHoogstrate** [comment] 2023-09-28 09:19
I can reproduce this... 

Xcode 15
sim iPhone 15
real device running iOS 16.6

permission handler alone, no problem. flutter_blue no problem. Combining them: 

On simulator:

dyld[59765]: Symbol not found: _OBJC_CLASS_$_FlutterError
  Referenced from: <C069CB7F-86A6-3DC4-B6FD-AF2058755E59> /Users/XXX/Library/Developer/CoreSimulator/Devices/0292A339-C606-4773-B1A7-4EDCA8D77E6C/data/Containers/Bundle/Application/4F257E7D-8B81-4F4B-8104-CD222DF1395A/Runner.app/Runner
  Expected in:     <8E3AFB4C-C62A-3419-A114-A43BABF37D18> /Users/XXX/Library/Developer/CoreSimulator/Devices/0292A339-C606-4773-B1A7-4EDCA8D77E6C/data/Containers/Bundle/Application/4F257E7D-8B81-4F4B-8104-CD222DF1395A/Runner.app/Frameworks/flutter_blue.framework/flutter_blue

On real device: 

dyld[8723]: Symbol not found: _OBJC_CLASS_$_FlutterError
  Referenced from: <352FFBF2-7F6A-3B2D-BB33-0F2108FBC331> /private/var/containers/Bundle/Application/B877FE91-A7A2-4A91-9998-EEC5DFF53715/Runner.app/Runner
  Expected in:     <DF21BABF-8BFE-3C3C-B7D8-AD1B78C1E605> /private/var/containers/Bundle/Application/B877FE91-A7A2-4A91-9998-EEC5DFF53715/Runner.app/Frameworks/flutter_blue.framework/flutter_blue,

I am not sure if this has something to do with the permission-handler.

**Comment by TimHoogstrate** [comment] 2023-09-29 10:07
Dear @Yongle-Fu,

It looks like the flutter_blue repository han't been updated for a long time. Furthermore, it looks like you have added additional functionality in your own fork. After trying the same setup with flutter_blue_plus it seems to work fine. It is out of the scope of our team to advise on these plugins. Therefore, we cannot help you for now and I'll close this issue.

Kind regards,

**Closed by TimHoogstrate** 2023-09-29 10:07 UTC
Labels: platform: ios, type: bug, P2

**Comment by Yongle-Fu** [comment] 2023-10-07 01:23
Although I don’t know the specific reason why they cannot work properly on Xcode15 when used together, by comparing flutter_blue_plus and modifying the following code, the problem was solved.

```
+  s.dependency 'SwiftProtobuf', '~> 1.0' 

-  s.subspec "Protos" do |ss|
-    ss.source_files = "gen/*.pbobjc.{h,m}", "gen/**/*.pbobjc.{h,m}"
-    ss.header_mappings_dir = "gen"
-    ss.requires_arc = false
-    ss.dependency "Protobuf", '=3.14.0'
-  end
```

**Comment by Yongle-Fu** [comment] 2023-10-07 01:45
Additional reply, specific reasons have been pointed out [](https://github.com/boskokg/flutter_blue_plus/issues/581#issuecomment-1744635737)
