### ISSUE TITLE
[10.2.0]Does not work at all for ios

### ISSUE THREAD

**Issue by ninoko1995** [Baseflow/flutter-permission-handler#976] opened 2023-01-11 16:32 UTC
## 🐛 Bug Report

My app is able to access to microphone and camera.
But this module cannot detect it and always returns the same value, `PermissionStatus.denied`.

<img width=300 src='https://user-images.githubusercontent.com/18717088/211862247-08ab36ec-e329-4940-97d7-7bb7828d8da3.jpg'>

```
final microphoneStatus = await Permission.microphone.status;
print('microphoneStatus: $microphoneStatus');
final cameraStatus = await Permission.camera.status;
print('cameraStatus: $cameraStatus');
```

```
flutter: microphoneStatus: PermissionStatus.denied
flutter: cameraStatus: PermissionStatus.denied
```

podfile
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'

      ## dart: PermissionGroup.camera
      'PERMISSION_CAMERA=1'
      ## dart: PermissionGroup.microphone
      'PERMISSION_MICROPHONE=1'
    end
  end
end
```

### Configuration

**Version:** 10.2.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by fullflash** [comment] 2023-01-12 21:10
same here IOS 16.2

**Comment by abdalmonem** [comment] 2023-02-04 08:36
same also on IOS 16.2

**Comment by tajaouart** [comment] 2023-02-07 15:02
Have the same issue.

**Comment by lanrehnics** [comment] 2023-02-10 00:26
Any update on this ??

**Comment by spkersten** [comment] 2023-02-10 14:09
Looks like some stuff is missing in your podfile. The defines need to be added to `GCC_PREPROCESSOR_DEFINITIONS`. For example:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      ...

      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: [PermissionGroup.camera]
        ## Info.plist: [NSCameraUsageDescription]
        'PERMISSION_CAMERA=1',
      ]
    end
  end
end
```

**Comment by BillyWithFlutter** [comment] 2023-07-10 07:31
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|

      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=1',

      ]    

    end
  end
end
```


did this and I got a white blank screen. when I comment it. it show the actual app

**Comment by mvanbeusekom** [comment] 2023-07-12 10:32
Did some testing using the [example](https://github.com/Baseflow/flutter-permission-handler/tree/main/permission_handler/example) app and everything seems to work fine.

This result can indeed happen when the permissions are not (correctly) enabled in the `ios/Podfile` (as mentioned by @spkersten and documented in the iOS section of the [README](https://pub.dev/packages/permission_handler)). Have a look at the configuration of the [Podfile](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/example/ios/Podfile) of the [example](https://github.com/Baseflow/flutter-permission-handler/tree/main/permission_handler/example) application as a working configuration.

For us to be able to help debug this problem, please create a sample application reproducing the problem and share it here. I will mark this issue with the `status: needs more info` label, which will close this issue in 14 days unless the requested additional information is supplied.

Here is some additional information of my environment:

- Device: iPhone 12 mini (real device)
- iOS version: 16.5.1
- Flutter doctor output:
```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-NL)
    • Flutter version 3.10.5 on channel stable at /Users/maurits/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/maurits/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • Maurits van Beusekom’s iPhone (mobile) • 00008101-000D543E1A40001E • ios            • iOS 16.5.1 20F75
    • macOS (desktop)                        • macos                     • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)                           • chrome                    • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Closed** 2023-07-26 11:08 UTC
Labels: platform: ios, status: needs more info, type: bug, status: closed (missing info), P1

**Comment by KrishnaDhaduk007** [comment] 2024-05-20 10:36
ji
