### ISSUE TITLE
Requesting activity recognition permission doesn't prompt for any permission in iOS devices.

### ISSUE THREAD

**Issue by bikcrum** [Baseflow/flutter-permission-handler#379] opened 2020-09-02 06:23 UTC
## 🐛 Bug Report

Requesting activity recognition permission doesn't prompt for any permission in iOS devices.

### Expected behavior

Like in Android devices, iOS devices should have asked for activity recognition permission with a dialog. Permission status is always undetermined when requesting.

### Reproduction steps

```
var status = await Permission.activityRecognition.request();
// check value of status. It's always coming PermissionStatus.undetermined.
// No prompt in iOS device
// Only works with Android device
```

### Configuration

**pubspec.lock**
```
...
 permission_handler:
    dependency: "direct main"
    description:
      name: permission_handler
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.0.1+1"
  permission_handler_platform_interface:
    dependency: transitive
    description:
      name: permission_handler_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
...
```

**Platform:** 
- Device model: iPhone 6, iOS 12.4.8

**Comment by sajunt4** [comment] 2020-09-05 22:55
Same error here, under the same conditions.

**Comment by PavelClaudiuStefan** [comment] 2020-11-02 13:13
Same issue here

**Comment by Sempakonka** [comment] 2020-12-18 11:41
Hi,
It seems like this has yet to be implemented for iOS.
Since someone has already opened a proposal [here](https://github.com/Baseflow/flutter-permission-handler/issues/430) I am going to close this issue.

**Comment by bikcrum** [comment] 2020-12-18 11:46
> Hi,
> It seems like this has yet to be implemented for iOS.
> Since someone has already opened a proposal [here](https://github.com/Baseflow/flutter-permission-handler/issues/430) I am going to close this issue.

You should not have closed this issue as this issue is created earlier than #430. Furthermore, this issue is following proper guidelines for reporting issues such as reproduction steps.

**Comment by Sempakonka** [comment] 2020-12-18 14:41
Agreed. 
My motivation to close this issue was because of the fact that this issue is not a bug but rather a feature request. Information about this not working on iOS is documented.
```
  /// When running on Android Q and above: Activity Recognition
  /// When running on Android < Q: Nothing
  /// iOS: Nothing
```
But I agree with your reasoning to reopen this case!
thanks for clarifying

**Comment by bikcrum** [comment] 2021-04-09 09:05
I am using ` Permission.sensors` instead of `Permission.activityRecognition` for iOS and it works fine.

**Comment by JDDV** [comment] 2021-05-17 09:25
Hi @bikcrum, as mentioned before the `activityRecognition` permission is for Android only, the `sensors` permission is indeed the iOS equivalent of the `activityRecognition`. more information about the `sensors` permission on iOS can be found [here](https://developer.apple.com/documentation/coremotion). I will close this issue now, if you still have questions please let us know!

**Closed by JDDV** 2021-05-17 09:25 UTC
Labels: platform: ios, type: enhancement
