### ISSUE TITLE
REQUEST_INSTALL_PACKAGES!!

### ISSUE THREAD

**Issue by minhnguyenandpad** [Baseflow/flutter-permission-handler#871] opened 2022-07-13 04:07 UTC
## 🐛 Bug Report

Please remove this permission request. Although i don't use it, PlayStore still detect and reject all the apps that have been pushed.

**Comment by mvanbeusekom** [comment] 2022-07-14 14:59
Duplicate of #869

**Closed by mvanbeusekom** 2022-07-14 14:59 UTC
