### ISSUE TITLE
Always getting PermissionStatus.undetermined status for camera.

### ISSUE THREAD

**Issue by DhavalRKansara** [Baseflow/flutter-permission-handler#338] opened 2020-06-26 12:51 UTC
I am getting `PermissionStatus.undetermined` status for the camera while I am asking permission for the first time. After that, I have denied permission to never ask again checkbox in android, and still next time I Got the same `PermissionStatus.undetermined ` on behalf of `PermissionStatus.permanentlyDenied`.

- Even when the first time I simply deny the Camera permission still I am getting the same permission status as `PermissionStatus.undetermined `.

Code:

```
  Future _scan() async {
    var cameraPermissionStatus = await Permission.camera.status;
    if (cameraPermissionStatus == PermissionStatus.granted) {
      try {
        String barcode = await BarcodeScanner.scan();
        if (barcode.isNotEmpty && barcode != null) {
          printLog("Value of Barcode is $barcode");
          _facilityDashboardBloc.add(ScanQRCode(barcode));
        }
      } on PlatformException catch (e) {
        if (e.code == BarcodeScanner.CameraAccessDenied) {
          _opneSetting();
        } else {
          printLog("Unknown error: $e");
        }
      } on FormatException {
        printLog(
            'null (User returned using the "back"-button before scanning anything. Result)');
      } catch (e) {
        printLog('Unknown error: $e');
      }
    } else if (cameraPermissionStatus == PermissionStatus.undetermined) {
      Permission.camera.request();
    } else if (cameraPermissionStatus == PermissionStatus.denied ||
        cameraPermissionStatus == PermissionStatus.permanentlyDenied ||
        cameraPermissionStatus == PermissionStatus.restricted) {
      _opneSetting();
    }
  }
```

**Comment by DhavalRKansara** [comment] 2020-07-01 13:35
@martijn00 @orzech85 Can you please help me out with this issue?

**Comment by mvanbeusekom** [comment] 2020-07-01 14:16
duplicate of 336

**Closed by mvanbeusekom** 2020-07-01 14:16 UTC
Labels: type: duplicate

**Comment by xuzhaokai** [comment] 2020-11-19 08:03
> @martijn00 @orzech85 Can you please help me out with this issue?

You can test this : await Permission.camera.request().isDenied
