### ISSUE TITLE
Check if the permission dialog is already open

### ISSUE THREAD

**Issue by hugocbpassos** [Baseflow/flutter-permission-handler#107] opened 2019-05-14 22:43 UTC
I have this situation in which there's a button that calls `requestPermissions` on press. If the user is fast enough, he/she can tap the button while the permission dialog stills visible, resulting in a `PlatformException`.  We should be able to check whether the dialog is already open. A simple `bool` like `PermissionHandler().isRequestingPermission` would be perfect.

**Comment by ened** [comment] 2019-05-16 16:11
Fixed in #109.

**Comment by hugocbpassos** [comment] 2019-05-16 21:16
I still have the issue even with this change.

**Comment by danielroek** [comment] 2020-09-09 13:46
Unable to reproduce the issue on iOS or Android. Closing this issue

**Closed by danielroek** 2020-09-09 13:46 UTC
