### ISSUE TITLE
[Reply already submitted] java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by mayur1433** [Baseflow/flutter-permission-handler#539] opened 2021-04-29 11:37 UTC
After the add, this Permission manage external storage I got the below error any can help me?
![Screenshot 2021-04-29 at 5 07 17 PM](https://user-images.githubusercontent.com/22167190/116544919-5c1cea80-a90d-11eb-9253-18f7490f49ab.png)

[        ] E/AndroidRuntime( 9539): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=210, result=0,
data=null} to activity {com.rbeat/io.flutter.embedding.android.FlutterActivity}: java.lang.IllegalStateException: Reply already submitted
[        ] E/AndroidRuntime( 9539):     at android.app.ActivityThread.deliverResults(ActivityThread.java:5213)
[        ] E/AndroidRuntime( 9539):     at android.app.ActivityThread.handleSendResult(ActivityThread.java:5254)
[        ] E/AndroidRuntime( 9539):     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
[        ] E/AndroidRuntime( 9539):     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[        ] E/AndroidRuntime( 9539):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[        ] E/AndroidRuntime( 9539):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
[        ] E/AndroidRuntime( 9539):     at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime( 9539):     at android.os.Looper.loop(Looper.java:233)
[        ] E/AndroidRuntime( 9539):     at android.app.ActivityThread.main(ActivityThread.java:8010)
[        ] E/AndroidRuntime( 9539):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime( 9539):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
[        ] E/AndroidRuntime( 9539):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
[        ] E/AndroidRuntime( 9539): Caused by: java.lang.IllegalStateException: Reply already submitted
[        ] E/AndroidRuntime( 9539):     at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
[        ] E/AndroidRuntime( 9539):     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
[        ] E/AndroidRuntime( 9539):     at com.baseflow.permissionhandler.-$$Lambda$fOfJ7OpNBkhP48Mtzqs01exhUJs.onSuccess(Unknown Source:2)
[        ] E/AndroidRuntime( 9539):     at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:64)
[        ] E/AndroidRuntime( 9539):     at
io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistr
y.java:739)
[        ] E/AndroidRuntime( 9539):     at
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
[        ] E/AndroidRuntime( 9539):     at
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:677)
[        ] E/AndroidRuntime( 9539):     at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:616)
[        ] E/AndroidRuntime( 9539):     at android.app.Activity.dispatchActivityResult(Activity.java:8316)
[        ] E/AndroidRuntime( 9539):     at android.app.ActivityThread.deliverResults(ActivityThread.java:5206)
[        ] E/AndroidRuntime( 9539):     ... 11 more
[  +27 ms] I/Process ( 9539): Sending signal. PID: 9539 SIG: 9

**Comment by mvanbeusekom** [comment] 2021-04-30 06:06
@mayur1433 it would be great if you could provide some additional information:

1. Could you list the other plugins/ dependencies that you are using in your app? This seems closely related to an earlier issue we experienced, where two plugins use the same `requestCode` when starting an intent and both would then try to handle the result, resulting in multiple calls to the result object;
2. The output of the `flutter doctor -v` command;
3. The version of the permission_handler plugin you are using.

**Comment by mayur1433** [comment] 2021-04-30 11:14
1. Could you list the other plugins/ dependencies that you are using in your app? This seems closely related to an earlier issue we experienced, where two plugins use the same requestCode when starting an intent and both would then try to handle the result, resulting in multiple calls to the result object;

ANS: Yes

2. The output of the flutter doctor -v command;

[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 2.0.5 at /Volumes/DATA/Sdk/flutter
    • Framework revision adc687823a (2 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mayur/Library/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mayur/Library/Android/Sdk
    • ANDROID_SDK_ROOT = /Users/mayur/Library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0
    
3. The version of the permission_handler plugin you are using.

ANS: permission_handler: ^7.0.0

**Comment by sn1cka** [comment] 2021-06-17 10:52
I have same issue. 
Im getting it when trying to request Permission.ignoreBatteryOptimizations in List<Permission>.request();

Here's the code when im getting this exception.

`var mList = [Permission.microphone, Permission.notification, Permission.storage, Permission.ignoreBatteryOptimizations];
    mList.request();`



Here is my pubspec.yaml:

`name: mega_recorder
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^8.1.4
  permission_handler: ^8.1.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  equatable: ^2.0.3
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  path_provider: ^2.0.2
  flutter_background: ^1.0.1
  awesome_notifications: ^0.0.6+9
  intl: ^0.17.0
  move_to_background: ^1.0.2
  auto_route: ^2.2.0
  flutter_foreground_plugin: ^0.8.0
  socket_io_client: ^1.0.1
  json_annotation: ^4.0.1
  dio: ^4.0.0

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  json_serializable: ^4.1.3
  build_runner: ^2.0.4
  disk_space: ^0.1.1

flutter:

  uses-material-design: true

`

**Comment by EinatK** [comment] 2021-11-01 06:35
Same issue here, i see the crash in crashlytics, haven't reproduced it locally. I suspect it's either storage or camera permissions. 

the error is ```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.mobitti.hadassah/com.mobitti.mobitti_flutter_app.MainActivity}: java.lang.IllegalStateException: Reply already submitted
```

my other dependencies :

```
dependencies:
  async: ^2.5.0
  barcode_scan2: ^4.1.4
  cached_network_image: ^3.0.0
  carousel_slider: ^2.3.1
  connectivity_plus: ^2.0.2
  device_calendar: ^3.1.0
  device_info: ^2.0.0
  f_logs: ^2.0.0
  file_picker: ^3.0.3
  firebase_analytics: ^8.2.0
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  firebase_crashlytics: ^2.1.1
  firebase_messaging: ^10.0.8
  flip_card: ^0.5.0
  flutter:
    sdk: flutter
  flutter_absolute_path: ^1.0.6
  flutter_calendar_carousel: ^2.0.1
  flutter_email_sender: ^5.0.2
  flutter_fgbg: ^0.1.0
  flutter_local_notifications: ^8.1.0
  flutter_localizations:
    sdk: flutter
  flutter_microsoft_authentication:
    git:
      url: https://github.com/einatguri/flutter-microsoft-authentication.git
      ref: ca47774fff4dc4711682f4e1292366b660e6f101
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_week_view:
    git:
      url: https://github.com/einatguri/FlutterWeekView.git
      ref: master
  flutter_zoom_drawer: ^2.1.1
  fluttertoast: ^8.0.6
  geolocator: ^7.7.1
  get_it: ^5.0.3
  google_fonts: ^2.0.0
  google_maps_flutter: ^2.0.6
  google_sign_in: ^5.1.1
  html: ^0.15.0
  http: ^0.13.1
  image_picker: ^0.8.1+3
  intl: ^0.17.0
  local_auth: ^1.1.5
  map_launcher: ^2.1.1
  marquee: ^2.1.0
  mobitti_webview:
    path: ../mobitti_webview
  network_info_plus: ^2.0.2
  network_to_file_image: ^2.3.8
  otp_text_field: ^1.1.1
  package_info: ^0.4.3+2
  path_provider: ^2.0.1
  permission_handler: ^8.2.5
  provider: ^6.0.1
  rxdart: ^0.26.0
  sembast: ^3.1.1
  shared_preferences: ^2.0.5
  sliding_up_panel: ^2.0.0+1
  ssh: ^0.0.7
  toggle_switch: ^1.2.0
  transparent_image: ^1.0.0
  uuid: ^3.0.4
  webview_flutter: ^2.0.10
  xml: ^5.0.2
  xml2json: ^5.2.0
```

**Comment by xiejinpeng007** [comment] 2021-12-16 03:16
I have same issue , app crash in some devices , and I can't reproduce.
The only thing I did is request the camera permission.

```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3

  # Internationalization
  flutter_localizations:
    sdk: flutter

  # GetX
  get: ^4.1.4

  # Http Client
  dio: 4.0.4
  dio_cookie_manager: 2.0.0

  # Data persistence
  sqflite: ^2.0.0+3
  shared_preferences: ^2.0.6

  # Tools
  url_launcher: ^6.0.7
  intl: ^0.17.0
  path: ^1.8.0
  path_provider: ^2.0.1
  dartz: ^0.10.0-nullsafety.2
  rxdart: ^0.27.0
  equatable: ^2.0.0
  permission_handler: 8.1.6
  device_info: ^2.0.0
  share_plus: ^2.1.2
  package_info_plus: ^1.0.3
  connectivity_plus: ^1.0.5
  ntp: ^2.0.0
#  android_intent_plus: ^1.0.2
  # Widget
  webview_flutter: ^2.0.4
  flutter_inappwebview: ^5.3.2
  fluttertoast: ^8.0.7
  retry: ^3.1.0

  firebase_core: ^1.7.0
  firebase_crashlytics: ^2.2.3
  firebase_remote_config: ^0.11.0
  adjust_sdk: ^4.29.1
  system_proxy:
    git: https://github.com/fenrir-cd/flutter_system_proxy.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.0.16
  build_runner: ^2.1.2
```

**Comment by au-top** [comment] 2022-02-22 03:26
+1 

i call code `await ListenCall.requestPhonePermission`

`java.lang.IllegalStateException: Reply already submitted`

**Comment by EinatK** [comment] 2022-03-23 11:19
Any news on this ?

**Comment by jeromeDms** [comment] 2022-04-14 07:48
Same issue.
I'm using contacts and location permissions.
Multiple crashes reported by firebase

**Comment by luttmfra** [comment] 2022-06-08 22:11
Same issue. location permission.

**Comment by sunqihui222** [comment] 2022-07-09 07:31
Same issue. manageExternalStorage permission.

**Comment by sanekyy** [comment] 2022-10-25 14:58
Hi @mvanbeusekom!

I faced with same error in our app. Tracked by Firebase Crashlytics.

`permission_handler` version is `9.0.2`
`permission_handler_platform_interface` version is `3.7.0` 

Errors only with `ResultInfo.request` 209 or 211

Here is actual stack trace:

<details>

```
Fatal Exception: java.lang.RuntimeException
Failure delivering result ResultInfo{who=null, request=209, result=0, data=null} to activity {xxx.xxx.xxx.MainActivity}: java.lang.IllegalStateException: Reply already submitted
```

```
io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:430)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success (MethodChannel.java:267)
com.baseflow.permissionhandler.-$$Lambda$fOfJ7OpNBkhP48Mtzqs01exhUJs.onSuccess (-.java:2)
com.baseflow.permissionhandler.PermissionManager.onActivityResult (PermissionManager.java:100)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult (FlutterEngineConnectionRegistry.java:805)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult (FlutterEngineConnectionRegistry.java:428)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult (FlutterActivityAndFragmentDelegate.java:807)
io.flutter.embedding.android.FlutterActivity.onActivityResult (FlutterActivity.java:724)
android.app.Activity.dispatchActivityResult (Activity.java:8659)
android.app.ActivityThread.deliverResults (ActivityThread.java:5939)
android.app.ActivityThread.handleSendResult (ActivityThread.java:5985)
android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:54)
android.app.servertransaction.ActivityTransactionItem.execute (ActivityTransactionItem.java:45)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2443)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:226)
android.os.Looper.loop (Looper.java:313)
android.app.ActivityThread.main (ActivityThread.java:8751)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)
```

</details>

**Comment by deckerst** [comment] 2022-11-09 13:13
I can't reproduce myself but I saw a crash report with:
- permission_handler: 10.1.0
- permission_handler_android: 9.0.2+1
- permission_handler_platform_interface: 3.9.0
- flutter: 3.3.4
- device: OPPO A53
- Android 10

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {deckers.thibault.aves/deckers.thibault.aves.MainActivity}: java.lang.IllegalStateException: Reply already submitted
```
Note `ResultInfo.request` is 24. Rest of the stack is the same as others above.

**Comment by windows7lake** [comment] 2022-11-09 13:14
邮件已收到，谢谢！

**Comment by sanekyy** [comment] 2022-12-02 10:31
Hi @mvanbeusekom!

This error still reproducing in production.

I added throttle to `request permission button` and this error reproducing with throttle too (3 seconds between clicks).

This error crash entire app, so can you please somehow help with resolving this error.

**Comment by liu731** [comment] 2023-01-31 06:33
+1

**Comment by liu731** [comment] 2023-01-31 06:35
+1
Unable to reproduce, `request=24`. Rest of the stack is the same as others above.

permission_handler: 9.2.0

**Comment by huang1592847** [comment] 2023-06-07 09:23
await [
      Permission.storage,
    ].request();
await [
      Permission.manageExternalStorage,
    ].request();
申请权限分开请求，不要写在一起

**Comment by Passer-by** [comment] 2023-08-14 02:56
Same issue.

**Comment by Shik1266** [comment] 2023-08-22 04:22
any news update?

**Comment by TimHoogstrate** [comment] 2023-08-24 11:45
Is anyone able to reproduce this issue with clear steps?

**Closed** 2023-09-07 08:34 UTC
Labels: platform: android, type: bug, P2
