### ISSUE TITLE
Permission Handler Errors (5.1.0+2)

### ISSUE THREAD

**Issue by windowmirror** [Baseflow/flutter-permission-handler#454] opened 2021-02-19 13:20 UTC
I am getting an unterminated conditional directive which I think also part of an error with known class method for selector and and incompatible pointer to integer conversion - using permission_handler-5.1.0+2

Thoughts? 

<img width="754" alt="Permission_Handler Error" src="https://user-images.githubusercontent.com/34893202/108509409-ce74ad00-7282-11eb-873d-21c4ff341787.png">

**Comment by Fedaldo** [comment] 2021-02-22 15:44
I'm having the same error

**Comment by RalphMarvin** [comment] 2021-03-04 11:43
> I'm having the same error

Am facing the same issue as well

**Comment by mvanbeusekom** [comment] 2021-03-06 21:34
You receive this error if you are compiling with a pre-Xcode 12 version (note that Flutter will use Xcode build tools under the covers). 

Version 5.1.0+2 contains a new permission (Photo Only Acces) which is added to the iOS version 14 and requires Xcode 12 or higher. This means you have two choices:

1. Upgrade to Xcode 12.x which supports iOS 12 and up;
2. Pin the dependency to permission_handler 5.0.1+2 (play close attention to the version number because it looks almost the same as the latest version which is 5.1.0+1).

Will be closing this issue as this is expected behaviour.

**Closed by mvanbeusekom** 2021-03-06 21:34 UTC
