### ISSUE TITLE
 Android： Enter the front desk, black screen

### ISSUE THREAD

**Issue by paintingStyle** [Baseflow/flutter-permission-handler#756] opened 2021-12-13 05:36 UTC
## 🐛

####After the permission request pop-up box pops up, switch the application to the background, and then switch back to the foreground. The application displays black

I don't know whether this official error or this library problem

<img width="415" alt="image" src="https://user-images.githubusercontent.com/22866404/145757912-57b884f3-312f-4be8-9a6d-313272a00b38.png">

**Version：** 8.3.0

**Platform：**
- Android

**Comment by JDDV** [comment] 2021-12-16 09:55
Hi @paintingStyle, I tested it using other packages tht request permissions as well. The same behavior happened when the permission request dialog was app and I switched to application to the background and opened it up again. It seems like it's behavior that's caused by using Flutter. There is a issue on the Flutter GitHub page where a lot of people have the same problem, you can read it here: link to [GitHub Issue](https://github.com/flutter/flutter/issues/58002).

I'll close the issue for now, since it's not a permission_handler error/bug. Let me know if this didn't answer your question though!

**Closed by JDDV** 2021-12-16 09:55 UTC
