### ISSUE TITLE
Add support for XCode 13

### ISSUE THREAD

**Issue by knightowlRaising** [Baseflow/flutter-permission-handler#672] opened 2021-09-22 22:11 UTC
Getting this while trying to run on XCode 13

'UIUserNotificationType' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNAuthorizationOptions [-Wdeprecated-declarations]
          UIUserNotificationType notificationTypes = 0;

**Comment by saileshbro** [comment] 2021-09-28 01:57
@knightowlRaising Add this in your `Podfile` for a temporary fix
```Podfile
    if ['permission_handler'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5'
      end
    end
```
Somewhere here
![image](https://user-images.githubusercontent.com/43571990/135009769-20bea358-4b51-4e19-aceb-ea68986717d5.png)

**Comment by JDDV** [comment] 2021-09-30 07:54
Hi @knightowlRaising, I tried to reproduce the issue that you're facing but I don't get that error message when I try to run my project. I looked into the documentation of `UIUserNotificationType` and it indeed is deprecated, `UNUserNotificationCenter` should be used for newer versions.

I looked into the code of the `permission_handler` and already saw that this was implemented with an `if-else` check, handling the permission the right way for the right iOS version.

I would like to get some more information to find out why you get this message. Can you run/compile the code, or does the error block you from doing that?

I would also be helpful to see a `flutter doctor -v` output, the version of the `permission_handler` you're using, and the version of iOS you're testing it on.

Thanks in advance!

**Comment by saileshbro** [comment] 2021-10-05 09:51
@JDDV looks like this is fixed with the latest update.

**Closed** 2021-10-14 08:08 UTC
Labels: platform: ios, status: needs more info, status: waiting for customer response
