### ISSUE TITLE
[Bug]: A request for permissions is already running, please wait for it to finish before doing another request

### ISSUE THREAD

**Issue by MR-MaoJiu** [Baseflow/flutter-permission-handler#1276] opened 2024-02-05 11:35 UTC
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

 Map<Permission, PermissionStatus> statuses = await [
      Permission.storage,
      Permission.camera,
      Permission.microphone,
      Permission.manageExternalStorage,
    ].request();
    if (statuses[Permission.storage] == PermissionStatus.granted &&
        statuses[Permission.camera] == PermissionStatus.granted &&
        statuses[Permission.microphone] == PermissionStatus.granted &&
        statuses[Permission.manageExternalStorage] ==
            PermissionStatus.granted) {
      setState(() {
        havePermission = true;
      });
    }

### Expected results

 Map<Permission, PermissionStatus> statuses = await [
      Permission.storage,
      Permission.camera,
      Permission.microphone,
      Permission.manageExternalStorage,
    ].request();
    if (statuses[Permission.storage] == PermissionStatus.granted &&
        statuses[Permission.camera] == PermissionStatus.granted &&
        statuses[Permission.microphone] == PermissionStatus.granted &&
        statuses[Permission.manageExternalStorage] ==
            PermissionStatus.granted) {
      setState(() {
        havePermission = true;
      });
    }

### Actual results

 Map<Permission, PermissionStatus> statuses = await [
      Permission.storage,
      Permission.camera,
      Permission.microphone,
      Permission.manageExternalStorage,
    ].request();
    if (statuses[Permission.storage] == PermissionStatus.granted &&
        statuses[Permission.camera] == PermissionStatus.granted &&
        statuses[Permission.microphone] == PermissionStatus.granted &&
        statuses[Permission.manageExternalStorage] ==
            PermissionStatus.granted) {
      setState(() {
        havePermission = true;
      });
    }

### Code sample

 Map<Permission, PermissionStatus> statuses = await [
      Permission.storage,
      Permission.camera,
      Permission.microphone,
      Permission.manageExternalStorage,
    ].request();
    if (statuses[Permission.storage] == PermissionStatus.granted &&
        statuses[Permission.camera] == PermissionStatus.granted &&
        statuses[Permission.microphone] == PermissionStatus.granted &&
        statuses[Permission.manageExternalStorage] ==
            PermissionStatus.granted) {
      setState(() {
        havePermission = true;
      });
    }

### Version

10.2.0

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.3.9, on macOS 14.2.1 23C71 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.9 on channel stable at /Users/abandon/fvm/versions/3.3.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (1 year, 2 months ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/abandon/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/abandon/Library/Java/JavaVirtualMachines/corretto-11.0.20/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-11.0.20.8.1 (build 11.0.20+8-LTS)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.13135.65

**Comment by Cheng455153666** [comment] 2024-02-08 13:17
I encountered a similar issue.But the issue does't resolved.
flutter version: 3.16.x
permission_handler version: 11.1.0

Here are the steps to reproduce it:

1. Request permissions, and a system dialog pops up.
2. Don't select any permissions and exit the app to the background.
3. Wait or open other apps, during which the app may rebuild itself.
4. The system dialog disappears, but at this point, all permissions cannot be requested, and an error message appears: A request for permissions is already running, please wait for it to finish before doing another request.

I think you may be able to provide a recovery method. Thanks :)

**Comment by mvanbeusekom** [comment] 2024-02-13 08:39
Duplicate of #1261.

**Closed by mvanbeusekom** 2024-02-13 08:39 UTC
