### ISSUE TITLE
10.2.0 import failed

### ISSUE THREAD

**Issue by Mike-Android-Chow** [Baseflow/flutter-permission-handler#953] opened 2022-11-12 05:08 UTC
`Because projectname depends on permission_handler 10.2.0 which doesn't match any versions, version solving failed.
`

**Comment by minjie0707** [comment] 2022-11-12 05:09
If I change the 10.2.0 to any , and it works , and I local package version is 10.0.0 . Does this mean the 10.0.0 is the latest version that I can import?

**Comment by minjie0707** [comment] 2022-11-12 05:28
<img width="656" alt="image" src="https://user-images.githubusercontent.com/82426849/201458843-477f1811-87b8-4228-a627-299910b0b31a.png">

**Comment by JeroenWeener** [comment] 2023-07-11 15:06
Hi @Mike-Android-Chow, thank you for reaching out!

I did not fully understand your question. `permission_handler` should have several versions available, including `10.0.0`, `10.2.0`, and the latest at the time of writing, `10.4.2`. You can find a complete and up-to-date list at https://pub.dev/packages/permission_handler/versions.

**Comment by mvanbeusekom** [comment] 2023-07-12 09:58
Hi @Mike-Android-Chow. @JeroenWeener,

The problem is most likely related to the pub mirror that is being used. According to the attached output of the `flutter doctor -v` command @Mike-Android-Chow is using `pub.flutter-io.cn` as a pub repository which most likely in this case is not up to date with the original pub.dev repository.

Hence @Mike-Android-Chow is not able to find version 10.2.0 which at the time (when the issue was created) was available on pub.dev, but not on pub.flutter-io.cn.

Closing this issue as this is out of our hands.

**Closed by mvanbeusekom** 2023-07-12 09:58 UTC
Labels: status: needs more info, type: bug, P2
