### ISSUE TITLE
Apps crashing when enabling "REQUEST_INSTALL_PACKAGES" permission

### ISSUE THREAD

**Issue by deepuc** [Baseflow/flutter-permission-handler#806] opened 2022-03-05 13:24 UTC
## 🐛 Bug Report

Apps are crashing without any error after enabling "REQUEST_INSTALL_PACKAGES" permission. And when trying to get back to the app from recent it is causing the app to get stuck on the splash screen.  I'm not seeing this behavior in apps like WhatsApp when enabling or disabling permissions.

https://user-images.githubusercontent.com/94203385/156884848-1cf9d210-9504-4506-bae0-3479906ffd20.mp4

### Expected behavior
The app shouldn't crash after enabling "REQUEST_INSTALL_PACKAGES" permission.

### Reproduction steps
Run the example provided with this plugin and enable the "REQUEST_INSTALL_PACKAGES" permission and then get back to the app.
This will lead to a crash and the app will get stuck on the splash screen.

### Configuration
**Version:** 9.2.0

**Platform:** 
- [x] :robot: Android

**Comment by mvanbeusekom** [comment] 2022-03-08 11:02
Hi @deepuc, as annoying as it is, this is the correct behavior. Since Android 11 Google implemented this behavior as a security feature. You can see the issue tracker from Google [here](https://issuetracker.google.com/issues/154157387?pli=1).

Note that this is specific to the `REQUEST_INSTALL_PACKAGES` permission. I am not entirely sure why the App is still showing up in the emulator as it is actually closed (hence the `Lost connection` message in the debug window), this might be an emulator issue.

I will close this issue now as this seems expected behaviour, however feel free to leave a comment is you have additional questions or information.

**Closed by mvanbeusekom** 2022-03-08 11:02 UTC

**Comment by deepuc** [comment] 2022-03-25 10:22
> Hi @deepuc, as annoying as it is, this is the correct behavior. Since Android 11 Google implemented this behavior as a security feature. You can see the issue tracker from Google [here](https://issuetracker.google.com/issues/154157387?pli=1).
> 
> Note that this is specific to the `REQUEST_INSTALL_PACKAGES` permission. I am not entirely sure why the App is still showing up in the emulator as it is actually closed (hence the `Lost connection` message in the debug window), this might be an emulator issue.
> 
> I will close this issue now as this seems expected behaviour, however feel free to leave a comment is you have additional questions or information.

Thanks for replying but if it's intended then how apps like aurora store, vanced manager are not forced to stop when granting this permission. Do you know how they are avoiding it if it's intended behavior?
Thanks
