### ISSUE TITLE
Incorrect PermissionStatus value for Android

### ISSUE THREAD

**Issue by bambinoua** [Baseflow/flutter-permission-handler#260] opened 2020-04-09 13:16 UTC
`Permission.locationAlways` under Android returns `PermissionStatus.restricted` `(3)` but location services are enabled on device (emulator) and permission is **granted**, i.e. checkbox on app settings is **on**! And why comment says `restricted` `*Only supported by iOS`?!

**Comment by mvanbeusekom** [comment] 2020-04-09 13:49
That should indeed not be possible. Android doesn't define a `restricted` status so if this is the case it must be a mistake in the mapping logic. I will try to reproduce it.

**Comment by bambinoua** [comment] 2020-04-09 14:12
> That should indeed not be possible

But it is. When I ask for `Permission.locationAlways.status` using newest version I get `3` as returned value. When I ask for `PermissionHandler().checkPermissionStatus(PermissionGroup.locationAlways)` using `4.2.0+hotfix.3` I get `2` as returned value with the **same conditions**!

**Comment by mvanbeusekom** [comment] 2020-04-09 14:50
@marcelgarus can you chime in on this maybe? It seems that the enum sequence changed between 4.4.0 and 5.0.0. Is there any specific reason for this? On the native side (e.g. the Java implementation on Android I haven't updated the enums, so it looks like this might be a bit out of sync).

**Comment by bambinoua** [comment] 2020-04-09 15:09
All that I did I changed the call as I wrote above. When newest version is used I got `3` when I return to `4.2.0`  I got `2`. Again... just change the call. Then I do this:
```dart
if (returnedValue == PermissionStatus.granted) {
  // do stuff
}
```

**Comment by marcelgarus** [comment] 2020-04-09 16:48
Hmm. The `PermissionStatus` is implemented in the <kbd>permission_handler_platform_interface</kbd> package and in a quick comparison of the old code ([this](https://github.com/Baseflow/flutter-permission-handler/blob/65dd04845ce421af4f25a5ef1297ed310e17e4b7/permission_handler_platform_interface/lib/src/permission_handler_enums.dart#L5-43) & [this](https://github.com/Baseflow/flutter-permission-handler/blob/65dd04845ce421af4f25a5ef1297ed310e17e4b7/permission_handler_platform_interface/lib/src/method_channel/utils/codec.dart#L6)) and the [new code](https://github.com/Baseflow/flutter-permission-handler/blob/ac1147d003462cf613db8cae84e33dbefb405dc4/permission_handler_platform_interface/lib/src/permission_status.dart), I can't spot any differences in the encoding. These should be the encoded values:

old status | new status | code
---|---|---
`denied` | `denied` | 0
`granted` | `granted` | 1
`restricted` | `restricted` | 2
`unknown` | `undetermined` | 3
`neverAskAgain` | `permanentlyDenied` | 4

I only tested the code on Android though, because I don't have access to an Apple device.

> When newest version is used I got `3` when I return to 4.2.0 I got `2`.

What you're saying is that the native side returns different values depending on the plugin version?

**Comment by bambinoua** [comment] 2020-04-10 06:45
I use version `4.2.0+hotfix.3`! and source code is not what you show. Please compare [4.2.0+hotfix.3](https://github.com/Baseflow/flutter-permission-handler/blob/4.2.0%2Bhotfix.3/lib/src/permission_enums.dart) and [5.0.0+hotfix.3](https://github.com/Baseflow/flutter-permission-handler/blob/permission_handler-v5.0.0%2Bhotfix.3/permission_handler_platform_interface/lib/src/permission_status.dart). In first file you use `hand made` enums in second one standard enums. And **values are different**.

**Comment by marcelgarus** [comment] 2020-04-12 16:09
So, I did some digging and the update of <kbd>permission_handler</kbd> from 4.2.0 to 4.3.0 removed the `PermissionStatus.disabled` on the Dart side as well as on the native side ([here's the commit](https://github.com/Baseflow/flutter-permission-handler/commit/5ca47cbca7d3eb84216604f6558fe5d7137aeb77)).
That's long before I began working on this project and shouldn't affect any changes made just now. Just to make sure this isn't a bug of the pub tool, would you mind running `flutter clean` followed by `flutter pub get` and see if the error persists?

**Comment by bambinoua** [comment] 2020-04-14 08:06
You maybe will be laughing (as me nervous) but.. now using latest version of package `Permission.locationAlways.status` returns `1` `granted` (not as before `3` `restricted`) and it looks working correctly. But I am not bilnd and not stupied to write here what I didni't see. So it looks like come package caching bug or somethig like this...
So on this positive note we can close this issue if it was.

**Comment by marcelgarus** [comment] 2020-04-14 08:43
Yes, probably a package caching bug. @mvanbeusekom I believe we can close this issue then?

**Comment by mvanbeusekom** [comment] 2020-04-14 09:06
@marcelgarus thank you for helping out tackling this issue. @bambinoua also thanks for raising it and helping out. Will close the issue now, if something pops-up again let us know and we will reopen it.

**Closed by mvanbeusekom** 2020-04-14 09:06 UTC
Labels: platform: android, status: triage

**Comment by jkLennon** [comment] 2021-03-23 03:14
@bambinoua Have you found a solution?I also encountered system restrictions on location permissions，PermissionStatus return PermissionStatus.granted
