### ISSUE TITLE
Crashlytics is reporting crash is happening in PermissionManager.java line 140

### ISSUE THREAD

**Issue by grtushar** [Baseflow/flutter-permission-handler#659] opened 2021-08-31 07:53 UTC
## 🐛 Bug Report

**Stacktrace**

```
Caused by java.lang.NullPointerException
Attempt to invoke interface method 'void com.baseflow.permissionhandler.n$b.a(java.util.Map)' on a null object reference
com.baseflow.permissionhandler.PermissionManager.onRequestPermissionsResult (PermissionManager.java:140)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult (FlutterEngineConnectionRegistry.java:712)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult (FlutterEngineConnectionRegistry.java:412)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult (FlutterActivityAndFragmentDelegate.java:627)
io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult (FlutterActivity.java:640)
android.app.Activity.dispatchRequestPermissionsResult (Activity.java:8408)
android.app.Activity.dispatchActivityResult (Activity.java:8253)
android.app.ActivityThread.deliverResults (ActivityThread.java:4935)
android.app.ActivityThread.performResumeActivity (ActivityThread.java:4263)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4308)
android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:52)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2067)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:224)
android.app.ActivityThread.main (ActivityThread.java:7519)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:995)
```

**Version:** 7.1.0

**Platform:** 
- [x ] 🤖 Android

**Comment by florissmit1** [comment] 2021-09-10 12:56
I started working on making a fix for this issue, see: #666. It will fix the NullPointerException when running your application in release mode. It's good to know, that the mentioned use-case is not solved when running in development mode. I guess this issue has nothing to do with the NullPointerException showing up when running in release mode.

**Comment by JDDV** [comment] 2021-09-23 14:10
@grtushar did the new release of the permission handler version `^8.1.6` fix your issue? please let us know so we can close this issue, thanks in advance!

**Comment by grtushar** [comment] 2021-09-27 12:29
@JDDV thanks for your response. As this issue can't be produced in our test devices, what we need to do is to release the app first, then keep monitoring the Crashlytics. So, we will upgrade the plugin to your mentioned version before next release and will let you know the update.

**Comment by skripsimu** [comment] 2021-11-10 02:15
I still get error report from crashlytics in version 8.1.6
<img width="1124" alt="Screen Shot 2021-11-10 at 09 15 24" src="https://user-images.githubusercontent.com/35763779/141037210-92d0a3d7-69cb-40de-95c1-cc01140d43d5.png">

**Comment by MilosKarakas** [comment] 2021-12-02 14:45
We are getting this exception in the release version of the application.

Here is the full crash log:

`java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4864)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4901)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:52)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2307)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8512)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5506)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4851)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4901)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:52)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2307)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8512)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: java.lang.NullPointerException: 
  at com.baseflow.permissionhandler.PermissionManager.onRequestPermissionsResult (PermissionManager.java:150)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult (FlutterEngineConnectionRegistry.java:713)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult (FlutterEngineConnectionRegistry.java:412)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult (FlutterActivityAndFragmentDelegate.java:699)
  at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult (FlutterActivity.java:675)
  at android.app.Activity.dispatchRequestPermissionsResult (Activity.java:8724)
  at android.app.Activity.dispatchActivityResult (Activity.java:8545)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5499)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4851)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4901)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:52)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2307)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8512)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)`


Impacted users are using Android 11: 55%, Android 10: 33%, Android 9: 12%
90% of them are using Samung devices, there is one Xiaomi (Redmi 6A) and one OnePlus device (OnePlus 6).

**Comment by MilosKarakas** [comment] 2021-12-02 14:52
Similar one happened once on Sony Xperia L3 with Android 8.1:

`java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3622)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3662)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2903)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1623)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6548)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:445)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:857)
Caused by: java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4309)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3594)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3662)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2903)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1623)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6548)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:445)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:857)
Caused by: java.lang.NullPointerException: 
  at com.baseflow.permissionhandler.PermissionManager.onRequestPermissionsResult (PermissionManager.java:150)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult (FlutterEngineConnectionRegistry.java:713)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult (FlutterEngineConnectionRegistry.java:412)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult (FlutterActivityAndFragmentDelegate.java:699)
  at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult (FlutterActivity.java:675)
  at android.app.Activity.dispatchRequestPermissionsResult (Activity.java:7429)
  at android.app.Activity.dispatchActivityResult (Activity.java:7280)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4305)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3594)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3662)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2903)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1623)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6548)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:445)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:857)`

**Comment by JDDV** [comment] 2022-01-13 15:10
Hi @grtushar Was the issue solved by the fix mentioned by @florissmit1 ?

@skripsimu A bug I found today was requesting permission using Map<Permission, PermissionStatus> for requesting multiple permissions at the same time might result into a NullPointerException as well. This only happens when one or more of the permissions in the map that is being requested will execute a new Intent. This will cause the activity to be null since another intent is started and that will also result in a NullPointerException. Is this the case in your project as well? If not, I would like to see the full stacktrace if possible.

@MilosKarakas It seems like you're using a version before `8.1.6`. There was an issue where the `containsKey` method that was called on the `requestResults` variable would return a `NullPointerException` at line 150 of the `PermissionManager` class. Please update your project to use the newest version of the permission handler.

I'll close this issue for now. If there are still problems regarding this issue I would love to see a new issue!

**Closed by JDDV** 2022-01-13 15:10 UTC
Labels: platform: android, status: waiting for customer response

**Comment by grtushar** [comment] 2022-05-23 08:00
Hi, @JDDV this issue is resolved (No more Crashlytics reporting) after upgrading the version to ^8.1.6. Thanks for your cooperation.

**Comment by ShishirXT** [comment] 2024-05-10 05:29
Hi @JDDV 
We're encountering a similar issue. In the release version of the application, we're receiving the following exception.

**Package Version: permission_handler: ^11.0.0
Flutter Version: 3.13.6**


```
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4975)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:5018)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:60)
  at android.app.servertransaction.ActivityTransactionItem.execute (ActivityTransactionItem.java:45)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2374)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:233)
  at android.os.Looper.loop (Looper.java:344)
  at android.app.ActivityThread.main (ActivityThread.java:8249)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:589)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1071)
Caused by java.lang.RuntimeException:
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5568)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4953)
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
  at com.baseflow.permissionhandler.PermissionManager.onActivityResult (PermissionManager.java)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult
  at io.flutter.embedding.android.FlutterActivity.onActivityResult
  at android.app.Activity.dispatchActivityResult (Activity.java:8472)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5561)

Exception : java.lang.NullPointerException	Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:5094)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:5127)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:54)
  at android.app.servertransaction.ActivityTransactionItem.execute (ActivityTransactionItem.java:45)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2441)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:233)
  at android.os.Looper.loop (Looper.java:334)
  at android.app.ActivityThread.main (ActivityThread.java:8396)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:582)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1068)
Caused by java.lang.RuntimeException:
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5651)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:5081)
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
  at com.baseflow.permissionhandler.PermissionManager.onActivityResult (PermissionManager.java)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult
  at io.flutter.embedding.android.FlutterActivity.onActivityResult
  at android.app.Activity.dispatchActivityResult (Activity.java:8718)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5644)


```

Impacted users are using the following Android Version

<img width="597" alt="Screenshot 2024-04-22 at 1 10 22 PM (1)" src="https://github.com/Baseflow/flutter-permission-handler/assets/159430338/dac6d84a-2d05-43ef-96a1-924896b75bf8">
