### ISSUE TITLE
Remove REQUEST_INSTALL_PACKAGE permission

### ISSUE THREAD

**Issue by modimayur3812** [Baseflow/flutter-permission-handler#949] opened 2022-10-29 07:26 UTC
## 💬 Questions and Help

For questions or help we recommend checking the following:

REQUEST_INSTALL_PACKAGE is dangerous permission for an android higher version. Because whenever, we try to upload app to play console it shows me error. And the error says, you app include REQUEST_INSTALL_PACKAGE which is not your primary permission for app.

**Comment by mvanbeusekom** [comment] 2022-11-01 09:37
Hi @modimayur3812, 

This is not a problem caused by the permission_handler plugin, the issue is discussed at length in issue #869. 

A possible workaround is described [here](https://github.com/Baseflow/flutter-permission-handler/issues/869#issuecomment-1285128640).

Also note that it is likely that you'll have to remove builds you uploaded to the Google Play Store before a new build is accepted. More information on this can be found [here](https://github.com/Baseflow/flutter-permission-handler/issues/869#issuecomment-1280208815) and [here](https://github.com/Baseflow/flutter-permission-handler/issues/869#issuecomment-1286453623).

Closing this issue as the problem is not related to permission_handler package.

**Closed by mvanbeusekom** 2022-11-01 09:37 UTC
