### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by kameshkarthi** [Baseflow/flutter-permission-handler#576] opened 2021-06-03 07:41 UTC
## 🐛 Bug Report

Android app crashing after allowing the permissions and on popup close..

Version: 8.0.0+2

Platform: 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment] 2021-06-03 08:41
Hi @kameshkarthi, could you please provide some more details?

1. Which permissions are you requesting?
2. Can you provide a code snippet on how you are requesting permissions (or better a reproduction example, could be as simple as shown [here](https://github.com/Baseflow/flutter-permission-handler/issues/568#issuecomment-852101364))?
3. Please provide the some more details on the exception that occurs or the log output when the App crashes (an easy way to get log information is by running the App using the `flutter run --verbose`)?
4. Please provide the output of your `flutter doctor -v` command?

**Comment by kameshkarthi** [comment] 2021-06-03 09:10
Hello sir, Thank you

try{
      await [
        Permission.location,
        Permission.storage,
        Permission.camera,
        Permission.microphone,
        Permission.microphone,
      ].request();
    }
    catch(e){
      print(e.toString());
    }

This is my code and i got following error


W/Activity(31235): Can request only one set of permissions at a time
D/AndroidAudioRecorder(31235): onRequestPermissionsResult - false
E/MethodChannel#flutter.baseflow.com/geolocator(31235): Failed to handle method call
E/MethodChannel#flutter.baseflow.com/geolocator(31235): kotlin.UninitializedPropertyAccessException: lateinit property pResult has not been initialized
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at com.lucasjosino.on_audio_query.OnAudioQueryPlugin.onRequestPermissionsResult(OnAudioQueryPlugin.kt:161)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:712)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:412)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:627)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at io.flutter.embedding.android.FlutterFragment.onRequestPermissionsResult(FlutterFragment.java:716)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at io.flutter.embedding.android.FlutterFragmentActivity.onRequestPermissionsResult(FlutterFragmentActivity.java:492)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at android.app.Activity.requestPermissions(Activity.java:4542)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:516)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at com.baseflow.geolocator.permission.PermissionManager.requestPermission(PermissionManager.java:93)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at com.baseflow.geolocator.MethodCallHandlerImpl.onRequestPermission(MethodCallHandlerImpl.java:136)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at com.baseflow.geolocator.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:59)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at android.os.Looper.loop(Looper.java:165)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at android.app.ActivityThread.main(ActivityThread.java:6826)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/MethodChannel#flutter.baseflow.com/geolocator(31235): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
I/ActivityThread(31235): media acquiringCount 2
D/AndroidAudioRecorder(31235): onRequestPermissionsResult - false
D/AndroidRuntime(31235): Shutting down VM
E/AndroidRuntime(31235): FATAL EXCEPTION: main
E/AndroidRuntime(31235): Process: com.mecho.dude, PID: 31235
E/AndroidRuntime(31235): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.mecho.dude/com.mecho.dude.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property pResult has not been initialized
E/AndroidRuntime(31235): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4419)
E/AndroidRuntime(31235): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4461)
E/AndroidRuntime(31235): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(31235): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(31235): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(31235): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
E/AndroidRuntime(31235): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(31235): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(31235): 	at android.app.ActivityThread.main(ActivityThread.java:6826)
E/AndroidRuntime(31235): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31235): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(31235): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/AndroidRuntime(31235): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property pResult has not been initialized
E/AndroidRuntime(31235): 	at com.lucasjosino.on_audio_query.OnAudioQueryPlugin.onRequestPermissionsResult(OnAudioQueryPlugin.kt:161)
E/AndroidRuntime(31235): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:712)
E/AndroidRuntime(31235): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:412)
E/AndroidRuntime(31235): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:627)
E/AndroidRuntime(31235): 	at io.flutter.embedding.android.FlutterFragment.onRequestPermissionsResult(FlutterFragment.java:716)
E/AndroidRuntime(31235): 	at io.flutter.embedding.android.FlutterFragmentActivity.onRequestPermissionsResult(FlutterFragmentActivity.java:492)
E/AndroidRuntime(31235): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7749)
E/AndroidRuntime(31235): 	at android.app.Activity.dispatchActivityResult(Activity.java:7594)
E/AndroidRuntime(31235): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4412)
E/AndroidRuntime(31235): 	... 11 more
I/Process (31235): Sending signal. PID: 31235 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by kameshkarthi** [comment] 2021-06-03 09:26
Hello sir, Thank you

try {
      await [
        Permission.location,
        Permission.storage,
        Permission.camera,
        Permission.microphone,
      ].request();
    } catch (e) {
      print(e.toString());
    }

This is my code and i got following error,


D/AndroidAudioRecorder( 3817): onRequestPermissionsResult - false
D/AndroidRuntime( 3817): Shutting down VM
E/AndroidRuntime( 3817): FATAL EXCEPTION: main
E/AndroidRuntime( 3817): Process: com.mecho.app, PID: 3817
E/AndroidRuntime( 3817): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.mecho.app/com.mecho.app.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property pResult has not been initialized
E/AndroidRuntime( 3817): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4419)
E/AndroidRuntime( 3817): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4461)
E/AndroidRuntime( 3817): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime( 3817): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime( 3817): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime( 3817): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
E/AndroidRuntime( 3817): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 3817): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime( 3817): 	at android.app.ActivityThread.main(ActivityThread.java:6826)
E/AndroidRuntime( 3817): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3817): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime( 3817): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/AndroidRuntime( 3817): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property pResult has not been initialized
E/AndroidRuntime( 3817): 	at com.lucasjosino.on_audio_query.OnAudioQueryPlugin.onRequestPermissionsResult(OnAudioQueryPlugin.kt:161)
E/AndroidRuntime( 3817): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:712)
E/AndroidRuntime( 3817): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:412)
E/AndroidRuntime( 3817): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:627)
E/AndroidRuntime( 3817): 	at io.flutter.embedding.android.FlutterFragment.onRequestPermissionsResult(FlutterFragment.java:716)
E/AndroidRuntime( 3817): 	at io.flutter.embedding.android.FlutterFragmentActivity.onRequestPermissionsResult(FlutterFragmentActivity.java:492)
E/AndroidRuntime( 3817): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7749)
E/AndroidRuntime( 3817): 	at android.app.Activity.dispatchActivityResult(Activity.java:7594)
E/AndroidRuntime( 3817): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4412)
E/AndroidRuntime( 3817): 	... 11 more
W/com.mecho.app( 3817): Long monitor contention with owner pool-12-thread-1 (4536) at boolean android.os.BinderProxy.transactNative(int, android.os.Parcel, android.os.Parcel, int)(Binder.java:-2) waiters=0 in android.content.IContentProvider android.app.ActivityThread.acquireProvider(android.content.Context, java.lang.String, int, boolean) for 878ms
I/Process ( 3817): Sending signal. PID: 3817 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by mvanbeusekom** [comment] 2021-06-03 09:56
@kameshkarthi the problem is not the with the "permission_handler" but with the "[on_audio_query](https://pub.dev/packages/on_audio_query)" plugin. 

You can see this clearly by this line in the stack trace:

```
at com.lucasjosino.on_audio_query.OnAudioQueryPlugin.onRequestPermissionsResult(OnAudioQueryPlugin.kt:161)
```

The problem is that the "on_audio_query" plugin tries to handle the permissions request made by the "permission_handler" and doesn't recognise the `requestCode` (in this case 24) that the permission_handler uses. According to the Android documentation when this happens you should simply ignore it, however the "on_audio_query" plugin tries to send back a result too Flutter that is doesn't recognises the `requestCode`. Which of course doesn't work since the "on_audio_query" hasn't been asked to handle anything (since the request came from the "permission_handler"). 

There is already an [issue](https://github.com/LucasPJS/on_audio_query/issues/3) registered on the "on_audio_query" plugin reporting the same problem.

I am going to close this issue now as it isn't really a problem of the permission_handler.

**Closed by mvanbeusekom** 2021-06-03 09:56 UTC

**Comment by mvanbeusekom** [comment] 2021-06-03 12:48
@kameshkarthi I have created a [pull request](https://github.com/LucasPJS/on_audio_query/pull/8) at the "on_audio_query" plugin that should resolve this issue. Hopefully the maintainer of the plugin agrees with the solution and can release an update soon, which should resolve your issue.

**Comment by kameshkarthi** [comment] 2021-06-03 12:55
Thank you so much bro!
