### ISSUE TITLE
Unable to build for iOS

### ISSUE THREAD

**Issue by GroovinChip** [Baseflow/flutter-permission-handler#343] opened 2020-07-02 01:34 UTC
## 🐛 Bug Report

I am unable to build my app for iOS. I have only just gotten my first mac, and set about updating my Flutter app to run on iOS. I was getting a build failure due to a deprecated method from this package. I followed the tips in #191 to solve the problem but that didn't help. 

Here is the error log:

```
** BUILD FAILED **


Xcode's output:
↳
/Users/groov/development/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-4.4.0+hotfix.4/ios/Classes/strategies/NotificationPermissionStrategy.m:71:5: warning: 'UIRemoteNotificationType' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]
    UIRemoteNotificationType type = [[UIApplication sharedApplication] enabledRemoteNotificationTypes];
    ^
In module 'UIKit' imported from /Users/groov/development/flutter_projects/apps/CallManager/ios/Pods/Target Support Files/permission_handler/permission_handler-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:69:32: note: 'UIRemoteNotificationType' has been explicitly marked deprecated here
typedef NS_OPTIONS(NSUInteger, UIRemoteNotificationType) {
                               ^
/Users/groov/development/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-4.4.0+hotfix.4/ios/Classes/strategies/NotificationPermissionStrategy.m:71:72: warning: 'enabledRemoteNotificationTypes' is deprecated: first deprecated in iOS 8.0 - Use -[UIApplication isRegisteredForRemoteNotifications] and UserNotifications Framework's -[UNUserNotificationCenter getNotificationSettingsWithCompletionHandler:] to retrieve user-enabled remote notification and user notification settings [-Wdeprecated-declarations]
    UIRemoteNotificationType type = [[UIApplication sharedApplication] enabledRemoteNotificationTypes];
                                                                       ^
In module 'UIKit' imported from /Users/groov/development/flutter_projects/apps/CallManager/ios/Pods/Target Support Files/permission_handler/permission_handler-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:229:1: note: 'enabledRemoteNotificationTypes' has been explicitly marked deprecated here
- (UIRemoteNotificationType)enabledRemoteNotificationTypes API_DEPRECATED("Use -[UIApplication isRegisteredForRemoteNotifications] and UserNotifications Framework's -[UNUserNotificationCenter getNotificationSettingsWithCompletionHandler:] to retrieve user-enabled remote notification and user notification settings", ios(3.0, 8.0)) API_UNAVAILABLE(tvos);
^
2 warnings generated.
Command CompileSwift failed with a nonzero exit code
/Users/groov/development/flutter/.pub-cache/hosted/pub.dartlang.org/call_number-0.0.1/ios/Classes/CallNumberPlugin.m:14:42: error: expected identifier
    result([@"Not yet Implemented in iOS"]);
                                         ^
1 error generated.
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')
```

**Comment by mvanbeusekom** [comment] 2020-07-02 08:22
@GroovinChip the deprecation warning from the permission_handler are not the real problem (although I admit they obscure the actual error a bit ;)). 

Your real issue is with the `call_number` plugin (see the error directly below the `2 warnings generated`):
```
/Users/groov/development/flutter/.pub-cache/hosted/pub.dartlang.org/call_number-0.0.1/ios/Classes/CallNumberPlugin.m:14:42: error: expected identifier
    result([@"Not yet Implemented in iOS"]);
```

I took the liberty on checking out the `call_number` plugin and it seems it doesn't support iOS (see iOS implementation [here](https://github.com/sreesdas/flutter_call_number_plugin/blob/master/ios/Classes/CallNumberPlugin.m)).

By the way if you are able to migrate to version 5.0.1 you will also no longer receive the deprecation warnings anymore, they are suppressed in the later versions. The permission_handler has code inside that is only called on lower iOS platform versions which still rely on the by now deprecated methods. You don't have to worry about this, since it is only executed if the platform version requires it.

I will close this issue now since the problem is not related to the permission_handler.

**Closed by mvanbeusekom** 2020-07-02 08:22 UTC

**Comment by GroovinChip** [comment] 2020-07-02 13:58
Thank you @mvanbeusekom !
