### ISSUE TITLE
requestAlwaysAuthorization is not supported on iOS AppClip

### ISSUE THREAD

**Issue by miguelpruivo** [Baseflow/flutter-permission-handler#394] opened 2020-09-25 16:38 UTC
## 🐛 Bug Report

When deploying to AppStore an app with AppClip (iOS 14) it fails the submission with the following:
```
Invalid SDK usage - App clip 'Runner.app/AppClips/AppClip.app' uses the SDK selector 'requestAlwaysAuthorization', which is not supported. Ensure your app clip is using supported SDK features.
```

### Expected behavior

Being able to deploy.

### Reproduction steps

Just use the plugin and create an AppClip. Deploy an app with it.

### Configuration

**Version:** 5.0.0+hotfix.5

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by luismarquesfreire** [comment] 2020-09-27 16:54
This seems to be related with XCode 12 as it no longer support iOS 8.0. This is critical. We cannot upload to App Store with this issue. It causes the App Store Binary with issues email:

Dear Developer,
We identified one or more issues with a recent delivery for your app...

ITMS-90842: Invalid SDK usage - App clip 'Runner.app/AppClips/AppClip.app' uses the SDK selector 'requestAlwaysAuthorization', which is not supported. Ensure your app clip is using supported SDK features.

**Comment by solo-lgolden** [comment] 2023-03-16 12:43
Is there any update/solution to this? This is blocking our release

**Comment by JeroenWeener** [comment] 2023-08-30 14:47
According to #1010 the issue is still present in version 10.2.0 of the plugin.

**Comment by mvanbeusekom** [comment] 2023-09-18 18:46
The problem here (as already mentioned by @solo-lgolden) is that the default configuration in the Podfile is applied to all targets. This means that if you enable the location permissions for your normal app they are also enable for the App Clip target.

I believe a possible solution would be to update the configuration in your Podfile to skip enabling permissions for the App Clip target:

```ruby
if target.name == '<Your App Clip target name here>'
    next
end
```

A complete example for an App Clip called "RunnerAppClip" could look something like this: 

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|

      # Skip declaring preprocessor definitions for the App Clip target called "RunnerAppClip".
      if target.name == 'RunnerAppClip'
            next
      end

      # You can remove unused permissions here
      # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
        'PERMISSION_EVENTS=1',

        ## dart: PermissionGroup.reminders
        'PERMISSION_REMINDERS=1',

        ## dart: PermissionGroup.contacts
        'PERMISSION_CONTACTS=1',

        ## dart: PermissionGroup.camera
        'PERMISSION_CAMERA=1',

        ## dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=1',

        ## dart: PermissionGroup.speech
        'PERMISSION_SPEECH_RECOGNIZER=1',

        ## dart: PermissionGroup.photos
        'PERMISSION_PHOTOS=1',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=1',
       
        ## dart: PermissionGroup.notification
        'PERMISSION_NOTIFICATIONS=1',

        ## dart: PermissionGroup.mediaLibrary
        'PERMISSION_MEDIA_LIBRARY=1',

        ## dart: PermissionGroup.sensors
        'PERMISSION_SENSORS=1',

        ## dart: PermissionGroup.bluetooth
        'PERMISSION_BLUETOOTH=1',

        ## dart: PermissionGroup.appTrackingTransparency
        'PERMISSION_APP_TRACKING_TRANSPARENCY=1',

        ## dart: PermissionGroup.criticalAlerts
        'PERMISSION_CRITICAL_ALERTS=1',
      ]

    end
  end
end
```

The `ios/Podfile` is constructed using Ruby programming language, this means we can use all Ruby constructs to filter of manipulate the preprocessor definitions.

I will go ahead and close this issue for now. If you have any questions please feel free to leave a comment and I would be happy to look into it.

**Closed by mvanbeusekom** 2023-09-18 18:46 UTC
Labels: platform: ios, type: bug, P2
