### ISSUE TITLE
Location permission status fetched as "undetermined" in Android, after permanately denyming 

### ISSUE THREAD

**Issue by kristijorgji** [Baseflow/flutter-permission-handler#390] opened 2020-09-16 13:07 UTC
### Steps to reproduce + expected behavior

1. User clicks deny location permission in Android
2. You ask for permission again, they click deny this time and also tick the checkbox "Do not ask again"
<img width="313" alt="Screenshot 2020-09-16 at 15 13 16" src="https://user-images.githubusercontent.com/15630854/93342086-308e3980-f82f-11ea-93dc-2765cf094273.png">

3. afterward, next time we call the code below it has wrong result
Result of  

```
PermissionWithService lp = await ph.Permission.location;
await lp.isUndetermined
```

should be false

I expect 
lp.isUndetermined or lp.isPermanatelyDenied to be true instead because undertermined as you document it is the initial status when the user does not select anything, but in case reported here customer selected "DENY" and also "Do not ask again"

### Configuration

permission_handler: ^5.0.1+1

**Platform:** 
- [y] :robot: Android

**Comment by gkrawiec** [comment] 2020-11-01 19:03
can confirm. same issue.

**Comment by novas1r1** [comment] 2020-11-04 15:39
Same issue for me: Pixel 2, Android 11

**Comment by bazurtovqhr** [comment] 2020-11-06 22:19
Same issue but requesting storage access. Android 10

**Comment by xuzhaokai** [comment] 2020-11-19 07:59
You can try this : [ph.Permission.location.request().isPermanentlyDenied]. seem it is ok

**Comment by 159159951** [comment] 2020-12-03 10:29
> You can try this : [ph.Permission.location.request().isPermanentlyDenied]. seem it is ok

You saved my day.
Thanks with heart

**Comment by Sempakonka** [comment] 2021-01-04 14:08
Hi,
To keep the issues on this repo more organized I am going to close this ticket, as I think it is a duplicate of #336 .
Don't hestitate to re-open if you think otherwise!

**Closed by Sempakonka** 2021-01-04 14:08 UTC
