### ISSUE TITLE
Storage Permission not working

### ISSUE THREAD

**Issue by gegobyte** [Baseflow/flutter-permission-handler#885] opened 2022-08-04 12:06 UTC
## 🔙 Regression

I have an app which asks user for storage permission and then proceeds to download a file in the `Download` directory on the device. I am using the latest version of Permission Handler which is `10.0.0` but on my new app created with the latest version of Flutter, getting this error:

```
FileSystemException: Cannot open file, path = '/storage/emulated/0/Download/abc.pdf' (OS Error: Permission denied, errno = 13)
```

Here is the code for request permission and saving the file to Download folder:

```dart
try {
      final output = await getExternalStorageDirectory();
      RegExp pathToDownloads = RegExp(r'.+0\/');
      final outputPath = '${pathToDownloads.stringMatch(output!.path).toString()}Download'; // returns /storage/emulated/0/Download
      final filePath = '$outputPath/abc.pdf';
      var file = File(filePath);

      // Ask for storage permission
      if (await Permission.storage.request().isGranted) {
        await file.writeAsBytes(pdfBytes);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('File has been downloaded'),
            duration: Duration(seconds: 2),
          ),
        );
      }
    } catch (error) {
      print(error);
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text(
              'Allow storage permission so that file pdf can be saved'),
          duration: Duration(seconds: 2),
        ),
      );
    }
```

The above code asks for permission but despite tapping on Allow, the catch part is triggered and it gives the above permission error. Permission is also set in the manifest file:

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`

### Old (and correct) behavior
The above code used to work flawlessly on my old app and still works with the latest version `10.0.0` but my new app created with latest version of Flutter does not work.

### Current behavior
These are the minimum and target sdk version in `build.gradle`
```
minSdkVersion 21
targetSdkVersion 33
```
### Configuration
**Permission Handler Version:** 10.0.0
**Flutter Version:** 3.0.5

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by JDDV** [comment] 2022-08-08 11:51
Hi @gegobyte, It seems like I can reproduce it half of the time using your code strange enough. I had it succeeded, where the file `abc.pdf` is created. But also times where he said the permission wasn't granted.

I tested it on API 31 (Android 12).

Can you provide me a bit more information, and tell me on what Android version you're testing this?

Can you try adding the following permission too, see if it fixes the problem? :
```
<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
```

**Comment by gegobyte** [comment] 2022-08-09 09:49
> Can you provide me a bit more information, and tell me on what Android version you're testing this?

I've also tested on Android 12. I am also getting the same result - sometimes it downloads successfully, sometimes I get permission error.

**Comment by gegobyte** [comment] 2022-08-24 15:30
@JDDV Do you recommend any temporary solution until this is fixed?

**Comment by armandojimenez** [comment] 2022-08-30 01:47
Any fix for this?

**Comment by naumanmir** [comment] 2022-09-01 08:54
@gegobyte you need to use "manageExternalStorage" permission both at runtime and in manifest along with storage permission.

**Comment by PeterNjeim** [comment] 2022-09-01 17:27
The temporary solution is to go to the app's settings and revoke the file permission, then regrant the permission. Then you can open the app again and it should have file access.

**Comment by PeterNjeim** [comment] 2022-09-01 18:11
Android 13: works fine
Android 12 and 12.1/12L: permission is "fake" granted, user needs to go to App's settings (in Android settings) and revoke and regrant the file access permission for it to actually apply.
Android 11: `needs testing`
Android 10: `needs testing`

This is with WRITE_EXTERNAL_STORAGE permission with a targetSdkVersion of 29 (Android 10), that way I can use the requestLegacyExternalStorage="true" option.

Someone else should test this on Android 11 and Android 10 to see if it's limited to Android 12 and 12.1 / 12L only

**Comment by gegobyte** [comment] 2022-09-14 11:34
> @gegobyte you need to use "manageExternalStorage" permission both at runtime and in manifest along with storage permission.

Would Google not reject the app after using manage external storage permission. I have read a few instances of apps getting rejected using this permission and targeting Android 11.

**Comment by Shvet** [comment] 2022-09-30 10:59
Android 33 Emulator not working

**Comment by dsingh06** [comment] 2022-10-16 14:18
I have the exact same problem, very similar code with:

minSdkVersion 21
targetSdkVersion 33

Checking on a physical device, there is no permission popup.

**Comment by PeterNjeim** [comment] 2022-10-16 14:30
@dsingh06 can you try my workaround and reply back to me?

**Comment by dsingh06** [comment] 2022-10-16 16:30
> @dsingh06 can you try my workaround and reply back to me?

Hi, it is not fully clear to me what your workaround is and steps to be followed. 

When I goto app settings, I cannot see individual permissions mentioned where I can  revoke them (mentioning it in case this is part of your workaround)

**Comment by PeterNjeim** [comment] 2022-10-16 16:51
@dsingh06 See the attached images. Press "Don't allow" then "Allow"

**Comment by dsingh06** [comment] 2022-10-16 22:28
I do not see 'Files Permission' mentioned anywhere (neither in 'Allowed' nor 'Not Allowed'. My Manifest files do have external storage mentioned.

**Comment by PeterNjeim** [comment] 2022-10-16 22:56
@dsingh06 The lack of the permission in the permissions list is probably your problem, not related to this issue. Since you're targeting Android SDK 33, I don't believe you can use external storage permission anymore. Target a lower SDK version and try again

**Comment by StarkZzzOoo** [comment] 2022-11-21 10:05
I change permmission in settings ,and it work.but it's not a good method for user.

**Comment by aacsus** [comment] 2022-12-05 17:19
I have the same problem. Emulator does not ask External Storage Permission.
I load the .apk to my Android 11, API 33 phone, and it works fine. I use the latest Android Studio.
Both Emulator and Phone ask AUDIO permission though.

**Comment by PeterNjeim** [comment] 2022-12-05 22:44
@aacsus can you try my workaround and see if it works?

**Comment by aacsus** [comment] 2022-12-09 18:18
> @aacsus can you try my workaround and see if it works?

I tried to downgrade SDK 33 to SDK 30. Everything got screwed up. A lot of errors. I then lowered the other components' versions too. No help. SDK 30 was pushing me to SDK 31. When switched to 31, it in turn pushed me to 32. I ended up going back to SDK 33. Now, it stopped asking AUDIO too. No permissions asked, it runs the program!

**Comment by PeterNjeim** [comment] 2022-12-09 20:25
@aacsus Well, since you're on API 33 you can't ask for the manage external storage permission. If you want that permission you need to downgrade. You need to stop using features that are only available in API 33 for that to work. That's an Android thing, and isn't related to this repository. You can't even use my workaround, because you can't even request the permission currently.

**Comment by PeterNjeim** [comment] 2022-12-09 20:29
@aacsus Which permission are you requesting? If you can't see the permission in the settings page, then you probably are using a deprecated permission.

**Comment by aacsus** [comment] 2022-12-28 16:09
@PeterNjeim FILE and AUDIO permissions (multi permissions). I improved the code little bit, it started asking AUDIO again (in SDK 33). However, FILE permission is still the same; works in Android phone (V11, API 33), but does not work in the Emulator. The SETTINGS page in Emulator does not show FILE permission, while both are visible in phone.

**Comment by aeaevo** [comment] 2023-01-02 20:43
Does anyone have a real fix for this issue yet? Please don't tell me that the user has to revoke rights in the settings and regrant them, that is not a fix 😂

`await Permission.storage.request().isGranted` does not show a popup to grant permission. Other permissions work fine.

**Comment by PeterNjeim** [comment] 2023-01-02 21:09
It's fine to say you want a fix, it's _not_ fine to say someone else is lying about their "fix". I never said it was a fix, I said it was a workaround, which is a big difference. My message only serves to help people temporarily while a fix is waited for. Please adjust your comment to say that you don't care about workarounds, instead of misrepresenting my comments

**Comment by aeaevo** [comment] 2023-01-03 05:41
@PeterNjeim I really did not mean to offend you at all and I do appreciate everyone's efforts here! Classic misunderstanding... Let's just concentrate on solving this issue. I am curious how such a major bug persists since August last year - is there a bigger underlying problem?

Did someone try to switch from stable flutter version to master?

**Comment by aeaevo** [comment] 2023-01-03 06:05
Same issue for flutter latest stable & master channel

**Comment by blue492** [comment] 2023-01-03 08:06
Same here, `Permission.storage.request().isGranted` don't show ask permission popup and return false always

Here are my permissions in AndroidManifest.xml
```
   <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" tools:node="remove" />

    <queries>
        <!-- If your app opens https URLs -->
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>
  
        <intent>
            <action android:name="android.intent.action.DIAL" />
            <data android:scheme="tel" />
        </intent>
    
        <intent>
            <action android:name="android.intent.action.SEND" />
            <data android:mimeType="*/*" />
        </intent>
    </queries>
```

**Comment by aeaevo** [comment] 2023-01-03 08:35
I guess @PeterNjeim already did mention the main reason why most of us (maybe even all of us) are facing this problem earlier in this thread. We don't need to ask for the READ_EXTERNAL_STORAGE permission since targetSDK 33 anymore. Check [this thread on StackOverflow](https://stackoverflow.com/questions/72948052/android-13-read-external-storage-permission-still-usable). 

So this works without any permission request:

`
Directory? storageDirectory;
if (Platform.isAndroid) {
  storageDirectory = await getExternalStorageDirectory();
} else if (Platform.isIOS) {
  storageDirectory = await getApplicationDocumentsDirectory();
}
`

**Comment by NawrasBukhari** [comment] 2023-03-15 15:11
this issue still presents till today

**Comment by AndersonMichellin** [comment] 2023-04-26 23:29
I had the same problem as described here and I haven't found any definitive solution so far.
Here's what I did to resolve it:
I updated the package_info_plus, file_picker, permission_handler and device_info_plus to the latest versions and everything is working again.
However, it is worth remembering that it is necessary to treat the SDK version to verify the permissions:

  Future<bool> ePermitidoGravar() async {
    DeviceInfoPlugin plugin = DeviceInfoPlugin();
    AndroidDeviceInfo android = await plugin.androidInfo;
    if( android.version.sdkInt < 33 ){
      var status = Platform.isAndroid
        ? await Permission.storage.status
        : await Permission.photos.status;               //https://github.com/Baseflow/flutter-permission-handler/issues/440
      if (!status.isGranted) {
        if(Platform.isAndroid){
          status = await Permission.storage.request();
          if(status.isPermanentlyDenied){
            await openAppSettings();
            status = await Permission.storage.status;              //https://github.com/Baseflow/flutter-permission-handler/issues/440
          }
        }else{
          status = await Permission.photos.request();
          if(status.isPermanentlyDenied){
            await openAppSettings();
            status = await Permission.photos.status;               //https://github.com/Baseflow/flutter-permission-handler/issues/440
          }
        }
        if(!status.isGranted){
          return false;
        }
      }
    }else {
      var status = Platform.isAndroid
        ? await Permission.manageExternalStorage.status
        : await Permission.photos.status;                 //https://github.com/Baseflow/flutter-permission-handler/issues/440
      if (!status.isGranted) {
        if (Platform.isAndroid) {
          status = await Permission.manageExternalStorage.request();
          if(status.isPermanentlyDenied){
            await openAppSettings();
            status = await Permission.storage.status;              //https://github.com/Baseflow/flutter-permission-handler/issues/440
          }
        } else {
          status = await Permission.photos.request();
          if (status.isPermanentlyDenied) {
            await openAppSettings();
            status = await Permission.photos.status;
          }
        }
      }
    }
    return true;
  }

**Comment by petermusembi69** [comment] 2023-05-10 06:04
Add this permission in the manifest file - [source](https://stackoverflow.com/questions/73484221/how-to-define-permission-in-manifest-specifically-for-newer-android-sdk)

```yaml
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
```

**Comment by VirtualAstronaut** [comment] 2023-07-03 10:45
> MANAGE_EXTERNAL_STORAGE

This is sensitive permission and should not be used if does not full-fill [use case list](https://support.google.com/googleplay/android-developer/answer/10467955?sjid=14230517013027055727-AP)

**Comment by mvanbeusekom** [comment] 2023-07-03 11:17
Duplicate of issue #955. 

The permission_handler is working as intended, have a look at [this comment](https://github.com/Baseflow/flutter-permission-handler/issues/955#issuecomment-1614478427) for more details.

**Closed by mvanbeusekom** 2023-07-03 11:17 UTC
Labels: platform: android, type: bug
