### ISSUE TITLE
Bug IOS Permission.request 

### ISSUE THREAD

**Issue by JunnanLee** [Baseflow/flutter-permission-handler#433] opened 2021-01-04 11:19 UTC
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/18182976/103529820-4d737900-4ec1-11eb-974a-9ec4ef009bc9.png)
![image](https://user-images.githubusercontent.com/18182976/103529864-611edf80-4ec1-11eb-9792-e72f2e16f6c0.png)

only output PermissionStatus.undetermined.

**Version:** 5.0.1+1

**Platform:** 
- [x] :iphone: iOS14

**Comment by Sempakonka** [comment] 2021-01-04 14:40
possibly related to #336

**Comment by pawlowskim** [comment] 2021-02-19 18:57
I had the same issue. I have updated to 5.1.0+2 and it seems to work right now. It was not working only in test flights (app store as well) builds. In debug or release build locally it worked.

**Comment by hiashutoshsingh** [comment] 2021-03-19 08:52
> ## 🐛 Bug Report
> ![image](https://user-images.githubusercontent.com/18182976/103529820-4d737900-4ec1-11eb-974a-9ec4ef009bc9.png)
> ![image](https://user-images.githubusercontent.com/18182976/103529864-611edf80-4ec1-11eb-9792-e72f2e16f6c0.png)
> 
> only output PermissionStatus.undetermined.
> 
> **Version:** 5.0.1+1
> 
> **Platform:**
> 
> * [x]  📱 iOS14

I had the same issue for the past 2 days can't find a solution yet.

**Comment by JDDV** [comment] 2021-07-23 13:45
Hi @JunnanLee and @hiashutoshsingh, I tried to reproduce the same, but for me it works.
Can you both try using the newest version of the plugin (^8.1.4+1) and also update the `podfile` since version ^8.0.0 has a breaking change where you need to change the `podfile` as mentioned in the [documentation](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/README.md#setup).
Also make sure you've added the permission description in the `info.plist`. I'll close this issue for now since I'm pretty sure it will solve the problem if you update the `podfile` and use the newest version of the plugin. If it did not work please reopen this issue and let me know!

**Closed by JDDV** 2021-07-23 13:45 UTC
Labels: platform: ios
