### ISSUE TITLE
plugin_platform_interface ^1.0.2

### ISSUE THREAD

**Issue by denkoul** [Baseflow/flutter-permission-handler#467] opened 2021-03-04 09:56 UTC
## 🐛 Bug Report
When running pub get:

Because file_picker >=3.0.0-nullsafety.3 depends on plugin_platform_interface ^2.0.0 and permission_handler_platform_interface ^2.0.1 depends on plugin_platform_interface ^1.0.2, file_picker >=3.0.0-nullsafety.3 is incompatible with permission_handler_platform_interface ^2.0.1.

### Reproduction steps
running pub get
### Configuration

**Version:** '>=2.9.0 <3.0.0'

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment] 2021-03-04 10:25
duplicate of #464

**Closed by mvanbeusekom** 2021-03-04 10:25 UTC
