### ISSUE TITLE
Android image library permission not working

### ISSUE THREAD

**Issue by feykro** [Baseflow/flutter-permission-handler#1020] opened 2023-03-30 09:26 UTC
## 🐛 Bug Report

When I want to ask the user's permission to access their storage to pick and upload a file, the permission prompt isn't shown. It works for the camera though. Bug present in both version 10.0 and 10.2 of the plugin.

### Expected behavior

The call to `Permission.storage.request()` should open a permission pop-up and ask the user to grant their permission to access storage. It doesn't and returns denied by default.
 
### Reproduction steps

Call `Permission.storage.request()` on an Android 33 app, and observe no pop up.

### Configuration

**Version:** 10.0 and 10.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android (API 33), seems like it works on Android 12 (API 31)

**Comment by marcodecarolisidt** [comment] 2023-03-30 11:06
I see the issue as well, makes our app not working in android 13

**Comment by DenisMrGnusa** [comment] 2023-04-03 15:44
same as me with very similar configuration

**Comment by lumianchan** [comment] 2023-04-04 01:46
set compileSdkVersion 32

**Comment by tmgnr75** [comment] 2023-04-05 08:46
Same here, the prompt does not show on Android 13.

**Comment by feykro** [comment] 2023-04-05 14:07
@lumianchan I have set compileSdkVersion 32 while maintaining targetVersion to 33 and it seems to work, but it doesn't take advantage of the new permissions and seems to rely on OS retrocompatibility.
That's a good enough temporary fix, but I think something should definitely be implemented to handle this, even if it's just some documentation. I'm particularly wondering how it works for documents such as PDF since the new permission are related to media files only (Audio, Video and Photos).

**Comment by ahmed-raza-92** [comment] 2023-04-06 06:54
I have same issue. Tried everything but not working on android 13. Can anyone help regarding this.

**Comment by RoyalCoder88** [comment] 2023-04-07 10:28
same problem on Android 13, please fix it asap...thanks in advance!

**Comment by chianglife** [comment] 2023-04-12 07:14
same, and I have used [photo_manager 2.6.0](https://pub.flutter-io.cn/packages/photo_manager) instead

**Comment by Orhan-Kahraman** [comment] 2023-05-11 09:40
Guys, many people have experienced this problem, but this is not a problem, it comes from the change in user permissions with a decision made by android. In Android 10 and above, you no longer need to ask for storage permission to access the media. If you don't believe me and want to be satisfied, check out the links below :D

[Privacy changes in Android 10](https://developer.android.com/about/versions/10/privacy/changes)
[Access app-specific files](https://developer.android.com/training/data-storage/app-specific#external)
[Access media files from shared storage](https://developer.android.com/training/data-storage/shared/media)

**Comment by JeroenWeener** [comment] 2023-07-04 11:13
Thank you for filing this issue @feykro!

This is a duplicate of #955. As mentioned there, and by @Orhan-Kahraman here, Android has changed the way storage permissions work in Android 13. For more information, you can have a look here: https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions. The plugin is therefore working as intended.

If you have suggestions for clarifying this to users of the plugin, feel free to open an issue! We want to make sure users know how to achieve this common use case. As an example of our ongoing efforts to increase usability, we recently merged an update to our example app's `AndroidManifest.xml`: https://github.com/Baseflow/flutter-permission-handler/pull/1081.

**Closed by JeroenWeener** 2023-07-04 11:13 UTC
