### ISSUE TITLE
https://stackoverflow.com/questions/76506501/flutter-app-storage-permission-issue-on-android-13-devices

### ISSUE THREAD

**Issue by DhruvalPrime** [Baseflow/flutter-permission-handler#1069] opened 2023-06-19 12:27 UTC
please check this and help me

https://stackoverflow.com/questions/76506501/flutter-app-storage-permission-issue-on-android-13-devices

**Comment by harshitwe360** [comment] 2023-06-21 12:10
I m also facing this issue

**Comment by A7MeDG0L0L** [comment] 2023-06-22 07:45
Same...

**Comment by JeroenWeener** [comment] 2023-06-29 10:34
Thank you for filing this issue!

This is a duplicate of #955. I am therefore going to close it. Until the issue is resolved, the comments on that issue may provide you with valuable solutions in the meantime.

**Closed by JeroenWeener** 2023-06-29 10:34 UTC
