### ISSUE TITLE
Flutter Permission Handler for MacOS.

### ISSUE THREAD

**Issue by DenisMrGnusa** [Baseflow/flutter-permission-handler#886] opened 2022-08-09 09:40 UTC
## Flutter Permission Handler for MacOS

I hope this plugin can also support for macOS in addition to being able to desktop windows.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :MacOS

**Comment by hassan-2040** [comment] 2022-10-02 20:53
@DenisMrGnusa hi, did you find a workaround for this? I need to ask cam/mic permission on mac os but I cant seem to find a way. Did you get it to work?

**Comment by egyleader** [comment] 2023-03-22 16:14
I also vote for this feature , is it planned to be implemented in this plugin so people can submit a pull request ?

**Comment by bvoq** [comment] 2023-04-03 14:33
Bump on this feature.

**Comment by LinHaoLove** [comment] 2023-05-23 08:01
I also vote for this feature!

**Comment by JeroenWeener** [comment] 2023-09-18 08:35
Closing as this is a duplicate of #337.

**Closed by JeroenWeener** 2023-09-18 08:35 UTC
Labels: type: enhancement, platform: macos, P3
