### ISSUE TITLE
Getting NSUserTrackingUsageDescription info plist warning after IPA submission

### ISSUE THREAD

**Issue by armandojimenez** [Baseflow/flutter-permission-handler#906] opened 2022-09-04 02:00 UTC
## 🔙 Regression

I don't use any ads sdk, but now Apple is warning me about this permission below that I am not asking. When searching in my workspace, the only one that access this APIs is this package. I have configured the podfile correctly by having the app transparency tracking commented.

### Old (and correct) behavior
Upload build with no warning

### Current behavior
Getting this warning after submission
```
Dear Developer,We identified one or more issues with a recent delivery for your app, "Believe - Daily Affirmations" 4.0.0 (83). Your delivery was successful, but you may wish to correct the following issues in your next delivery:ITMS-90683: Missing Purpose String in Info.plist - Your app‘s code references one or more APIs that access sensitive user data. The app‘s Info.plist file should contain a NSUserTrackingUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required.
```

### Reproduction steps
Upload ipa to testflight

**Version:** 9.2.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by armandojimenez** [comment] 2022-09-04 22:07
Can anyone help with this? this is my current podfile config, and did clean and pod install

```
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  # pod 'DKImagePickerController/PhotoGallery', :git => 'https://github.com/miguelpruivo/DKImagePickerController.git'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)


    target.build_configurations.each do |config|

      
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
        # 'PERMISSION_EVENTS=0',

        ## dart: PermissionGroup.reminders
        # 'PERMISSION_REMINDERS=0',

        ## dart: PermissionGroup.contacts
        # 'PERMISSION_CONTACTS=0',

        ## dart: PermissionGroup.camera
        'PERMISSION_CAMERA=1',

        ## dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=1',

        ## dart: PermissionGroup.speech
        # 'PERMISSION_SPEECH_RECOGNIZER=0',

        ## dart: PermissionGroup.photos
        'PERMISSION_PHOTOS=1',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        # 'PERMISSION_LOCATION=0',
       
        ## dart: PermissionGroup.notification
        'PERMISSION_NOTIFICATIONS=1',

        ## dart: PermissionGroup.mediaLibrary
        'PERMISSION_MEDIA_LIBRARY=1',

        ## dart: PermissionGroup.sensors
        # 'PERMISSION_SENSORS=0',   
        
        ## dart: PermissionGroup.bluetooth
        # 'PERMISSION_BLUETOOTH=0'

        ## dart: PermissionGroup.appTrackingTransparency
        # 'PERMISSION_APP_TRACKING_TRANSPARENCY=0'
      ]

    end
  end
end
```

**Comment by gjrjf** [comment] 2022-09-18 07:10
I also faced the same problem.
Failing to update app

**Comment by armandojimenez** [comment] 2022-09-27 15:59
> I also faced the same problem. Failing to update app

Did you find a solution?

**Comment by armandojimenez** [comment] 2022-09-30 11:09
Can someone help me with this? My app was just rejected again because they said I use the app tracking transparency API, but I don’t. Please I need help with this. My pod file has this commented.

**Comment by armandojimenez** [comment] 2022-10-01 04:11
I just forked this repo and removed all code having to do with App Tracking and it worked... So there is a problem with how this package handles the comments in the podfile. Please verify this!

**Comment by cs-hyunseo** [comment] 2022-10-04 07:26
Still no solution for this?

**Comment by ishakdas** [comment] 2023-01-27 21:35
@cs-hyunseo @armandojimenez  @gjrjf  
remove 
## dart: PermissionGroup.appTrackingTransparency
        # 'PERMISSION_APP_TRACKING_TRANSPARENCY=0'

**Comment by armandojimenez** [comment] 2023-05-08 18:20
Still no solution to this? does not work with or without commenting. My app just failed a review because they say I am using the App Tracking permission

**Comment by alexobviously** [comment] 2023-06-21 09:27
We also started getting this problem, apparently apple's static analysis found camera related code and they want `NSCameraUsageDescription`, but we don't use the camera at all.

**Comment by mvanbeusekom** [comment] 2023-09-14 13:26
It is very difficult for us to debug this issue since it only occurs while uploading/ publishing the application to the Apple App Store. 

I did create a simple test application copying the `Podfile` configuration mentioned in this issue and uploaded it to the App Store without any problems. The steps I took to try and reproduce the error were:

1. Create a new Flutter application: `flutter create --platforms ios --empty permission_tester`
2. Navigate to the root of the new application: `cd permission_tester`
3. Add a dependency on the permission_handler: `flutter pub add permission_handler`
4. Download dependencies: `flutter pub get`
5. Add configuration to `ios/Podfile` (see code snippet below)
6. Add configuration to `ios/Runner/Info.plist` (see code snippet below)
7. Build a release: `flutter build ipa`
8. Login to [Apple App Store Connect](https://appstoreconnect.apple.com/) and create new iOS application.
9. Upload the generated `build/ios/ipa/permission_tester.ipa` file to App Store using `xcrun` or the [Transporter](https://apps.apple.com/us/app/transporter/id1450874784) tool.
10. Upload was successful, received an email that the build was ready to use in TestFlight.

<details>
<summary> Podfile </summary>

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|    
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
        # 'PERMISSION_EVENTS=0',

        ## dart: PermissionGroup.reminders
        # 'PERMISSION_REMINDERS=0',

        ## dart: PermissionGroup.contacts
        # 'PERMISSION_CONTACTS=0',

        ## dart: PermissionGroup.camera
        'PERMISSION_CAMERA=1',

        ## dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=1',

        ## dart: PermissionGroup.speech
        # 'PERMISSION_SPEECH_RECOGNIZER=0',

        ## dart: PermissionGroup.photos
        'PERMISSION_PHOTOS=1',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        # 'PERMISSION_LOCATION=0',
       
        ## dart: PermissionGroup.notification
        'PERMISSION_NOTIFICATIONS=1',

        ## dart: PermissionGroup.mediaLibrary
        'PERMISSION_MEDIA_LIBRARY=1',

        ## dart: PermissionGroup.sensors
        # 'PERMISSION_SENSORS=0',   
        
        ## dart: PermissionGroup.bluetooth
        # 'PERMISSION_BLUETOOTH=0'

        ## dart: PermissionGroup.appTrackingTransparency
        # 'PERMISSION_APP_TRACKING_TRANSPARENCY=0'
      ]

    end
  end
end

```
</details>

<details>
<summary> Info.plist </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Permission Tester</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>permission_tester</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>

    <!-- Permission options for the `mediaLibrary` group -->
    <key>NSAppleMusicUsageDescription</key>
    <string>Music!</string>
    <key>kTCCServiceMediaLibrary</key>
    <string>media</string>

    <!-- Permission options for the `camera` group -->
    <key>NSCameraUsageDescription</key>
    <string>camera</string>

    <!-- Permission options for the `microphone` group -->
    <key>NSMicrophoneUsageDescription</key>
    <string>microphone</string>

    <!-- Permission options for the `photos` group -->
    <key>NSPhotoLibraryUsageDescription</key>
    <string>photos</string>

</dict>
</plist>
```

</details>

I will close this issue for now as the plugin seems to be working as expected. If this issue still remains and you'd want us to have a look, please provide a sample application we can use to reproduce the problem.

**Closed by mvanbeusekom** 2023-09-14 13:26 UTC
Labels: platform: ios, type: bug, P2
