### ISSUE TITLE
when I compileSdkVersion set it to 30. error video_player

### ISSUE THREAD

**Issue by mahdimoaz** [Baseflow/flutter-permission-handler#628] opened 2021-07-19 06:40 UTC
## 💬 Questions and Help

When to fix the problem :permission_handler:compileDebugJavaWithJavac 
I will change compileSdkVersion set it to 30.

This error is displayed :video_player:compileDebugJavaWithJavac Because it wants compileSdkVersion 29

**Comment by mvanbeusekom** [comment] 2021-07-19 07:22
@mahdimoaz which version of the `video_player` plugin are you using? 

I created a test application to try and reproduce the issue and I had no problems. Here are the steps I took:

1. Create a new Flutter application: `flutter create permission_issue_628`
2. Edit the `pubspec.yaml` file and add the following dependencies:
  - `permission_handler: ^8.1.3`;
  - `video_player: ^2.1.10`
3. Check `compileSdkVersion` in `android/app/build.gradle` file (in my case this was already set to 30, since this is done automatically by latest Flutter version).
4. Compile the App for Android: `flutter build appbundle`

Here some additional information:

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/maurits/fvm/versions/stable
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/maurits/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/maurits/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • M2003J15SC (mobile) • 106fdad20410                         • android-arm64  • Android 11 (API 30)
    • iPhone 12 (mobile)  • C6D66ADF-ABAB-4A3E-9101-D0E460AF4A80 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)        • chrome                               • web-javascript • Google Chrome 91.0.4472.164
```
</details>

<details>
<summary>pubspec.yaml</summary>

```yaml
name: permission_issue_628
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  video_player: ^2.1.10
  permission_handler: ^8.1.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

```
</details>

<details>
<summary>build.gradle</summary>

```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.permission_issue_628"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

```
</details>

If you really want to stay stuck on `compileSdkVersion=29` you can switch to permission_handler version 6.1.3. If you want more help please provide more information.

**Comment by mahdimoaz** [comment] 2021-07-19 08:06
`pubspec.yaml:`
 
```
permission_handler: ^8.1.3
wakelock: ^0.5.2
chewie: ^1.2.2
```
`flutter doctor -v`
```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-UG)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at E:\sdk\sdk\sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = E:\sdk\sdk\sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_51\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (4 available)
    • M2004J19C (mobile) • 8548e4300406 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)  • windows      • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)       • chrome       • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)         • edge         • web-javascript • Microsoft Edge 91.0.864.70

! Doctor found issues in 2 categories.
```

This message will be displayed when Im runnig the app

> Note: C:\Users\mahdi\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_sound_lite-8.2.0\android\src\main\java\com\dooboolab\fluttersound\FlutterSound.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\Users\mahdi\.gradle\caches\transforms-2\files-2.1\4463bcbc5ae456f29f96037cbbd4575a\jetified-exoplayer-common-2.14.1-api.jar(com/google/android/exoplayer2/util/Util.class): warning: Cannot find annotation method 'value()' in type 'EnsuresNonNull': class file for org.checkerframework.checker.nullness.qual.EnsuresNonNull not found
C:\Users\Sabbaghzadeh\.gradle\caches\transforms-2\files-2.1\4463bcbc5ae456f29f96037cbbd4575a\jetified-exoplayer-common-2.14.1-api.jar(com/google/android/exoplayer2/util/Util.class): warning: Cannot find annotation method 'value()' in type 'EnsuresNonNull'
error: warnings found and -Werror specified
1 error
2 warnings

> FAILURE: Build failed with an exception.

> * What went wrong:

> Execution failed for task ':video_player:compileDebugJavaWithJavac'.
Compilation failed; see the compiler error output for details.

**Comment by mvanbeusekom** [comment] 2021-07-19 08:27
@mahdimoaz this error seems to be caused by some warnings according to this line: `error: warnings found and -Werror specified`

You application won't compile because you have listed the `-Werror` switch which treats warnings as errors. There are a few things you can do:

1. Wait for the video_player and chewie to get updated;
2. Downgrade to version 6.1.3 of the permission_handler and use Android `complileSdkVersion: 29`;
3. Remove the `-Werror` switch in your `android/build.gradle` file and don't treat warnings as errors.

Which one of the above options you choose is completely up to you. Of course you can also pick a combination (like temporarily remove the `-Werror` switch until `chewie` and `video_player` are updated).

I am going to close this issue as there is nothing I can do. If you have additional questions please don't hesitate to leave a comment.

**Closed by mvanbeusekom** 2021-07-19 08:27 UTC
Labels: platform: android

**Comment by mahdimoaz** [comment] 2021-07-19 09:03
@mvanbeusekom thanks for the help
