### ISSUE TITLE
version8.1.2 in native no callback  --Android

### ISSUE THREAD

**Issue by bxxasn** [Baseflow/flutter-permission-handler#615] opened 2021-07-08 09:48 UTC
## 🐛 Bug Report

It can run in the flutter environment alone.
However, integrating the flutter project into the native project will lead to the problem of no permission callback

### Expected behavior
       void requestCameraPermission(int type) async {
        await Permission.camera.request();
        if (await Permission.camera.request().isGranted) {
          // **permiession is allow**
          //   but no call
        }else{
          // **permiession is not allow**
          //   but no call
        }
       
  }
### Reproduction steps
    requrest permission>>>android.permission.CAMERA
    debug state
    in class PermissionManager 
    ActivityCompat.requestPermissions()    method  is call 
    PermissionManager.onRequestPermissionsResult()  mehod is not call 

### Configuration

**Version:** 8.1.2

**Platform:** 
- [ V] :robot: Android

sorry english is not great

**Comment by blaueeiner** [comment] 2021-07-10 15:59
[v8.0.0](https://pub.dev/packages/permission_handler/changelog) introduced a breaking change for the iOS configuration on which pemissions you want to use.

The changelog says the following:

> Starting from this version the permissions on iOS are disabled by default. To enable a permission, specify the correct GCC_PREPROCESSOR_DEFINITIONS in the ios/Podfile file. For an example check out the [Podfile](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/example/ios/Podfile) of the example application.

Maybe this is the issue and can help you. Has been mine :)

**Comment by bxxasn** [comment] 2021-07-12 11:36
but system is android
 no ios

**Comment by bxxasn** [comment] 2021-07-12 11:40
> [v8.0.0](https://pub.dev/packages/permission_handler/changelog) introduced a breaking change for the iOS configuration on which pemissions you want to use.
> 
> The changelog says the following:
> 
> > Starting from this version the permissions on iOS are disabled by default. To enable a permission, specify the correct GCC_PREPROCESSOR_DEFINITIONS in the ios/Podfile file. For an example check out the [Podfile](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/example/ios/Podfile) of the example application.
> 
> Maybe this is the issue and can help you. Has been mine :)

==============================
but system is android (not ios)

**Comment by JDDV** [comment] 2021-07-15 11:10
Hi @bxxasn, I'm not entirely sure about what the issue is. What seems to go wrong for you?
The code snippet in the expected behavior section of your message works fine for me.

I reproduced your issue by doing the following:

1. Created a new project and used the code from the 'Expected behavior' from your comment in the bug report.
2. Added print statements so I could see in which of the if/else code it would end in
2. Added the Permission handler plugin version ^8.1.2.
3. Set breakpoints in both the onRequestPermissionsResult and requestPermissions()
4. Debug the code

The result were as following: 

The permission got asked twice (since the code snippet will ask for the permission on the first line `await Permission.camera.request();` and also in the if statement you request permission `if (await Permission.camera.request().isGranted)`.

When you request the permission, then the `requestPermissions()` method gets called and will request the permission to the android system (showing you the pop-up to allow/deny the permission) by using the ActivityCompat.requestPermissions. When the user allows or denies the permission, then the `onRequestPermissionsResult()` will be called automatically since it's the callback function for the result from requesting the permission.

Can you please check if the prints in the code get executed using this code snippet?:

```
    if (await Permission.camera.request().isGranted) {
      // **permission is allowed**
      //   but no call
      print("ALLOWED");
    }else{
      // **permission is not allowed**
      //   but no call
      print("NOT ALLOWED");
    }
```
If I allow the permission the if-statement gets executed, printing `ALLOWED`. if I deny the permission the else-statement gets executed, printing `NOT ALLOWED`. This means that the plugin works as it should. Can you test if it does the same for you?

Let me know the result so we can figure out if it works as it's supposed to work so we can close this issue. If it still does not work for you, can you send me a clearer description of the problem, a `flutter doctor -v` result, and the device + API level you tested this on?

**Closed** 2021-07-29 11:53 UTC
Labels: platform: android, status: needs more info, status: waiting for customer response
