### ISSUE TITLE
[Bug]: Permission.locationAlways.request() doesn't work on IOS

### ISSUE THREAD

**Issue by Ellynnn** [Baseflow/flutter-permission-handler#1210] opened 2023-11-06 08:45 UTC
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

Check if `Permission.locationWhenInUse.isDenied`, if yes then request with `Permission.locationWhenInUse.request()`. If `Permission.locationWhenInUse.isGranted` then request for locationAlways with `Permission.locationAlways.request()`

### Expected results

Bring user to app location setting page to Allow Location always just like in Android

### Actual results

Nothing happened. Directly returned me with a PermissionStatus.permanentlyDenied

### Code sample

<details><summary>Code sample</summary>

```dart
if (await Permission.locationWhenInUse.isDenied) {
    await Permission.locationWhenInUse.request();
    if (await Permission.locationWhenInUse.isGranted) {
     await Permission.locationAlways.request();
      if (await Permission.locationAlways.isDenied) {
        return false;
      }
    }
  }
```

</details>

### Version

11.0.1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
```

</details>

**Comment by TimHoogstrate** [comment] 2023-11-06 12:44
Dear @Ellynnn,

I have tested this with the provided example app but it seems to work as expected. What I don't fully understand is why: `Bring user to app location setting page` should happen. I see a pop-up asking the "always" permission.

Kind regards,

**Comment by LeonP2ER** [comment] 2023-11-06 13:30
I have the same problem as @Ellynnn here. Does not work for me on an iPhone with iOS 17.0.3.

**Comment by LeonP2ER** [comment] 2023-11-06 13:44
Seems to be related to / duplicate of #1152.

**Comment by TimHoogstrate** [comment] 2023-11-06 15:35
Dear @LeonP2ER,

Can you create a new issue with all the required information like `flutter doctor -v` and steps to reproduce. Please try the example app to see if it is happening there. It seems to works in the example app with iOS 17.1 with the steps to reproduce.

Kind regards,

**Comment by LeonP2ER** [comment] 2023-11-06 16:10
@TimHoogstrate I created https://github.com/Baseflow/flutter-permission-handler/issues/1211 :)

**Comment by Ellynnn** [comment] 2023-11-07 01:22
I revised the code to as below and attached is a screen recording of the behavior

```
const rcLocationPermissionRestricted =
    'This application requires location permission\n\nPlease allow location permission in Settings';
const rcBackgroundLocationPermission =
    'This application requires access to location updates in the background\n\nWhen prompted, please select "Allow all the time"';
const rcLocationPermissionPermanentlyDenied =
    'This application requires access to location to get clocking location and location update in background\n\n'
    'In the App Info page:\n\n'
    '*Tap "Permission"*\n*Tap "Location"*\n*Select "Allow all the time"* then return to the app';

Future<bool> requestLocationPermission() async {
  if (await Permission.locationWhenInUse.isDenied) {
    await showMessage(rcLocationPermissionRestricted);
    await Permission.locationWhenInUse.request();
  }

  if (await Permission.locationWhenInUse.isGranted &&
      await Permission.locationAlways.isDenied) {
    await showMessage(rcBackgroundLocationPermission);
    await Permission.locationAlways.request();
    if (await Permission.locationAlways.isDenied) {
      return false;
    }
  }

  // if location permission is permanently denied
  if (await Permission.locationWhenInUse.isPermanentlyDenied) {
    await showMessage(rcLocationPermissionPermanentlyDenied);
    await openAppSettings();
  }

  return true;
}
```

https://github.com/Baseflow/flutter-permission-handler/assets/45744236/541a82f7-658b-49dd-9009-82afbcee09d1

**Closed** 2023-11-21 10:11 UTC
Labels: platform: ios, status: needs more info, status: closed (missing info)
