### ISSUE TITLE
Permission.storage.request() not working on android 13 (SDK 33)

### ISSUE THREAD

**Issue by menezes85** [Baseflow/flutter-permission-handler#995] opened 2023-02-13 21:36 UTC
## 🐛 Bug Report

Permission.storage.request() not working on android 13 (SDK 33)

**Platform:** 
- [x ] :robot: Android

**Comment by brunovsiqueira** [comment] 2023-02-14 16:44
Any updates on this? Affecting several production users.

**Comment by NitiLTechscape** [comment] 2023-02-15 04:33
same issue. Is there a workaround?

**Comment by pye52** [comment] 2023-02-15 05:29
[give a try](https://github.com/Baseflow/flutter-permission-handler/issues/907#issuecomment-1375999027). it works fine for me

**Comment by humzakt** [comment] 2023-02-15 14:01
A temp workaround is to downgrade your targetSdkVersion to 32, while keeping compileSdkVersion on 33 to cater for firebase requirements.

**Comment by AliEasy** [comment] 2023-02-16 07:42
same issue here

**Comment by NitiLTechscape** [comment] 2023-02-20 02:30
> same issue here

try @humzakt workaround it works for me

**Comment by kyi87** [comment] 2023-02-28 18:37
I have the same Problem. I also tried the workaround from humzakt, but its not working for me.
Nothing happens, i dont see any Request Dialog...

I do this in my main.dart file:

```
void main() async {
....
    var isDenied = await Permission.notification.isDenied;
    if (isDenied) {
      var status = await Permission.notification.request();
    }
  runApp(const MyApp());
}
```

Which version of the permission handler do you use?

**Comment by WMOH-DEV** [comment] 2023-03-01 02:35
i added this to `AndroidManifest.xml`
`    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />`
uninstalled the app from the emulator
run it again  

it worked for me

**Comment by WMOH-DEV** [comment] 2023-03-01 02:36
I had the same issue with the notifications 

i added this to AndroidManifest.xml
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
uninstalled the app from the emulator
run it again

it worked for me

**Comment by chirag-chopra** [comment] 2023-03-03 13:45
Facing same issue. Please help!!

**Comment by AliPunjabi** [comment] 2023-03-15 10:54
still facing the same issue, trying to store pdf file using external storage but getting rejected by playstore

**Comment by Marco4763** [comment] 2023-03-20 11:02
Hello guys, if you're still facing this problem, i just wanted to let you guys know that in SDK 33, there is no need to request for the storage permission as the app will had the access to the files by default.

But if you guys need to access a file generated by other apps, I suggest using Permission.photos, Permission.videos or Permission.audio because this permissions work with Granular Media Permissions, you can read more about that in this [article](https://medium.com/@marcoedomingos/flutter-storage-access-for-android-sdk-33-d19e2b693017)

**Comment by RobertQuayle** [comment] 2023-03-24 12:35
> Hello guys, if you're still facing this problem, i just wanted to let you guys know that in SDK 33, there is no need to request for the storage permission as the app will had the access to the files by default.
> 
> But if you guys need to access a file generated by other apps, I suggest using Permission.photos, Permission.videos or Permission.audio because this permissions work with Granular Media Permissions, like this: `Future<void> _getStoragePermission() async {` `DeviceInfoPlugin plugin = DeviceInfoPlugin();` `AndroidDeviceInfo android = await plugin.androidInfo;` `if (android.version.sdkInt < 33) {` `if (await Permission.storage.request().isGranted) {` `setState(() {` `permissionGranted = true;` `});` `} else if (await Permission.storage.request().isPermanentlyDenied) {` `await openAppSettings();` `} else if (await Permission.audio.request().isDenied) {` `setState(() {` `permissionGranted = false;` `});` `}` `} else {` `if (await Permission.photos.request().isGranted) {` `setState(() {` `permissionGranted = true;` `});` `} else if (await Permission.photos.request().isPermanentlyDenied) {` `await openAppSettings();` `} else if (await Permission.photos.request().isDenied) {` `setState(() {` `permissionGranted = false;` `});` `}` `}` `}`
> 
> You can read more about that in this [article](https://medium.com/@marcoedomingos/flutter-storage-access-for-android-sdk-33-d19e2b693017)

Facing same issue, this worked for me.

**Comment by RobertQuayle** [comment] 2023-03-24 12:37
Facing same issue, @Marco4763 solution worked for me

**Comment by Marco4763** [comment] 2023-03-30 15:21
@RobertQuayle did you try to select the file without asking the for storage permission, just like i metioned before, Tiramsu has permission to the Storage by default.

**Comment by PrasadDhend** [comment] 2023-04-04 08:29
### **_Adding the below lines of code worked for me!_**

**android/app/src/main/AndroidManifest.xml**

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`
`<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>`



**### Take a permission using below code**

`final status = await Permission.manageExternalStorage.request();`
`     if (status.isDenied ||`
`        status.isPermanentlyDenied ||`
`       status.isRestricted) {`
`    throw "Please allow storage permission to upload files";`
` }`

**Comment by alperefesahin** [comment] 2023-04-20 23:39
@PrasadDhend what about the iOS side?

**Comment by mahdibagjani** [comment] 2023-05-03 09:04
> ### **_Adding the below lines of code worked for me!_**
> **android/app/src/main/AndroidManifest.xml**
> 
> `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>` `<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>` `<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>`
> 
> **### Take a permission using below code**
> 
> `final status = await Permission.manageExternalStorage.request();` ` if (status.isDenied ||` ` status.isPermanentlyDenied ||` ` status.isRestricted) {` ` throw "Please allow storage permission to upload files";` ` }`

It's work for me

**Comment by julianfalcionelli** [comment] 2023-06-07 18:36
> ### **_Adding the below lines of code worked for me!_**
> **android/app/src/main/AndroidManifest.xml**
> 
> `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>` `<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>` `<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>`
> 
> **### Take a permission using below code**
> 
> `final status = await Permission.manageExternalStorage.request();` ` if (status.isDenied ||` ` status.isPermanentlyDenied ||` ` status.isRestricted) {` ` throw "Please allow storage permission to upload files";` ` }`

Be careful, this approach may not work for everyone, due to PlayStore Policies the manageExternalStorage permission is limited to specific usages.

**Comment by johnkeygithub** [comment] 2023-06-25 08:46
same issue

**Comment by JeroenWeener** [comment] 2023-06-29 10:25
Duplicate of #955, and related to #1026, #1066.

**Closed** 2023-06-29 10:25 UTC
Labels: good first issue, platform: android

**Comment by syedwaleednawaz000** [comment] 2023-08-03 06:49
Please dont waste time 
i share update code you peoples
  List<File> selectedImages = []; // List to store selected images

  Future<void> pickImages({required int photoCounter}) async {
    List<XFile>? pickedFiles = await ImagePicker().pickMultiImage();
    if (pickedFiles != null && pickedFiles.isNotEmpty) {
      if (pickedFiles.length < 3) {
        AppConstant.flutterToastError(responseMessage: "Please upload minimum 3 images");
      } else {
        if(pickedFiles.length < photoCounter){
          selectedImages.clear();
          for (XFile pickedFile in pickedFiles) {
            File image = File(pickedFile.path);
            selectedImages.add(image);
          }
        }else{
          AppConstant.flutterToastError(responseMessage: "You have upload up to ${photoCounter.toString()} images");
        }
        update();
      }
    } else {
    }
  }

**Comment by Mariluk** [comment] 2024-06-26 12:42
> ### **_Adding the below lines of code worked for me!_**
> **android/app/src/main/AndroidManifest.xml**
> 
> `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>` `<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>` `<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>`
> 
> **### Take a permission using below code**
> 
> `final status = await Permission.manageExternalStorage.request();` ` if (status.isDenied ||` ` status.isPermanentlyDenied ||` ` status.isRestricted) {` ` throw "Please allow storage permission to upload files";` ` }`

Good luck with the release on Google Play :))))

**Comment by JuYiYang** [comment] 2024-06-27 03:05
final DeviceInfoPlugin deviceInfoPlugin = DeviceInfoPlugin();

    if (Platform.isAndroid) {
      var androidInfo = await deviceInfoPlugin.androidInfo;
      int androidVersion = int.parse(androidInfo.version.release);
      PermissionStatus status;
      if (androidVersion >= 13) {
        status = await Permission.photos.status;
        if (status.isDenied) {
          print('request');
          status = await Permission.photos.request();
        }
      } else {
        status = await Permission.storage.status;

        if (status.isDenied) {
          status = await Permission.storage.request();
        }
      }
      if (!status.isGranted) {
        OtherUtils.showToastError('User denied access request!');
        return;
      }
      _pickImage(status.isGranted);
    }

**Comment by JuYiYang** [comment] 2024-06-27 03:06
`  Future<void> _checkPermissionAndPickImage() async {
    final DeviceInfoPlugin deviceInfoPlugin = DeviceInfoPlugin();

    if (Platform.isAndroid) {
      var androidInfo = await deviceInfoPlugin.androidInfo;
      int androidVersion = int.parse(androidInfo.version.release);
      PermissionStatus status;
      if (androidVersion >= 13) {
        status = await Permission.photos.status;
        if (status.isDenied) {
          print('request');
          status = await Permission.photos.request();
        }
      } else {
        status = await Permission.storage.status;

        if (status.isDenied) {
          status = await Permission.storage.request();
        }
      }
      if (!status.isGranted) {
        print(' denied ');
        return;
      }
      // next()
    }
  }`

**Comment by JuYiYang** [comment] 2024-06-27 03:07
`  
Future<void> _checkPermissionAndPickImage() async {
    final DeviceInfoPlugin deviceInfoPlugin = DeviceInfoPlugin();

    if (Platform.isAndroid) {
      var androidInfo = await deviceInfoPlugin.androidInfo;
      int androidVersion = int.parse(androidInfo.version.release);
      PermissionStatus status;
      if (androidVersion >= 13) {
        status = await Permission.photos.status;
        if (status.isDenied) {
          print('request');
          status = await Permission.photos.request();
        }
      } else {
        status = await Permission.storage.status;

        if (status.isDenied) {
          status = await Permission.storage.request();
        }
      }
      if (!status.isGranted) {
        print(' denied ');
        return;
      }
      // next()
    }
  }
`
