### ISSUE TITLE
permanentlyDenied not work

### ISSUE THREAD

**Issue by robertoalvesneto** [Baseflow/flutter-permission-handler#840] opened 2022-05-04 20:50 UTC
## 🐛 Bug Report

When i press on "deny and do not ask again" the expected output is "permanentlyDenied", but i receive "Denied":

**Test code:**
```
    ph.PermissionStatus status = await ph.Permission.camera.status;
    print(status);
    print(status.isPermanentlyDenied);
```

**Output:**
```
I/flutter (25557): PermissionStatus.denied
I/flutter (25557): false
```

**Expected Output:**
```
I/flutter (25557): PermissionStatus.permanentlyDenied
I/flutter (25557): true
```

**Version:** 9.2.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by MarcMolitorAtDermalog** [comment] 2022-05-17 10:18
When clicking next to permission dialog (atleast for camera, Google Pixel 4, Android 12) the result is permanentlyDenied. Would expect Denied for this event.
Maybe the negation in PermissionUtiles.java::L367 (return !shouldShowRequestPermissionRationale) is the reason for my issue as well as yours.

**Comment by ProerMo** [comment] 2022-06-09 08:34
it's work like this
`bool isPermissionGranted = await Permission.camera.isGranted;

                var shouldShowRequestRationale =
                    await Permission.camera.shouldShowRequestRationale;

                if (isPermissionGranted) {
                  updateResult("isGranted:true");
                  SmartDialog.showToast('isGranted:true');
                } else {
                  if (!shouldShowRequestRationale) {
                    var permissionStatus = await Permission.camera.request();
                    if (permissionStatus.isPermanentlyDenied) {
                      openAppSettings();
                    }
                  } else {
                    var permissionStatus = await Permission.camera.request();
                    if (permissionStatus.isGranted) {
                      updateResult("isGranted:true");
                      SmartDialog.showToast('isGranted:true');
                    } else {
                      SmartDialog.showToast('isGranted:false');
                    }
                  }
                }`

**Comment by quiquegarcia** [comment] 2022-06-15 19:23
> 

I think this is more a hack than functionality maybe? I mean, isPermanentlyDenied must handle all this logic, I think

**Comment by quiquegarcia** [comment] 2022-06-15 19:24
> ## 🐛 Bug Report
> 
> When i press on "deny and do not ask again" the expected output is "permanentlyDenied", but i receive "Denied":
> 
> **Test code:**
> 
> ```
>     ph.PermissionStatus status = await ph.Permission.camera.status;
>     print(status);
>     print(status.isPermanentlyDenied);
> ```
> 
> **Output:**
> 
> ```
> I/flutter (25557): PermissionStatus.denied
> I/flutter (25557): false
> ```
> 
> **Expected Output:**
> 
> ```
> I/flutter (25557): PermissionStatus.permanentlyDenied
> I/flutter (25557): true
> ```
> 
> **Version:** 9.2.0
> 
> **Platform:**
> 
>     * [ ]  📱 iOS
> 
>     * [x]  🤖 Android

Confirmed

**Comment by mvanbeusekom** [comment] 2022-06-21 11:51
@quiquegarcia unfortunately the Android API doesn't allow developers (including us) to distinguish if permissions are simply denied or if they have been permanently denied. 

The Android API offers the `ContextCompat.checkSelfPermission()` (see [Android documentation](https://developer.android.com/reference/androidx/core/content/ContextCompat#checkSelfPermission(android.content.Context,%20java.lang.String))) which only returns `GRANTED` or `DENIED`. This means we are unable to reliably determine if permissions are simply denied but we can ask again, or if they are permanently denied and we should not ask again. This is also explained in more detail on our [Wiki](https://github.com/Baseflow/flutter-permission-handler/wiki/Changes-in-6.0.0). The [Wiki](https://github.com/Baseflow/flutter-permission-handler/wiki/Changes-in-6.0.00) also provides a suggestion on how to best handle this.

Unfortunately we are bound to the APIs provided to us by the native platforms, therefore I will be closing this issue.

**Closed by mvanbeusekom** 2022-06-21 11:51 UTC
