### ISSUE TITLE
add null-safety support

### ISSUE THREAD

**Issue by chavesgu** [Baseflow/flutter-permission-handler#466] opened 2021-03-04 06:08 UTC
## 🚀 Feature Requests

add null-safety support
### Describe the feature

Flutter stable version is `2.0.0`, support null-safety
### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by amebrahimi** [comment] 2021-03-04 07:49
Please add null safety !!!

**Comment by mvanbeusekom** [comment] 2021-03-04 08:04
duplicate of #419. 

we are currently testing the migration and should be released soon. See also #450 and #451

**Closed by mvanbeusekom** 2021-03-04 08:04 UTC
