### ISSUE TITLE
Do not ask the storage permission in android version 13 and above?

### ISSUE THREAD

**Issue by Talha137m** [Baseflow/flutter-permission-handler#1066] opened 2023-06-12 13:20 UTC
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by AtzeniMichele** [comment] 2023-06-12 15:15
I have the same issue

**Comment by JeroenWeener** [comment] 2023-06-13 14:39
Hi @Talha137m, thank you opening an issue for `flutter-permission-handler`.

To effectively tackle issues, we require information on what exactly is actual/expected behavior, reproduction steps and some description so we know what we are dealing with.

It was unclear to me from your report what it is you are experiencing.

My assumption is as follows:
You are using the latest version of the permission handler and your application asks the user for storage permissions. You expect the system to request the user for permission, but the dialog does not show. Instead, nothing happens. You have tested the behavior on both Android and iOS and it is present on both platforms.

Please let me know if this assumption is correct so people can start digging into the issue.

**Comment by lexoops** [comment] 2023-06-17 08:13
same problem

**Comment by rudroanik** [comment] 2023-06-21 06:46
I also face same issue in android 13. In android 13 I am not getting permission request

**Comment by Avi067** [comment] 2023-06-22 07:55
I had same issue , but I resolved it by increasing the targetSdkVersion to 31 to 33.

**Comment by Talha137m** [comment] 2023-06-23 01:29
Yes your assumption is right 👍

**Comment by rhasnat191** [comment] 2023-06-23 11:44
:/ Having the same issue

**Comment by cauapedrosa** [comment] 2023-06-23 19:53
Having the same issue here. 
Calls to `Permission.storage.request()` and `Permission.manageExternalStorage.request()` work as intended in APIs 29 and 30, but in 33 it simply fails without even prompting the user to allow or deny the permission. Any ideas?

**Comment by rudroanik** [comment] 2023-06-26 04:30
If you use targetSdk version 33 then use following code.

```
 bool permissionStatus;
 final deviceInfo =await DeviceInfoPlugin().androidInfo;

 if(deviceInfo.version.sdkInt>32){
      permissionStatus = await Permission.photos.request().isGranted;
    }else{
      permissionStatus = await Permission.storage.request().isGranted;

    }
```
use this permission manifest file

```
 <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
 <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
```

**Comment by GokulakrishnanV** [comment] 2023-06-27 12:51
> If you use targetSdk version 33 then use following code.
> 
> ```
>  bool permissionStatus;
>  final deviceInfo =await DeviceInfoPlugin().androidInfo;
> 
>  if(deviceInfo.version.sdkInt>32){
>       permissionStatus = await Permission.photos.request().isGranted;
>     }else{
>       permissionStatus = await Permission.storage.request().isGranted;
> 
>     }
> ```
> 
> use this permission manifest file
> 
> ```
>  <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
>  <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
> ```
> 
> It's work for me. & It's exact solution.

how to request permission for files ?

**Comment by rudroanik** [comment] 2023-06-27 14:52
> > If you use targetSdk version 33 then use following code.
> > ```
> >  bool permissionStatus;
> >  final deviceInfo =await DeviceInfoPlugin().androidInfo;
> > 
> >  if(deviceInfo.version.sdkInt>32){
> >       permissionStatus = await Permission.photos.request().isGranted;
> >     }else{
> >       permissionStatus = await Permission.storage.request().isGranted;
> > 
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > use this permission manifest file
> > ```
> >  <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
> >  <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It's work for me. & It's exact solution.
> 
> how to request permission for files ?

Using this permission you also request for files.No need extra permission in Android 13

**Comment by JeroenWeener** [comment] 2023-06-29 10:14
Possible duplicate of #955

**Comment by JeroenWeener** [comment] 2023-06-30 10:22
I found the likely culprit. Both `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` permissions have been deprecated in Android 13.

```
READ_EXTERNAL_STORAGE is deprecated (and is not granted) when targeting Android 13+. If you need to query or interact with MediaStore or media files on the shared storage, you should instead use one or more new storage permissions: READ_MEDIA_IMAGES, READ_MEDIA_VIDEO or READ_MEDIA_AUDIO.
```

```
WRITE_EXTERNAL_STORAGE is deprecated (and is not granted) when targeting Android 13+. If you need to write to shared storage, use the MediaStore.createWriteRequest intent.
```

**Comment by JeroenWeener** [comment] 2023-06-30 10:24
By now I am pretty sure this is a duplicate of #955. Therefore, I am going to close this issue. To track progress on this particular bug, please see #955.

**Closed by JeroenWeener** 2023-06-30 10:24 UTC
Labels: good first issue, platform: android, type: bug
