### ISSUE TITLE
[Bug]: ths bug happened on iOS 16.5

### ISSUE THREAD

**Issue by iOSluozhiping** [Baseflow/flutter-permission-handler#1106] opened 2023-07-14 06:36 UTC
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

 // 申请权限
    Map<Permission, PermissionStatus> statuses = await [
      Permission.camera,
    ].request();

    _isGranted = statuses[Permission.camera]?.isGranted ?? false;

    if ((statuses[Permission.camera]?.isGranted ?? false)) {
      showConfirmDialog();
    } else {
      SmartDialog.showToast("获取权限失败，无法视频认证");
    }

### Expected results

Permission.camera success!

### Actual results

[Subscriber] Error getting user auth token: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"

### Code sample

 // 申请权限
    Map<Permission, PermissionStatus> statuses = await [
      Permission.camera,
    ].request();

    _isGranted = statuses[Permission.camera]?.isGranted ?? false;

    if ((statuses[Permission.camera]?.isGranted ?? false)) {
      showConfirmDialog();
    } else {
      SmartDialog.showToast("获取权限失败，无法视频认证");
    }

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

iOS 16.5

### Flutter Doctor output

(base) luozhiping@bogon ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.6, on macOS 13.4.1 22F82 darwin-x64, locale
    zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.41.1)
[✓] VS Code (version 1.74.2)
[✓] Connected device (3 available)
HTTP Host availability check is taking a long time...⣽

**Comment by mvanbeusekom** [comment] 2023-07-14 07:24
Hi @iOSluozhiping, 

Thank you for taking the time to fill in the complete form and submitting the issue. I feel however that the error mentioned is not related to requesting camera permissions. 

The error domain "NSPOSIXErrorDomain" is related to network requests. From the look of the error description, the application is doing a network request which requires a missing authentication token.

The permission_handler plugin doesn't make any network requests and therefore it is highly unlikely this error is a result of using the permission_handler. 

I am going ahead and close this issue. If you feel this is incorrect and the problem is caused by the permission_handler plugin, feel free to leave a reply and attach a small application reproducing the error.

**Closed by mvanbeusekom** 2023-07-14 07:24 UTC
