### ISSUE TITLE
Storage permission dined in Android

### ISSUE THREAD

**Issue by blue492** [Baseflow/flutter-permission-handler#972] opened 2023-01-03 08:26 UTC
My app have a problem with STORAGE permission in `Android version: 13`, it returns false always and don't show allow permission popup when I use the following line:
`await Permission.storage.request().isGranted`

`permission_handler: ^10.2.0`
`Flutter version: 3.3.10`

My permissions in AndroidManifest.xml are here:
```
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" tools:node="remove" />
   
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>
        <intent>
            <action android:name="android.intent.action.DIAL" />
            <data android:scheme="tel" />
        </intent>
        <intent>
            <action android:name="android.intent.action.SEND" />
            <data android:mimeType="*/*" />
        </intent>
    </queries>
```

**Comment by Reketaka** [comment] 2023-01-04 15:46
i have same problem with same versions

**Comment by astubenbord** [comment] 2023-01-06 12:21
This is most likely related to https://github.com/Baseflow/flutter-permission-handler/issues/907

**Comment by Artico77** [comment] 2023-02-09 17:04
exact same error here with **targetSdkVersion** **33**.

**Comment by okbye123** [comment] 2023-03-17 12:26
This might help https://www.youtube.com/watch?v=uMvGpBOT0ZY

**Comment by Marco4763** [comment] 2023-03-20 11:08
Hello guys, if you're still facing this problem, i just wanted to let you guys know that in SDK 33, there is no need to request for the storage permission as the app will had the access to the files by default.

But if you guys need to access a file generated by other apps, I suggest using Permission.photos, Permission.videos or Permission.audio because this permissions work with Granular Media Permissions, like this:
`Future<void> _getStoragePermission() async {`
    `DeviceInfoPlugin plugin = DeviceInfoPlugin();`
    `AndroidDeviceInfo android = await plugin.androidInfo;`
       `if (android.version.sdkInt < 33) {`
          `if (await Permission.storage.request().isGranted) {`
             `setState(() {`
               `permissionGranted = true;`
             `});`
          `} else if (await Permission.storage.request().isPermanentlyDenied) {`
             `await openAppSettings();`
          `} else if (await Permission.audio.request().isDenied) {`
             `setState(() {`
               `permissionGranted = false;`
             `});`
          `}`
        `} else {`
           `if (await Permission.photos.request().isGranted) {`
                `setState(() {`
                   `permissionGranted = true;`
                `});`
           `} else if (await Permission.photos.request().isPermanentlyDenied) {`
               `await openAppSettings();`
           `} else if (await Permission.photos.request().isDenied) {`
               `setState(() {`
                   `permissionGranted = false;`
               `});`
         `}`
      `}`
`}`

You can read more about that in this [article](https://medium.com/@marcoedomingos/flutter-storage-access-for-android-sdk-33-d19e2b693017)

**Comment by JeroenWeener** [comment] 2023-07-12 07:22
This is a duplicate of #955. In short, Android 13 no longer supports `READ_STORAGE`. Instead, you should request one of the granular media permissions `READ_MEDIA_IMAGES`, `READ_MEDIA_VIDEO` and `READ_MEDIA_AUDIO`.

We have recently documented this in the README: https://pub.dev/packages/permission_handler#faq

**Closed by JeroenWeener** 2023-07-12 07:22 UTC
