### ISSUE TITLE
Permission.location.request() not work for iOS 13

### ISSUE THREAD

**Issue by JDongKhan** [Baseflow/flutter-permission-handler#1087] opened 2023-07-05 11:37 UTC
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

1、run flutter-permission-handler/permission_handler_apple/example project 
2、tap Permission.location
3、see log

```
2023-07-05 19:29:37.420627+0800 Runner[433:51250] flutter: {Permission.location: PermissionStatus.denied}
2023-07-05 19:29:37.420806+0800 Runner[433:51250] flutter: PermissionStatus.denied

```

### Expected results

```
2023-07-05 19:29:37.420627+0800 Runner[433:51250] flutter: {Permission.location: PermissionStatus.granted}
2023-07-05 19:29:37.420806+0800 Runner[433:51250] flutter: PermissionStatus.granted
```

### Actual results

```
2023-07-05 19:29:37.420627+0800 Runner[433:51250] flutter: {Permission.location: PermissionStatus.denied}
2023-07-05 19:29:37.420806+0800 Runner[433:51250] flutter: PermissionStatus.denied

```

### Code sample

<details><summary>Code sample</summary>

```dart
cd flutter-permission-handler/permission_handler_apple/example/lib

```

</details>

### Screenshots or video

https://github.com/Baseflow/flutter-permission-handler/assets/4929805/7a34a4a8-c441-4210-9c57-d19b45cfc48d

![苏宁豆芽图片20230705193541773](https://github.com/Baseflow/flutter-permission-handler/assets/4929805/f4ee9563-40fd-4377-9d2e-438de12f3639)

### Version

10.4.1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console

/Users/sn/fvm/default/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.0 22A380 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.10.5 on channel stable at /Users/sn/fvm/versions/3.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/sn/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode_14_2.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (5 available)
    • MIX 2 (mobile)     • cfad48ed                                 • android-arm64  • Android 8.0.0 (API 26)
    • sn的iPhone (mobile) • 00008101-001E518E21FA001E                • ios            • iOS 16.2 20C65
    • iPhone (mobile)    • 74b200dc411070e7befc1408366a8398d8021873 • ios            • iOS 13.5.1 17F80
    • macOS (desktop)    • macos                                    • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)       • chrome                                   • web-javascript • Google Chrome 110.0.5481.100

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
Process finished with exit code 0

```

</details>

**Comment by JDongKhan** [comment] 2023-07-05 12:18
Maybe _locationManager was released before I clicked on AlertView.

**Comment by JDongKhan** [comment] 2023-07-05 12:28
PermissionManager.m
```
@implementation PermissionManager {
    NSMutableArray <id <PermissionStrategy>> *_strategyInstances;
    id <PermissionStrategy> permissionStrategy;
}


- (void)requestPermissions:(NSArray *)permissions completion:(PermissionRequestCompletion)completion {
    NSMutableDictionary *permissionStatusResult = [[NSMutableDictionary alloc] init];

    if (permissions.count == 0) {
        completion(permissionStatusResult);
        return;
    }
    
    NSMutableSet *requestQueue = [[NSMutableSet alloc] initWithArray:permissions];
        
    for (int i = 0; i < permissions.count; ++i) {
        NSNumber *rawNumberValue = permissions[i];
        int rawValue = rawNumberValue.intValue;
        PermissionGroup permission = (PermissionGroup) rawValue;
        
        permissionStrategy = [PermissionManager createPermissionStrategy:permission];
        [_strategyInstances addObject:permissionStrategy];
        
        
        [permissionStrategy requestPermission:permission completionHandler:^(PermissionStatus permissionStatus) {
            permissionStatusResult[@(permission)] = @(permissionStatus);
            [requestQueue removeObject:@(permission)];
            
            [self->_strategyInstances removeObject:self->permissionStrategy];
            
            if (requestQueue.count == 0) {
                completion(permissionStatusResult);
            }
          
            // Make sure `completion` is called before cleaning up the reference
            // otherwise the `completion` block is also dereferenced on iOS 12 and
            // below (this is most likely a bug in Objective-C which is solved in
            // later versions of the runtime).
            self->permissionStrategy = nil;
        }];
    }
}


```
LocationPermissionStrategy.m

```
- (void)locationManager:(CLLocationManager *)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status {
    if (_permissionStatusHandler == nil || @(_requestedPermission) == nil) {
        return;
    }
    
    if (status == kCLAuthorizationStatusNotDetermined) {
//        _permissionStatusHandler(PermissionStatusDenied);
        return;
    }

    if ((_requestedPermission == PermissionGroupLocationAlways && status == kCLAuthorizationStatusAuthorizedWhenInUse)) {
        _permissionStatusHandler(PermissionStatusDenied);
        return;
    }

    PermissionStatus permissionStatus = [LocationPermissionStrategy
                                         determinePermissionStatus:_requestedPermission authorizationStatus:status];
    
    _permissionStatusHandler(permissionStatus);
}
```

1、Move Up  permissionStrategy
2、remove kCLAuthorizationStatusNotDetermined

This is a temporary solution.

**Comment by JeroenWeener** [comment] 2023-07-05 13:07
Hi @JDongKhan, thank you for opening another issue! We are grateful for your feedback.

This might be related to #1086, although the behavior seems to be slightly different. From the video, it looks like the permission is denied regardless of the user's response.

**Comment by mvanbeusekom** [comment] 2023-07-06 07:24
Hi @JDongKhan, @JeroenWeener,

The problem might have been introduced by me in [this](78b68c42323438dbe9476684682a0a29f42502ae) commit. Most likely what happens is that upon requesting permissions iOS will first trigger the `didChangeAuthorizationStatus` event with the `NotDetermined` status, before showing the permission dialog.

In the commit I updated the code to make sure the completion callback is called as soon as a status update is received, this will complete the `requestPermission` method on the Dart side and no longer await further status updates. 

@JeroenWeener, could you maybe test this theory by putting a breakpoint in the `locationManager:didChangeAuthorizationStatus:` method and validating if it is being called before the permission dialog is shown? If so we should probably remove the call to the completion callback (as shown in the example provided by @JDongKhan).

**Comment by JeroenWeener** [comment] 2023-07-06 12:38
Hi @JDongKhan!

We just published a fix to an issue that looks similar to yours. Since I cannot reproduce the issue you are experiencing, I want to ask you to upgrade to see if the issue has been resolved.

Could you update your version of `permission_handler_apple` to 9.1.3? You can do this by running `flutter pub upgrade` in your project. You can verify you are using the new version by checking `pubspec.lock`.

Can you confirm that this update fixes your problem?

Happy to hear from you!

**Comment by JDongKhan** [comment] 2023-07-07 08:53
@JeroenWeener  @mvanbeusekom 
Thanks  for fix this issue.
After a test,  that's work for me!

**Comment by mvanbeusekom** [comment] 2023-07-07 09:13
Thanks for confirming @JDongKhan, really appreciate you taking the time for submitting the detailed issue. I will go ahead and close the issue.

**Closed by mvanbeusekom** 2023-07-07 09:13 UTC
Labels: platform: ios, status: needs more info, type: bug, P2
