### ISSUE TITLE
No working Files Permission on Android 13 

### ISSUE THREAD

**Issue by DSMan97** [Baseflow/flutter-permission-handler#892] opened 2022-08-18 09:27 UTC
### Expected behavior
Ask permissions for Photo and Video

### Reproduction steps
Use Android with Android 13 and call permission.storage

### Configuration

**Version:** 10.0.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

Android Doc
https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

**Comment by adrianyim** [comment] 2022-08-27 21:34
Same issue. Call `Permission.storage.request()` and the ask permissions for Photo and Video dialog is not showing up.

**Comment by armandojimenez** [comment] 2022-08-31 17:28
Any updates on this?

**Comment by bradv123** [comment] 2022-09-02 20:49
I am also having this issue, is there any workaround for the time being?

**Comment by Theunodb** [comment] 2022-09-14 05:05
A temp workaround is to downgrade your targetSdkVersion to 32, while keeping compileSdkVersion on 33 to cater for firebase requirements.

**Comment by kdokhanx98** [comment] 2022-12-05 11:55
not fixed yet? not working for me for Permission.photos.request()
Android API 31
library version: 10.0.2

**Comment by okbye123** [comment] 2023-03-17 12:28
This might help https://www.youtube.com/watch?v=uMvGpBOT0ZY

**Comment by JeroenWeener** [comment] 2023-06-29 10:27
Closing, as it is a duplicate of #955, and that issue contains more information regarding the issue and possible solutions.

**Closed by JeroenWeener** 2023-06-29 10:27 UTC
