### ISSUE TITLE
How to take Storage/files permission for android 11?

### ISSUE THREAD

**Issue by shofizone** [Baseflow/flutter-permission-handler#480] opened 2021-03-13 04:30 UTC
## 💬 Questions and Help

Some reason its not asking file access permission  in android 11. 
in AndroidManifest.xml
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
      <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
```
And this way I am asking for permission !
```
   Map<Permission, PermissionStatus> statuses = await [
      Permission.mediaLibrary,
      Permission.storage,
      Permission.photos,
    ].request();
```

**Comment by mvanbeusekom** [comment] 2021-03-22 13:15
duplicate of #491. 

Support for `MANAGE_EXTERNAL_STORAGE` has not yet been implemented.

**Closed by mvanbeusekom** 2021-03-22 13:15 UTC

**Comment by aniketsongara** [comment] 2021-03-24 05:08
When you guy's are planing to implement it ?

**Comment by canitez** [comment] 2021-04-15 19:48
If this is not fixed, google play reported that it will restrict apps shortly.
